scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle- mcac d/src/ma n/scala",
        "f natra- nternal/mtls-http/src/ma n/scala",
        "f natra- nternal/mtls-thr ftmux/src/ma n/scala",
        "servo/repo/src/ma n/scala",
    ],
    exports = [
        "f nagle/f nagle- mcac d/src/ma n/scala",
        "f natra- nternal/mtls-http/src/ma n/scala",
        "f natra- nternal/mtls-thr ftmux/src/ma n/scala",
        "servo/repo/src/ma n/scala",
    ],
)
