steps:
- na : 'gcr. o/cloud-bu lders/docker'
  args: ['bu ld', '-t', 'gcr. o/twttr-recos-ml-prod/dataflow-gpu/beam2_39_0_py3_7', '.']
- na : 'gcr. o/cloud-bu lders/docker'
  args: ['push', 'gcr. o/twttr-recos-ml-prod/dataflow-gpu/beam2_39_0_py3_7']
 mages: ['gcr. o/twttr-recos-ml-prod/dataflow-gpu/beam2_39_0_py3_7']