scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "ema lstorage/server/src/ma n/thr ft/com/tw ter/ema lstorage/ap :ema l-storage-serv ce-scala",
        "f natra- nternal/mtls-thr ftmux/src/ma n/scala",
        "f natra/ nject/ nject-thr ft-cl ent",
        "follow-recom ndat ons-serv ce/common/src/ma n/scala/com/tw ter/follow_recom ndat ons/common/cl ents/common",
        "follow-recom ndat ons-serv ce/common/src/ma n/scala/com/tw ter/follow_recom ndat ons/common/models",
        "st ch/st ch-core",
    ],
)
