scala_l brary(
    s ces = ["*.scala"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "src/thr ft/com/tw ter/esc rb rd:t et-annotat on-scala",
        "src/thr ft/com/tw ter/t  l nes/content_features:thr ft-scala",
        "src/thr ft/com/tw ter/t etyp e: d a-ent y-scala",
        "src/thr ft/com/tw ter/t etyp e:t et-scala",
    ],
    exports = [
        "src/thr ft/com/tw ter/t  l nes/content_features:thr ft-scala",
    ],
)
