target(
    na  = "fa ss",
    dependenc es = [
        "ann/src/ma n/java/com/tw ter/ann/fa ss/sw g:sw g-art factory",
    ],
)

java_l brary(
    na  = "sw g-nat ve-ut ls",
    s ces = ["*.java"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [],
)
