scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "src/scala/com/tw ter/ml/featurestore/l b",
        "src/scala/com/tw ter/ml/featurestore/l b/onl ne",
    ],
)
