create_thr ft_l brar es(
    base_na  = "thr ft",
    s ces = [
        "cl ent_ dent f er.thr ft",
        "serv ce.thr ft",
        "s gnal.thr ft",
    ],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependency_roots = [
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft",
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    prov des_java_na  = "uss-thr ft-java",
    prov des_scala_na  = "uss-thr ft-scala",
)
