scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "conf gap /conf gap -core/src/ma n/scala/com/tw ter/t  l nes/conf gap ",
        "servo/dec der",
        "servo/ut l/src/ma n/scala",
    ],
)
