scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "src/scala/com/tw ter/search/blender/serv ces/strato",
        "src/thr ft/com/tw ter/spam/rtf:safety-label-scala",
        "src/thr ft/com/tw ter/spam/rtf:t et-rtf-event-scala",
        "st ch/st ch-core",
        "strato/src/ma n/scala/com/tw ter/strato/catalog",
        "strato/src/ma n/scala/com/tw ter/strato/cl ent",
        "strato/src/ma n/scala/com/tw ter/strato/data",
        "strato/src/ma n/scala/com/tw ter/strato/thr ft",
    ],
)
