scala_l brary(
    s ces = ["*.scala"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle-stats",
        "src/java/com/tw ter/ml/ap :ap -base",
        "src/thr ft/com/tw ter/ml/ap :data-scala",
        "src/thr ft/com/tw ter/ml/ap : nterpretable-model-java",
        "t  l nes/data_process ng/ml_ut l/aggregat on_fra work/ tr cs",
    ],
)
