scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = [
        "bazel-compat ble",
        "logg ng_ mpl_c ck_wh el sted_target",
    ],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "3rdparty/jvm/com/google/guava",
        "f nagle/f nagle- mcac d/src/ma n/scala",
        "src/thr ft/com/tw ter/servo:servo-except on-java",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/serverut l",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)
