res ces(
    na  = "res ces",
    s ces = [
        "*.dyl b",
        "*.so",
        "*.so.0",
        "*.so.1",
        "*.so.3",
        "*.so.5",
        "*.so.6",
    ],
    tags = [
        "bazel-compat ble",
        "bazel-only",
        "v s b l y://v s b l y:pr vate",
    ],
)
