scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "cac /cl ent",
        "f nagle/f nagle- mcac d/src/ma n/scala",
        "f natra/ nject/ nject-core/src/ma n/scala",
        "f natra/ nject/ nject-thr ft-cl ent/src/ma n/scala",
        "st ch/st ch-core",
        "ut l/ut l-core:scala",
        "ut l/ut l-thr ft",
    ],
)
