scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/ nject:gu ce",
        "conf gap /conf gap -core",
        "conf gap /conf gap -dec der",
        "conf gap /conf gap -featuresw c s:v2",
        "featuresw c s/featuresw c s-core",
        "featuresw c s/featuresw c s-core:v2",
        "featuresw c s/featuresw c s-core/src/ma n/scala/com/tw ter/featuresw c s/v2/bu lder",
        "follow-recom ndat ons-serv ce/common/src/ma n/scala/com/tw ter/follow_recom ndat ons/common/base",
        "follow-recom ndat ons-serv ce/common/src/ma n/scala/com/tw ter/follow_recom ndat ons/common/models",
        "follow-recom ndat ons-serv ce/server/src/ma n/scala/com/tw ter/follow_recom ndat ons/conf gap /dec ders",
        "follow-recom ndat ons-serv ce/server/src/ma n/scala/com/tw ter/follow_recom ndat ons/conf gap /params",
    ],
)
