scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle-core/src/ma n",
        "f natra/ nject/ nject-app/src/ma n/java/com/tw ter/ nject/annotat ons",
        "f natra/ nject/ nject-core/src/ma n/scala",
        "relevance-platform/src/ma n/scala/com/tw ter/relevance_platform/s mclustersann/mult cluster",
        "scrooge/scrooge-core/src/ma n/scala",
        "s mclusters-ann/server/src/ma n/scala/com/tw ter/s mclustersann/except ons",
        "s mclusters-ann/thr ft/src/ma n/thr ft:thr ft-scala",
    ],
)
