scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle-core/src/ma n",
        "scrooge/scrooge-core/src/ma n/scala",
        "t etyp e/common/src/thr ft/com/tw ter/t etyp e:serv ce-scala",
        "ut l/ut l-core:scala",
    ],
)
