scala_l brary(
    na  = " nterests_serv ce",
    s ces = [" nterestServ ceCl ent.scala"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/store/ nterests",
        " nterests-serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
        "strato/src/ma n/scala/com/tw ter/strato/catalog",
        "strato/src/ma n/scala/com/tw ter/strato/cl ent",
        "strato/src/ma n/scala/com/tw ter/strato/data",
        "strato/src/ma n/scala/com/tw ter/strato/thr ft",
    ],
)
