create_thr ft_l brar es(
    base_na  = "thr ft",
    s ces = ["*.thr ft"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependency_roots = [
        "f natra- nternal/thr ft/src/ma n/thr ft",
        "product-m xer/core/src/ma n/thr ft/com/tw ter/product_m xer/core:thr ft",
        "src/thr ft/com/tw ter/ads/sc ma:common",
        "src/thr ft/com/tw ter/ml/ap :data",
        "src/thr ft/com/tw ter/recos:recos-common",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft",
        "src/thr ft/com/tw ter/t  l nes/render:thr ft",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql:ap - d a-graphql",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql:top cs-graphql",
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    prov des_java_na  = "cr-m xer-thr ft-java",
    prov des_scala_na  = "cr-m xer-thr ft-scala",
)

create_thr ft_l brar es(
    base_na  = "cr-m xer-scr be",
    s ces = ["*.thr ft"],
    tags = ["bazel-compat ble"],
    dependency_roots = [
        "f natra- nternal/thr ft/src/ma n/thr ft",
        "product-m xer/core/src/ma n/thr ft/com/tw ter/product_m xer/core:thr ft",
        "src/thr ft/com/tw ter/ads/sc ma:common",
        "src/thr ft/com/tw ter/ml/ap :data",
        "src/thr ft/com/tw ter/recos:recos-common",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft",
        "src/thr ft/com/tw ter/t  l nes/render:thr ft",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql",
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    prov des_java_na  = "cr-m xer-scr be-java",
    prov des_scala_na  = "cr-m xer-scr be-scala",
)
