scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f natra/ nject/ nject-thr ft-cl ent",
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/store/strato",
        " rm / rm -core/src/ma n/scala/com/tw ter/ rm /store/common",
        "relevance-platform/src/ma n/scala/com/tw ter/relevance_platform/common/readablestore",
        "representat on-manager/cl ent/src/ma n/scala/com/tw ter/representat on_manager/conf g",
        "representat on-manager/server/src/ma n/thr ft:thr ft-scala",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
        "st ch/st ch-storehaus",
        "strato/src/ma n/scala/com/tw ter/strato/cl ent",
    ],
)
