scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/l haoy :ppr nt",
        "3rdparty/jvm/javax/ nject:javax. nject",
        "conf gap /conf gap -core",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/marshaller/response/urp",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng/response/urp",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/product",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/product",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/product/reg stry",
        "st ch/st ch-core",
        "ut l/ut l-core:scala",
    ],
)
