scala_l brary(
    s ces = ["*.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "featuresw c s/dynmap/src/ma n/scala/com/tw ter/dynmap:dynmap-core",
        "featuresw c s/dynmap/src/ma n/scala/com/tw ter/dynmap/json:dynmap-json",
        "graphql/thr ft/src/ma n/thr ft/com/tw ter/graphql:graphql-scala",
        "ut l/ut l-core:scala",
    ],
)
