scala_l brary(
    s ces = [
        "*.scala",
    ],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "src/scala/com/tw ter/wtf/beam/bq_embedd ng_export:bq_embedd ng_export_l b",
    ],
)
