scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = [
        "bazel-compat ble",
    ],
    dependenc es = [
        "conf gap /conf gap -abdec der",
        "conf gap /conf gap -core",
        "content-recom nder/thr ft/src/ma n/thr ft:thr ft-scala",
        "dec der/src/ma n/scala",
        "d scovery-common/src/ma n/scala/com/tw ter/d scovery/common/conf gap ",
        "featuresw c s/featuresw c s-core",
        "f natra/ nject/ nject-core/src/ma n/scala",
        "fr gate/fr gate-common:base",
        "fr gate/fr gate-common:ut l",
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/cand date",
        " nterests-serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
        "st ch/st ch-storehaus",
        "top c-soc al-proof/server/src/ma n/thr ft:thr ft-scala",
    ],
)
