scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "conf gap /conf gap -core",
        "conf gap /conf gap -core/src/ma n/scala/com/tw ter/t  l nes/conf gap ",
        "servo/dec der",
        "t  l neranker/common/src/ma n/scala/com/tw ter/t  l neranker/model",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/conf g",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/dec der",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/para ters/ut l",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/conf g",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/dec der",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/ut l/bounds",
        "ut l/ut l-stats/src/ma n/scala",
    ],
)
