java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/com/google/ nject:gu ce",
        "3rdparty/jvm/ /un m /ds :fastut l",
        "3rdparty/jvm/org/apac /hadoop:hadoop-cl ent-default",
        "3rdparty/jvm/org/apac /thr ft:l bthr ft",
        "3rdparty/jvm/org/slf4j:slf4j-ap ",
        "src/java/com/tw ter/common/base",
        "src/java/com/tw ter/search/common/f le",
        "src/java/com/tw ter/search/common/ut l/ o",
    ],
)
