create_thr ft_l brar es(
    base_na  = "storage_ nternal",
    s ces = ["*.thr ft"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    generate_languages = [
        "java",
        "scala",
    ],
)
