scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "conf gap /conf gap -core",
        "src/thr ft/com/tw ter/t  l neserv ce/server/ nternal:thr ft-scala",
        "src/thr ft/com/tw ter/t etyp e:t et-scala",
        "t  l neranker/common:model",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/cl entconf g",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/model/t et",
    ],
)
