# L brary for Sc ma.java and ot r ut l  es w h m n mal dependenc es.
java_l brary(
    na  = "base",
    s ces = ["*.java"],
    platform = "java8",
    prov des = art fact(
        org = "com.tw ter.search.common",
        na  = "sc ma-base",
        repo = art factory,
    ),
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/code/f ndbugs:jsr305",
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/commons-lang",
        "3rdparty/jvm/org/apac /lucene:lucene-analyzers-common",
        "3rdparty/jvm/org/apac /lucene:lucene-core",
        "3rdparty/jvm/org/apac /lucene:lucene-facet",
        "3rdparty/jvm/org/apac /thr ft:l bthr ft",
        "src/java/com/tw ter/common/base",
        "src/java/com/tw ter/common/text/ut l:token-ut l",
        "src/thr ft/com/tw ter/search/common:features-java",
        "src/thr ft/com/tw ter/search/common:sc ma-java",
    ],
)
