scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/src/jvm/com/tw ter/storehaus:core",
        "f nagle/f nagle-stats",
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/store",
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/store/strato",
        " rm / rm -core/src/ma n/scala/com/tw ter/ rm /store/common",
        "relevance-platform/src/ma n/scala/com/tw ter/relevance_platform/common/ nject on",
        "src/scala/com/tw ter/storehaus_ nternal/manhattan",
        "src/scala/com/tw ter/tw stly/common",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
        "user-s gnal-serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
    ],
)
