java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/org/apac /hadoop:hadoop-cl ent-default",
        "3rdparty/jvm/org/slf4j:slf4j-ap ",
        "3rdparty/jvm/org/yaml:snakeyaml",
        "src/java/com/tw ter/search/common/f le",
        "src/java/com/tw ter/search/common/ tr cs",
    ],
)
