scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "user-s gnal-serv ce/server/src/ma n/scala/com/tw ter/users gnalserv ce/base",
        "user-s gnal-serv ce/server/src/ma n/scala/com/tw ter/users gnalserv ce/s gnals",
        "user-s gnal-serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
    ],
)
