scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cursor",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/cand date_s ce/strato",
        "strato/conf g/columns/consu r- dent y/bus ness-prof les:bus ness-prof les-strato-cl ent",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql:graphql-scala",
        "strato/src/ma n/scala/com/tw ter/strato/cl ent",
    ],
)
