scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/storehaus:core",
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "ann/src/ma n/thr ft/com/tw ter/ann/common:ann-common-scala",
        " d aserv ces/commons/src/ma n/scala",
    ],
)
