create_thr ft_l brar es(
    base_na  = "ser al zat on",
    s ces = ["*.thr ft"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependency_roots = [
        "src/thr ft/com/tw ter/ml/ap :embedd ng",
    ],
    generate_languages = [
        "java",
        "scala",
    ],
)
