scala_l brary(
    platform = "java11",
    str ct_deps = False,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle-stats",
        "recos- njector/server/src/ma n/scala/com/tw ter/recos njector/cl ents",
        "src/thr ft/com/tw ter/g zmoduck:thr ft-scala",
    ],
)
