scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "dec der/src/ma n/scala",
        "src/scala/com/tw ter/s mclusters_v2/common",
    ],
)
