scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "src/java/com/tw ter/common/text/language:locale-ut l",
        "src/thr ft/com/tw ter/search:earlyb rd-scala",
        "src/thr ft/com/tw ter/search/common:features-scala",
        "src/thr ft/com/tw ter/t  l neranker/server/model:thr ft-scala",
        "t  l nes:conf g-ap -base",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/common/model",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/earlyb rd/common/opt ons",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/earlyb rd/common/ut ls",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/model/cand date",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/model/t et",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/ut l",
        "t  l neserv ce/common/src/ma n/scala/com/tw ter/t  l neserv ce/model",
    ],
    exports = [
        "t  l nes:conf g-ap -base",
    ],
)
