scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne:query",
        "st ch/st ch-core",
    ],
    exports = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne:query",
        "st ch/st ch-core",
    ],
)
