scala_l brary(
    s ces = ["*.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "conf gap /conf gap -core",
        "cr-m xer/server/src/ma n/scala/com/tw ter/cr_m xer/except on",
        "cr-m xer/server/src/ma n/scala/com/tw ter/cr_m xer/param",
        "f natra/ nject/ nject-core/src/ma n/scala",
        "s mclusters-ann/thr ft/src/ma n/thr ft:thr ft-scala",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
    ],
)
