java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    prov des = art fact(
        org = "com.tw ter.search.common.ut l",
        na  = "lang",
        repo = art factory,
    ),
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/code/f ndbugs:jsr305",
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/org/apac /thr ft:l bthr ft",
        "3rdparty/jvm/org/slf4j:slf4j-ap ",
        "src/java/com/tw ter/common/text/language:locale-ut l",
        "src/thr ft/com/tw ter/search/common:constants-java",
    ],
)
