scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "conf gap /conf gap -core/src/ma n/scala/com/tw ter/t  l nes/conf gap ",
        "conf gap /conf gap -dec der/src/ma n/scala/com/tw ter/t  l nes/conf gap /dec der",
        "servo/dec der",
        "servo/ut l/src/ma n/scala",
        "t  l neranker/common/src/ma n/scala/com/tw ter/t  l neranker/model",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/dec der",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/para ters/ut l",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/exper  nt",
        "ut l/ut l-logg ng",
        "ut l/ut l-stats",
    ],
)
