scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "ads-common/logg ngcl ent/src/ma n/scala",
        "src/scala/com/tw ter/ads/ nternal/pcl/serv ce",
        "src/scala/com/tw ter/ads/ nternal/pcl/strato_adaptor",
        "src/thr ft/com/tw ter/ads/adserver:ads_shared_types-scala",
        "src/thr ft/com/tw ter/ads/callback:engage nt_request-scala",
        "src/thr ft/com/tw ter/ads/ nternal/pcl:promoted_content_ nput-scala",
        "t etyp e/common/src/thr ft/com/tw ter/t etyp e:t et_serv ce_graphql-scala",
        "strato/src/ma n/scala/com/tw ter/strato/server/context",
        "tw ter-context/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)
