scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/spot fy:annoy-java",
        "3rdparty/jvm/com/spot fy:annoy-snapshot",
        "3rdparty/jvm/com/tw ter/storehaus:core",
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "ann/src/ma n/scala/com/tw ter/ann/f le_store",
        "ann/src/ma n/thr ft/com/tw ter/ann/common:ann-common-scala",
        " d aserv ces/commons",
        "src/java/com/tw ter/search/common/f le",
        "src/scala/com/tw ter/ml/ap /embedd ng",
    ],
    exports = [
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "src/java/com/tw ter/common_ nternal/hadoop",
        "src/java/com/tw ter/search/common/f le",
        "src/scala/com/tw ter/ml/ap /embedd ng",
    ],
)
