create_thr ft_l brar es(
    base_na  = "thr ft",
    s ces = ["*.thr ft"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependency_roots = [
        "f natra- nternal/thr ft/src/ma n/thr ft",
        "follow-recom ndat ons-serv ce/thr ft/src/ma n/thr ft/logg ng:thr ft",
        "product-m xer/core/src/ma n/thr ft/com/tw ter/product_m xer/core:thr ft",
        "src/thr ft/com/tw ter/ads/adserver:adserver_common",
        "src/thr ft/com/tw ter/ml/ap :data",
        "src/thr ft/com/tw ter/suggests/controller_data",
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    prov des_java_na  = "follow-recom ndat ons-java",
    prov des_scala_na  = "follow-recom ndat ons-scala",
)
