na space java com.tw ter.follow_recom ndat ons.thr ftjava
#@na space scala com.tw ter.follow_recom ndat ons.thr ftscala
#@na space strato com.tw ter.follow_recom ndat ons

 nclude "assembler.thr ft"
 nclude "cl ent_context.thr ft"
 nclude "debug.thr ft"
 nclude "d splay_context.thr ft"
 nclude "d splay_locat on.thr ft"
 nclude "recom ndat ons.thr ft"
 nclude "recently_engaged_user_ d.thr ft"

 nclude "f natra-thr ft/f natra_thr ft_except ons.thr ft"
 nclude "com/tw ter/product_m xer/core/p pel ne_execut on_result.thr ft"

struct Recom ndat onRequest {
    1: requ red cl ent_context.Cl entContext cl entContext
    2: requ red d splay_locat on.D splayLocat on d splayLocat on
    3: opt onal d splay_context.D splayContext d splayContext
    // Max results to return
    4: opt onal  32 maxResults
    // Cursor to cont nue return ng results  f any
    5: opt onal str ng cursor
    //  Ds of Content to exclude from recom ndat ons
    6: opt onal l st< 64> excluded ds(personalDataType='User d')
    // W t r to also get promoted content
    7: opt onal bool fetchPromotedContent
    8: opt onal debug.DebugParams debugParams
    9: opt onal str ng userLocat onState(personalDataType=' nferredLocat on')
}(hasPersonalData='true')


struct Recom ndat onResponse {
    1: requ red l st<recom ndat ons.Recom ndat on> recom ndat ons
}(hasPersonalData='true')

// for scor ng a l st of cand dates, wh le logg ng hydrated features
struct Scor ngUserRequest {
  1: requ red cl ent_context.Cl entContext cl entContext
  2: requ red d splay_locat on.D splayLocat on d splayLocat on
  3: requ red l st<recom ndat ons.UserRecom ndat on> cand dates
  4: opt onal debug.DebugParams debugParams
}(hasPersonalData='true')

struct Scor ngUserResponse {
  1: requ red l st<recom ndat ons.UserRecom ndat on> cand dates // empty for now
}(hasPersonalData='true')

// for gett ng t  l st of cand dates generated by a s ngle cand date s ce
struct DebugCand dateS ceRequest {
  1: requ red cl ent_context.Cl entContext cl entContext
  2: requ red debug.DebugCand dateS ce dent f er cand dateS ce
  3: opt onal l st< 64> utt nterest ds
  4: opt onal debug.DebugParams debugParams
  5: opt onal l st< 64> recentlyFollo dUser ds
  6: opt onal l st<recently_engaged_user_ d.RecentlyEngagedUser d> recentlyEngagedUser ds
  7: opt onal l st< 64> byfSeedUser ds
  8: opt onal l st< 64> s m larToUser ds
  9: requ red bool applySgsPred cate
  10: opt onal  32 maxResults
}(hasPersonalData='true')

serv ce FollowRecom ndat onsThr ftServ ce {
  Recom ndat onResponse getRecom ndat ons(1: Recom ndat onRequest request) throws (
    1: f natra_thr ft_except ons.ServerError serverError,
    2: f natra_thr ft_except ons.UnknownCl ent dError unknownCl ent dError,
    3: f natra_thr ft_except ons.NoCl ent dError noCl ent dError
  )
  Recom ndat onD splayResponse getRecom ndat onD splayResponse(1: Recom ndat onRequest request) throws (
    1: f natra_thr ft_except ons.ServerError serverError,
    2: f natra_thr ft_except ons.UnknownCl ent dError unknownCl ent dError,
    3: f natra_thr ft_except ons.NoCl ent dError noCl ent dError
  )
  // temporary endpo nt for feature hydrat on and logg ng for data collect on.
  Scor ngUserResponse scoreUserCand dates(1: Scor ngUserRequest request) throws (
    1: f natra_thr ft_except ons.ServerError serverError,
    2: f natra_thr ft_except ons.UnknownCl ent dError unknownCl ent dError,
    3: f natra_thr ft_except ons.NoCl ent dError noCl ent dError
  )
  // Debug endpo nt for gett ng recom ndat ons of a s ngle cand date s ce.   can remove t  endpo nt w n ProM x prov de t  funct onal y and    ntegrate w h  .
  Recom ndat onResponse debugCand dateS ce(1: DebugCand dateS ceRequest request) throws (
      1: f natra_thr ft_except ons.ServerError serverError,
      2: f natra_thr ft_except ons.UnknownCl ent dError unknownCl ent dError,
      3: f natra_thr ft_except ons.NoCl ent dError noCl ent dError
  )

  // Get t  full execut on log for a p pel ne (used by   debugg ng tools)
  p pel ne_execut on_result.P pel neExecut onResult executeP pel ne(1: Recom ndat onRequest request) throws (
    1: f natra_thr ft_except ons.ServerError serverError,
    2: f natra_thr ft_except ons.UnknownCl ent dError unknownCl ent dError,
    3: f natra_thr ft_except ons.NoCl ent dError noCl ent dError
  )
}

struct Recom ndat onD splayResponse {
 1: requ red l st<recom ndat ons.HydratedRecom ndat on> hydratedRecom ndat on
 2: opt onal assembler. ader  ader
 3: opt onal assembler.Footer footer
 4: opt onal assembler.WTFPresentat on wtfPresentat on
}(hasPersonalData='true')
