create_thr ft_l brar es(
    base_na  = " nteract on_graph",
    s ces = ["*.thr ft"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependency_roots = [
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    prov des_java_na  = " nteract on_graph-thr ft-java",
    prov des_scala_na  = " nteract on_graph-thr ft-scala",
)
