scala_l brary(
    s ces = [
        "*.scala",
    ],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "src/scala/com/tw ter/search/blender/serv ces/strato",
        "src/thr ft/com/tw ter/search/common:constants-scala",
        "st ch/st ch-core",
    ],
)
