create_thr ft_l brar es(
    org = "com.tw ter.un f ed_user_act ons.enr c r",
    base_na  = " nternal",
    s ces = ["*.thr ft"],
    tags = ["bazel-compat ble"],
    dependency_roots = [
        "src/thr ft/com/tw ter/cl entapp/gen:cl entapp",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons",
    ],
    generate_languages = [
        "java",
        "scala",
    ],
    prov des_java_na  = "enr c r_ nternal-thr ft-java",
    prov des_scala_na  = "enr c r_ nternal-thr ft-scala",
)
