# T  keys  n t  f le correspond to t  Dec derValues def ned  n
# https://s cegraph.tw ter.b z/g .tw ter.b z/s ce/-/blob/cr-m xer/server/src/ma n/scala/com/tw ter/cr_m xer/param/dec der/Dec derKey.scala

dark_traff c_f lter:
  com nt: Proport on of t  requests that are forwarded as dark traff c to t  proxy
  default_ava lab l y: 0

enable_t et_recom ndat ons_ho _product:
  com nt: Proport on of requests w re   return an actual response for T etRecom ndat ons Ho  product
  default_ava lab l y: 10000

enable_t et_ alth_score:
  com nt: "Enable t  calculat on for  alth scores  n t et nfo. By enabl ng t  dec der,   w ll compute T et althModelScore"
  default_ava lab l y: 10000

enable_user_agatha_score:
  com nt: "Enable t  calculat on for  alth scores  n t et nfo. By enabl ng t  dec der,   w ll compute User althModelScore"
  default_ava lab l y: 10000

enable_user_t et_ent y_graph_traff c:
  com nt: "Enable t  traff c to user ent y t et graph to fetch l ked-by t ets cand dates"
  default_ava lab l y: 10000

enable_user_t et_graph_traff c:
  com nt: "Enable t  traff c to user t et graph to fetch s m lar t ets cand dates"
  default_ava lab l y: 10000

enable_user_v deo_graph_traff c:
  com nt: "Enable t  traff c to user v deo graph to fetch s m lar t ets cand dates"
  default_ava lab l y: 10000

enable_user_ad_graph_traff c:
  com nt: "Enable t  traff c to user ad graph to fetch s m lar t ets cand dates"
  default_ava lab l y: 10000

enable_q g_s m lar_t ets_traff c:
  com nt: "Enable t  traff c to Q G to fetch s m lar t et cand dates"
  default_ava lab l y: 0

enable_frs_traff c:
  com nt: "Enable t  traff c to FRS to fetch user follow recom ndat ons"
  default_ava lab l y: 0

enable_hydra_dark_traff c:
  com nt: "Enable dark traff c to hydra"
  default_ava lab l y: 0

enable_real_graph_mh_store:
  com nt: "Enable traff c for t  real graph manhattan based store"
  default_ava lab l y: 0

enable_s mclusters_ann_exper  ntal_dark_traff c:
  com nt: "Enable dark traff c to s mclusters-ann-exper  ntal"
  default_ava lab l y: 0

enable_s mclusters_ann_2_dark_traff c:
  com nt: "Enable dark traff c to prod S mClustersANN2"
  default_ava lab l y: 0

enable_user_state_store:
  com nt: "Enable traff c user state store to hydrate user state"
  default_ava lab l y: 0

upper_funnel_per_step_scr be_rate:
  com nt: "Enable Upper Funnel Event Scr be Sampl ng (fetch, pre-rank,  nterleave etc.) for getT etsRecom ndat ons() endpo nt"
  default_ava lab l y: 0

kafka_ ssage_scr be_sample_rate:
  com nt: "Gates t  product on of forked scr be  ssages to kafka for t  async feature hydrator"
  default_ava lab l y: 0

top_level_ap _ddg_ tr cs_scr be_rate:
  com nt: "Enable Top Level AP  DDG  tr cs Scr be Sampl ng for getT etsRecom ndat ons() endpo nt"
  default_ava lab l y: 0

ads_recom ndat ons_per_exper  nt_scr be_rate:
  com nt: "Percentage of DDG traff c to Scr be for getAdsRecom ndat ons() endpo nt"
  default_ava lab l y: 0

enable_loads dd ng_getT etRecom ndat ons:
  com nt: "Enable loads dd ng (from 0% to 100%). Requests that have been s d w ll return an empty response"
  default_ava lab l y: 0

enable_loads dd ng_getT etRecom ndat ons_Ho :
  com nt: "Enable loads dd ng (from 0% to 100%). Requests that have been s d w ll return an empty response"
  default_ava lab l y: 0

enable_loads dd ng_getT etRecom ndat ons_Not f cat ons:
  com nt: "Enable loads dd ng (from 0% to 100%). Requests that have been s d w ll return an empty response"
  default_ava lab l y: 0

enable_loads dd ng_getT etRecom ndat ons_Ema l:
  com nt: "Enable loads dd ng (from 0% to 100%). Requests that have been s d w ll return an empty response"
  default_ava lab l y: 0

enable_loads dd ng_getRelatedT etsForQueryT et:
  com nt: "Enable loads dd ng (from 0% to 100%). Requests that have been s d w ll return an empty response"
  default_ava lab l y: 0

enable_loads dd ng_getRelatedT etsForQueryT et_Ho :
  com nt: "Enable loads dd ng (from 0% to 100%). Requests that have been s d w ll return an empty response"
  default_ava lab l y: 0

enable_loads dd ng_getRelatedT etsForQueryT et_MoreT etsModule:
  com nt: "Enable loads dd ng (from 0% to 100%). Requests that have been s d w ll return an empty response"
  default_ava lab l y: 0

enable_loads dd ng_getRelatedT etsForQueryAuthor:
  com nt: "Enable loads dd ng (from 0% to 100%). Requests that have been s d w ll return an empty response"
  default_ava lab l y: 0

enable_loads dd ng_getRelatedT etsForQueryAuthor_MoreT etsModule:
  com nt: "Enable loads dd ng (from 0% to 100%). Requests that have been s d w ll return an empty response"
  default_ava lab l y: 0

enable_loads dd ng_getFrsBasedT etRecom ndat ons_Ho :
  com nt: "Enable loads dd ng (from 0% to 100%). Requests that have been s d w ll return an empty response"
  default_ava lab l y: 0

enable_loads dd ng_getFrsBasedT etRecom ndat ons_Not f cat ons:
  com nt: "Enable loads dd ng (from 0% to 100%). Requests that have been s d w ll return an empty response"
  default_ava lab l y: 0

enable_user_ d a_representat on_store:
  com nt: "Enable fetch ng user nud y rate s gnal from  d a Understand ng"
  default_ava lab l y: 0

enable_mag c_recs_real_t  _aggregates_store:
  com nt: "Enable fetch ng real t   aggregates features from Mag c Recs  mcac "
  default_ava lab l y: 0

enable_utg_realt  _t et_engage nt_score:
  com nt: "Enable fetch ng real t   t et engage nt score from utg-plus"
  default_ava lab l y: 0

get_t et_recom ndat ons_cac _rate:
  com nt: "Proport on of users w re getT etRecom ndat ons() request and responses w ll be cac d"
  default_ava lab l y: 1000

enable_earlyb rd_traff c:
  com nt: "Enable fetch ng t et cand dates from Earlyb rd"
  default_ava lab l y: 0

enable_scr be_for_blue_ver f ed_t et_cand dates:
  com nt: "Enable scr b ng for t et cand dates from Blue Ver f ed users"
  default_ava lab l y: 0
