java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/ nject:gu ce",
        "src/java/com/tw ter/common/base",
        "src/java/com/tw ter/search/common/ tr cs",
        "src/thr ft/com/tw ter/search/feature_update_serv ce/thr ft:thr ft-java",
    ],
)
