scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "servo/repo/src/ma n/scala",
        "src/thr ft/com/tw ter/wtf/cand date:wtf-cand date-scala",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/core",
        "t  l nes:v s b l y",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/cl ents/soc algraph",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/ut l",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/ut l/stats",
        "ut l/ut l-core:ut l-core-ut l",
        "ut l/ut l-logg ng/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala",
    ],
)
