# Java l brary for feature encod ng and decod ng ut l  es.
java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    prov des = art fact(
        org = "com.tw ter.search.common",
        na  = "encod ng-features",
        repo = art factory,
    ),
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/org/apac /thr ft:l bthr ft",
        "src/java/com/tw ter/search/common/sc ma/base",
        "src/thr ft/com/tw ter/search/common: ndex ng-java",
    ],
)
