scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "abdec der/src/ma n/scala",
        "conf gap /conf gap -abdec der",
        "conf gap /conf gap -core",
        "conf gap /conf gap -featuresw c s:v2",
        "dec der",
        "featuresw c s/featuresw c s-core/src/ma n/scala",
        "f nagle/f nagle-stats",
        "servo/dec der/src/ma n/scala",
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/conf gap /conf gs",
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/models",
    ],
)
