scala_l brary(
    na  = "common",
    s ces = [
        "BaseQuery ndexServer.scala",
        "Except ons.scala",
        "Query ndexThr ftController.scala",
        "QueryableProv der.scala",
        "RefreshableQueryable.scala",
        "UnsafeQuery ndexServer.scala",
    ],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        ": ndex_path_prov der",
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/com/google/ nject:gu ce",
        "3rdparty/jvm/com/google/ nject/extens ons:gu ce-ass sted nject",
        "3rdparty/jvm/javax/ nject:javax. nject",
        "3rdparty/jvm/net/cod ng ll:scala-gu ce",
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "ann/src/ma n/thr ft/com/tw ter/ann/common:ann-common-scala",
        "f nagle/f nagle-core/src/ma n",
        "f nagle/f nagle-z pk n-scr be",
        "f natra- nternal/dec der",
        "f natra- nternal/mtls-thr ftmux/src/ma n/scala",
        "f natra/ nject/ nject-core/src/ma n/scala",
        " d aserv ces/commons",
        "scrooge/scrooge-core/src/ma n/scala",
        "src/scala/com/tw ter/cortex/ml/embedd ngs/common: lpers",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-logg ng/src/ma n/scala",
    ],
)

scala_l brary(
    na  = " ndex_path_prov der",
    s ces = [
        " ndexPathProv der.scala",
        "QueryServerUt l.scala",
    ],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "ann/src/ma n/scala/com/tw ter/ann/hnsw",
        "src/java/com/tw ter/search/common/f le",
        "ut l/ut l-logg ng/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "fa ss_ ndex_path_prov der",
    s ces = ["Fa ss ndexPathProv der.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        ": ndex_path_prov der",
        "ann/src/ma n/scala/com/tw ter/ann/fa ss",
        "src/java/com/tw ter/search/common/f le",
        "ut l/ut l-logg ng/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)
