scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    prov des = scala_art fact(
        org = "com.tw ter.t etyp e",
        na  = "context",
        repo = art factory,
    ),
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle-core/src/ma n",
        "graphql/common/src/ma n/scala/com/tw ter/graphql/common/core",
        "src/thr ft/com/tw ter/context:tw ter-context-scala",
        "tw ter-context/src/ma n/scala",
        "ut l/ut l-core:scala",
    ],
)
