jvm_b nary(
    na  = "b n",
    basena  = "top c-soc al-proof",
    ma n = "com.tw ter.tsp.Top cSoc alProofStratoFedServerMa n",
    runt  _platform = "java11",
    tags = [
        "bazel-compat ble",
    ],
    dependenc es = [
        "strato/src/ma n/scala/com/tw ter/strato/logg ng/logback",
        "top c-soc al-proof/server/src/ma n/res ces",
        "top c-soc al-proof/server/src/ma n/scala/com/tw ter/tsp",
    ],
)

#  Aurora Workflows bu ld phase convent on requ res a jvm_app na d w h ${project-na }-app
jvm_app(
    na  = "top c-soc al-proof-app",
    arch ve = "z p",
    b nary = ":b n",
    tags = [
        "bazel-compat ble",
    ],
)
