target(
    na  = "earlyb rd_rank ng",
    dependenc es = [
        "t  l nes/data_process ng/ad_hoc/earlyb rd_rank ng/common",
        "t  l nes/data_process ng/ad_hoc/earlyb rd_rank ng/model_evaluat on",
        "t  l nes/data_process ng/ad_hoc/earlyb rd_rank ng/tra n ng_data_generat on",
    ],
)
