# ---------- traff c percentage by embedd ng type and model vers on ----------
# Dec der str ngs are bu ld dynam cally follow ng t  rule  n t re
#  .e. s"enable_${embedd ngType.na }_${modelVers on.na }"
#  nce t  should be updated accord ngly  f usage  s changed  n t  embedd ng stores

# T et embedd ngs
"enable_LogFavBasedT et_Model20m145k2020":
  com nt: "Enable x% read traff c (0<=x<=10000, e.g. 1000=10%) for LogFavBasedT et - Model20m145k2020. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_LogFavBasedT et_Model20m145kUpdated":
  com nt: "Enable x% read traff c (0<=x<=10000, e.g. 1000=10%) for LogFavBasedT et - Model20m145kUpdated. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_LogFavLongestL2Embedd ngT et_Model20m145k2020":
  com nt: "Enable x% read traff c (0<=x<=10000, e.g. 1000=10%) for LogFavLongestL2Embedd ngT et - Model20m145k2020. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_LogFavLongestL2Embedd ngT et_Model20m145kUpdated":
  com nt: "Enable x% read traff c (0<=x<=10000, e.g. 1000=10%) for LogFavLongestL2Embedd ngT et - Model20m145kUpdated. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

# Top c embedd ngs
"enable_FavTfgTop c_Model20m145k2020":
  com nt: "Enable t  read traff c to FavTfgTop c - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_LogFavBasedKgoApeTop c_Model20m145k2020":
  com nt: "Enable t  read traff c to LogFavBasedKgoApeTop c - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

# User embedd ngs - KnownFor
"enable_FavBasedProducer_Model20m145kUpdated":
  com nt: "Enable t  read traff c to FavBasedProducer - Model20m145kUpdated from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_FavBasedProducer_Model20m145k2020":
  com nt: "Enable t  read traff c to FavBasedProducer - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_FollowBasedProducer_Model20m145k2020":
  com nt: "Enable t  read traff c to FollowBasedProducer - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_AggregatableFavBasedProducer_Model20m145kUpdated":
  com nt: "Enable t  read traff c to AggregatableFavBasedProducer - Model20m145kUpdated from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_AggregatableFavBasedProducer_Model20m145k2020":
  com nt: "Enable t  read traff c to AggregatableFavBasedProducer - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_AggregatableLogFavBasedProducer_Model20m145kUpdated":
  com nt: "Enable t  read traff c to AggregatableLogFavBasedProducer - Model20m145kUpdated from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_AggregatableLogFavBasedProducer_Model20m145k2020":
  com nt: "Enable t  read traff c to AggregatableLogFavBasedProducer - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_RelaxedAggregatableLogFavBasedProducer_Model20m145kUpdated:
  com nt: "Enable t  read traff c to RelaxedAggregatableLogFavBasedProducer - Model20m145kUpdated from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_RelaxedAggregatableLogFavBasedProducer_Model20m145k2020:
  com nt: "Enable t  read traff c to RelaxedAggregatableLogFavBasedProducer - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

# User embedd ngs -  nterested n
"enable_LogFavBasedUser nterested nFromAPE_Model20m145k2020":
  com nt: "Enable t  read traff c to LogFavBasedUser nterested nFromAPE - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_FollowBasedUser nterested nFromAPE_Model20m145k2020":
  com nt: "Enable t  read traff c to FollowBasedUser nterested nFromAPE - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_FavBasedUser nterested n_Model20m145kUpdated":
  com nt: "Enable t  read traff c to FavBasedUser nterested n - Model20m145kUpdated from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_FavBasedUser nterested n_Model20m145k2020":
  com nt: "Enable t  read traff c to FavBasedUser nterested n - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_FollowBasedUser nterested n_Model20m145k2020":
  com nt: "Enable t  read traff c to FollowBasedUser nterested n - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_LogFavBasedUser nterested n_Model20m145k2020":
  com nt: "Enable t  read traff c to LogFavBasedUser nterested n - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_FavBasedUser nterested nFromPE_Model20m145kUpdated":
  com nt: "Enable t  read traff c to FavBasedUser nterested nFromPE - Model20m145kUpdated from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_F lteredUser nterested n_Model20m145kUpdated":
  com nt: "Enable t  read traff c to F lteredUser nterested n - Model20m145kUpdated from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_F lteredUser nterested n_Model20m145k2020":
  com nt: "Enable t  read traff c to F lteredUser nterested n - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_F lteredUser nterested nFromPE_Model20m145kUpdated":
  com nt: "Enable t  read traff c to F lteredUser nterested nFromPE - Model20m145kUpdated from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_Unf lteredUser nterested n_Model20m145kUpdated":
  com nt: "Enable t  read traff c to Unf lteredUser nterested n - Model20m145kUpdated from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_Unf lteredUser nterested n_Model20m145k2020":
  com nt: "Enable t  read traff c to Unf lteredUser nterested n - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_UserNext nterested n_Model20m145k2020":
  com nt: "Enable t  read traff c to UserNext nterested n - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_LogFavBasedUser nterestedMaxpool ngAddressBookFrom  APE_Model20m145k2020":
  com nt: "Enable t  read traff c to LogFavBasedUser nterestedMaxpool ngAddressBookFrom  APE - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_LogFavBasedUser nterestedAverageAddressBookFrom  APE_Model20m145k2020":
  com nt: "Enable t  read traff c to LogFavBasedUser nterestedAverageAddressBookFrom  APE - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_LogFavBasedUser nterestedBooktypeMaxpool ngAddressBookFrom  APE_Model20m145k2020":
  com nt: "Enable t  read traff c to LogFavBasedUser nterestedMaxpool ngAddressBookFrom  APE - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_LogFavBasedUser nterestedLargestD mMaxpool ngAddressBookFrom  APE_Model20m145k2020":
  com nt: "Enable t  read traff c to LogFavBasedUser nterestedAverageAddressBookFrom  APE - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_LogFavBasedUser nterestedLouva nMaxpool ngAddressBookFrom  APE_Model20m145k2020":
  com nt: "Enable t  read traff c to LogFavBasedUser nterestedMaxpool ngAddressBookFrom  APE - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

"enable_LogFavBasedUser nterestedConnectedMaxpool ngAddressBookFrom  APE_Model20m145k2020":
  com nt: "Enable t  read traff c to LogFavBasedUser nterestedAverageAddressBookFrom  APE - Model20m145k2020 from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

# ---------- load s dd ng by caller  d ----------
# To create a new dec der, add  re w h t  sa  format and caller's deta ls :
# "representat on-manager_load_s d_by_caller_ d_twtr:{{role}}:{{na }}:{{env ron nt}}:{{cluster}}"
# All t  dec ders below are generated by t  scr pt:
# ./strato/b n/fed dec ders representat on-manager --serv ce-role=representat on-manager --serv ce-na =representat on-manager
#  f   need to run t  scr pt and paste t  output, add ONLY t  prod dec ders  re.
"representat on-manager_load_s d_by_caller_ d_all":
  com nt: "Reject all traff c from caller  d: all"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:cr-m xer:cr-m xer:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:cr-m xer:cr-m xer:prod:atla"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:cr-m xer:cr-m xer:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:cr-m xer:cr-m xer:prod:pdxa"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:s mclusters-ann:s mclusters-ann-1:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:s mclusters-ann:s mclusters-ann-1:prod:atla"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:s mclusters-ann:s mclusters-ann-1:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:s mclusters-ann:s mclusters-ann-1:prod:pdxa"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:s mclusters-ann:s mclusters-ann-3:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:s mclusters-ann:s mclusters-ann-3:prod:atla"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:s mclusters-ann:s mclusters-ann-3:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:s mclusters-ann:s mclusters-ann-3:prod:pdxa"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:s mclusters-ann:s mclusters-ann-4:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:s mclusters-ann:s mclusters-ann-4:prod:atla"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:s mclusters-ann:s mclusters-ann-4:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:s mclusters-ann:s mclusters-ann-4:prod:pdxa"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:s mclusters-ann:s mclusters-ann-exper  ntal:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:s mclusters-ann:s mclusters-ann-exper  ntal:prod:atla"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:s mclusters-ann:s mclusters-ann-exper  ntal:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:s mclusters-ann:s mclusters-ann-exper  ntal:prod:pdxa"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:s mclusters-ann:s mclusters-ann:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:s mclusters-ann:s mclusters-ann:prod:atla"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:s mclusters-ann:s mclusters-ann:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:s mclusters-ann:s mclusters-ann:prod:pdxa"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:stratostore:stratoap :prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:stratostore:stratoap :prod:atla"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:stratostore:stratoserver:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:stratostore:stratoserver:prod:atla"
  default_ava lab l y: 0

"representat on-manager_load_s d_by_caller_ d_twtr:svc:stratostore:stratoserver:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:stratostore:stratoserver:prod:pdxa"
  default_ava lab l y: 0

# ---------- Dark Traff c Proxy ----------
representat on-manager_forward_dark_traff c:
  com nt: "Def nes t  percentage of traff c to forward to d ffy-proxy. Set to 0 to d sable dark traff c forward ng"
  default_ava lab l y: 0
