scala_l brary(
    s ces = ["*.scala"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/algeb rd:core",
        "src/java/com/tw ter/ml/ap :ap -base",
        "src/java/com/tw ter/ml/ap /constant",
        "src/scala/com/tw ter/ml/ap /ut l:datarecord",
        "src/thr ft/com/tw ter/dal/personal_data:personal_data-java",
        "src/thr ft/com/tw ter/ml/ap :data-java",
        "src/thr ft/com/tw ter/ml/ap : nterpretable-model-java",
        "ut l/ut l-core:scala",
    ],
)
