scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/slf4j:slf4j-ap ",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common",
        "ut l/ut l-slf4j-ap /src/ma n/scala",
    ],
)
