scala_l brary(
    na  = "default",
    s ces = ["DefaultPart  oner.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        ":base",
        "un f ed_user_act ons/enr c r/src/ma n/thr ft/com/tw ter/un f ed_user_act ons/enr c r/ nternal: nternal-scala",
    ],
)

scala_l brary(
    na  = "base",
    s ces = ["Part  oner.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "un f ed_user_act ons/enr c r/src/ma n/thr ft/com/tw ter/un f ed_user_act ons/enr c r/ nternal: nternal-scala",
    ],
)
