scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle- nternal/slo/src/ma n/scala/com/tw ter/f nagle/slo",
        "f natra/ nject/ nject-thr ft-cl ent",
        "representat on-scorer/server/src/ma n/scala/com/tw ter/representat onscorer/columns",
        "strato/src/ma n/scala/com/tw ter/strato/fed",
        "strato/src/ma n/scala/com/tw ter/strato/fed/server",
        "tw ter-server- nternal/src/ma n/scala",
    ],
)
