scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "conf gap /conf gap -core",
        "conf gap /conf gap -dec der",
        "servo/dec der",
        "ut l/ut l-core:ut l-core-ut l",
        "ut l/ut l-logg ng",
    ],
    exports = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "conf gap /conf gap -core",
        "conf gap /conf gap -dec der",
        "servo/dec der",
        "ut l/ut l-core:ut l-core-ut l",
        "ut l/ut l-logg ng",
    ],
)
