scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "t etyp e/servo/repo",
        "t etyp e/servo/ut l",
        "snowflake: d",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/core",
        "t etyp e/server/src/ma n/thr ft:comp led-scala",
        "ut l/ut l-slf4j-ap /src/ma n/scala/com/tw ter/ut l/logg ng",
    ],
)
