scala_l brary(
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle-stats",
        " rm / rm -core/src/ma n/scala/com/tw ter/ rm /store/common",
        "src/scala/com/tw ter/s mclusters_v2/stores",
    ],
)
