scala_l brary(
    s ces = ["*.scala"],
    platform = "java8",
    str ct_deps = False,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/graphjet",
        "f nagle/f nagle-stats/src/ma n/scala",
        "src/scala/com/tw ter/recos/ut l:recos-ut l",
        "src/thr ft/com/tw ter/recos:recos-common-scala",
    ],
)
