scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "src/scala/com/tw ter/ml/ap /ut l:datarecord",
        "src/scala/com/tw ter/ml/featurestore/l b/data",
        "src/scala/com/tw ter/ml/featurestore/l b/dynam c",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "src/scala/com/tw ter/ml/ap /ut l:datarecord",
        "src/scala/com/tw ter/ml/featurestore/l b/data",
        "src/scala/com/tw ter/ml/featurestore/l b/dynam c",
    ],
)
