scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f natra/ nject/ nject-thr ft-cl ent",
        "representat on-manager/server/src/ma n/scala/com/tw ter/representat on_manager/common",
        "representat on-manager/server/src/ma n/thr ft:thr ft-scala",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
        "strato/src/ma n/scala/com/tw ter/strato/cl ent",
    ],
)
