scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle-core/src/ma n",
        " ncent ves/j m ny/src/ma n/thr ft/com/tw ter/ ncent ves/j m ny:thr ft-scala",
        "t etyp e/servo/ut l/src/ma n/scala",
        "st ch/st ch-core",
        "strato/src/ma n/scala/com/tw ter/strato/cl ent",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/core",
        "ut l/ut l-core",
        "ut l/ut l-stats",
    ],
)
