create_thr ft_l brar es(
    base_na  = "thr ft",
    s ces = ["*.thr ft"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependency_roots = [
        "src/thr ft/com/tw ter/ads/adserver:adserver_common",
        "src/thr ft/com/tw ter/ml/ap :data",
        "src/thr ft/com/tw ter/suggests/controller_data",
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    prov des_java_na  = "follow-recom ndat ons-logg ng-java",
    prov des_scala_na  = "follow-recom ndat ons-logg ng-scala",
)
