scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/cand date_s ce/strato",
        "src/thr ft/com/tw ter/t  l nes/ mpress on:thr ft-scala",
        "strato/conf g/columns/t  l nes/ mpress on-store: mpress on-store-strato-cl ent",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/cand date_s ce/strato",
        "strato/conf g/columns/t  l nes/ mpress on-store: mpress on-store-strato-cl ent",
    ],
)
