scala_l brary(
    s ces = ["*.scala"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "src/scala/com/tw ter/scald ng_ nternal/mult format/format",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/thr ft/com/tw ter/ rm /cand date: rm -cand date-scala",
        "src/thr ft/com/tw ter/ml/ap :embedd ng-scala",
        "src/thr ft/com/tw ter/recos/ent  es:ent  es-thr ft-scala",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
    ],
)
