scala_l brary(
    na  = "common",
    s ces = ["*.scala"],
    platform = "java8",
    tags = [
        "bazel-compat ble",
        "bazel-compat ble:m grated",
    ],
    dependenc es = [
        "src/java/com/tw ter/ml/ap :ap -base",
        "src/java/com/tw ter/ml/ap /constant",
        "src/java/com/tw ter/ml/ap /transform",
        "src/java/com/tw ter/search/model ng/t et_rank ng",
        "src/scala/com/tw ter/ml/ap /ut l",
        "src/scala/com/tw ter/t  l nes/pred ct on/features/common",
        "src/scala/com/tw ter/t  l nes/pred ct on/features/ l",
        "src/scala/com/tw ter/t  l nes/pred ct on/features/real_graph",
        "src/scala/com/tw ter/t  l nes/pred ct on/features/recap",
        "src/scala/com/tw ter/t  l nes/pred ct on/features/request_context",
        "src/scala/com/tw ter/t  l nes/pred ct on/features/t  _features",
        "src/thr ft/com/tw ter/ml/ap :data-java",
        "src/thr ft/com/tw ter/ml/ap :transform-java",
    ],
)
