scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = [
        "bazel-compat ble",
    ],
    dependenc es = [
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
        "st ch/st ch-storehaus",
        "top c-soc al-proof/server/src/ma n/scala/com/tw ter/tsp/common",
        "top c-soc al-proof/server/src/ma n/scala/com/tw ter/tsp/stores",
        "top c-soc al-proof/server/src/ma n/thr ft:thr ft-scala",
        "top cl st ng/top cl st ng-core/src/ma n/scala/com/tw ter/top cl st ng",
    ],
)
