java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/log4j",
        "src/java/com/tw ter/search/common/relevance:ut ls",
        "src/java/com/tw ter/search/common/ut l/earlyb rd",
        "src/thr ft/com/tw ter/search:earlyb rd-java",
    ],
)
