java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/code/f ndbugs:jsr305",
        "src/java/com/tw ter/search/common/sc ma/base",
        "src/thr ft/com/tw ter/search/common:sc ma-java",
        "src/thr ft/com/tw ter/search/feature_update_serv ce/thr ft:thr ft-java",
    ],
)
