scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/g hub/nscala_t  ",
        "3rdparty/jvm/com/google/ nject:gu ce",
        "3rdparty/jvm/com/google/ nject/extens ons:gu ce-ass sted nject",
        "3rdparty/jvm/net/cod ng ll:scala-gu ce",
        "3rdparty/jvm/org/slf4j:slf4j-ap ",
        "follow-recom ndat ons-serv ce/common/src/ma n/scala/com/tw ter/follow_recom ndat ons/common/cl ents/strato",
        "follow-recom ndat ons-serv ce/common/src/ma n/scala/com/tw ter/follow_recom ndat ons/common/models",
        "follow-recom ndat ons-serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
        "st ch/st ch-soc algraph",
        "ut l/ut l-core:scala",
    ],
)
