scala_l brary(
    s ces = ["*.scala"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/apac /thr ft:l bthr ft",
        "scrooge/scrooge-core/src/ma n/scala",
        "servo/ut l",
        "src/thr ft/com/tw ter/search:earlyb rd-scala",
        "t  l neranker/common/src/ma n/scala/com/tw ter/t  l neranker/model",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/core",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)
