scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/fasterxml/jackson/core:jackson-annotat ons",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common",
    ],
    exports = [
        "3rdparty/jvm/com/fasterxml/jackson/core:jackson-annotat ons",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common",
    ],
)
