java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "src/java/com/tw ter/search/common/sc ma/earlyb rd",
        "src/thr ft/com/tw ter/search:earlyb rd-java",
    ],
)
