scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "ut l/ut l-core:scala",
        "ut l/ut l-slf4j-ap /src/ma n/scala/com/tw ter/ut l/logg ng",
    ],
)
