create_thr ft_l brar es(
    base_na  = "thr ft",
    s ces = ["*.thr ft"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependency_roots = ["src/thr ft/com/tw ter/ml/featurestore:ml-feature-store"],
    generate_languages = [
        "java",
        "scala",
    ],
)
