stratofed_forward_dark_traff c:
  com nt:
    Forward Federated Strato traff c to DarkTraff cProxy (DTP).
    Note, t  dec der  s not overr deable v a T etyp e tool ng,
    as    s only used by t  StratoFedServer fra workDec der  nstance.
    Note,   cannot use t  dec der as a T etyp eDec derGates.
  default_ava lab l y: 0

t etyp e_enable_commun y_t et_creates:
  com nt: W n enable,   allows t  creat on of commun y t ets
  default_ava lab l y: 10000

t etyp e_hydrate_scrub_engage nts:
  com nt: Redact T et engage nt related data (StatusCounts) from  nterst al Publ c  nterest ( P ) T ets.
  default_ava lab l y: 10000

t etyp e_c ck_spam_on_ret et:
  com nt: Enable Scarecrow spam c ck dur ng ret et creat on
  default_ava lab l y: 10000

t etyp e_c ck_spam_on_t et:
  com nt: Enable Scarecrow spam c ck dur ng t et creat on
  default_ava lab l y: 10000

t etyp e_conversat on_control_use_feature_sw ch_results:
  com nt:
    Controls w t r T etyp e uses feature sw ch results dur ng conversat on control para ter val dat on. T  dec der supports m grat on of feature sw c s from macaw-t ets to t etyp e.
  default_ava lab l y: 0

t etyp e_conversat on_control_t et_create_enabled:
  com nt:
    Controls w t r   w ll enforce conversat on control pol cy on t et create. http://go/dont-at- -backend-tdd
  default_ava lab l y: 0

t etyp e_enable_exclus ve_t et_control_val dat on:
  com nt:
    Controls w t r   w ll restr ct t  exclus veT etControlOpt ons para ter to only be usable by creators. http://go/superfollows
  default_ava lab l y: 0

t etyp e_delay_erase_user_t ets:
  com nt: sleep for a f xed number of seconds before delet ng a page of t ets dur ng user erasure. Used as a rate l m  ng  chan sm.
  default_ava lab l y: 5000

t etyp e_deny_non_t et_permal nks:
  com nt:
    R ght now   would create a quote-t et wh ch would conta n a non-work ng permal nk
    w reas w h latest QT +  d a changes  're block ng t  t et creat on.  f t et
    from permal nk  s not found,   would throw an except on  f t  dec der  s on else
    return a default pass-through response.
  default_ava lab l y: 0

t etyp e_enable_trusted_fr ends_control_val dat on:
  com nt: Controls w t r   w ll enforce trusted fr ends control pol cy on repl es
  default_ava lab l y: 0

t etyp e_enforce_rate_l m ed_cl ents:
  com nt:
    Controls w t r   w ll rate-l m  low-pr or y cl ents based on per- nstance requests per sec.
      enable cl ents for rate-l m  ng by sett ng t  rate_l m  to true  n cl ents.yml
  default_ava lab l y: 10000

t etyp e_fa l_closed_ n_vf:
  com nt: Propagate fa lure from backends such as Strato w n runn ng V s b l y F lter ng
  default_ava lab l y: 0

t etyp e_fork_dark_traff c:
  com nt: Forks traff c to Darkhub
  default_ava lab l y: 0

t etyp e_hydrate_conversat on_muted:
  com nt: Hydrates t  conversat onMuted f eld  f requested. T  calls t  l neserv ce.
  default_ava lab l y: 10000

t etyp e_hydrate_counts:
  com nt: Hydrate status counts,  f asked for.  T  calls TFlock.
  default_ava lab l y: 10000

t etyp e_hydrate_prev ous_counts:
  com nt: Hydrate prev ous engage nts on a t et  n an ed  cha n
  default_ava lab l y: 0

t etyp e_hydrate_dev ce_s ces:
  com nt: Hydrate dev ce s ces.  T  reads from DBs.
  default_ava lab l y: 10000

t etyp e_hydrate_esc rb rd_annotat ons:
  com nt: Hydrate t  esc rb rdEnt yAnnotat ons add  onal f eld on t et create.  T  calls t  Esc rb rd Annotat on Serv ce.
  default_ava lab l y: 10000

t etyp e_hydrate_gn p_prof le_geo_enr ch nt:
  com nt: Hydrates each t et w h t  prof le geo enr ch nt.
  default_ava lab l y: 10000

t etyp e_hydrate_has_ d a:
  com nt: Hydrate t  has d a f eld based on w t r t  t et has a  d a ent y, a  d a card, or a URL that matc s partner  d a regexes
  default_ava lab l y: 10000

t etyp e_hydrate_ d a:
  com nt: Hydrate  d a ent  es. T  calls  d a nfo Serv ce.
  default_ava lab l y: 10000

t etyp e_hydrate_ d a_refs:
  com nt: Hydrate  d aRefs. Calls T etyp e for pasted  d a.
  default_ava lab l y: 0

t etyp e_hydrate_ d a_tags:
  com nt: Hydrate  d a tags. T  calls G zmoduck for user v ew.
  default_ava lab l y: 10000

t etyp e_hydrate_pasted_ d a:
  com nt: Cop es  d a ent  es and  d a cards from t ets referenced by a  d a permal nk url ent y.
  default_ava lab l y: 10000

t etyp e_hydrate_perspect ves:
  com nt: Hydrate perspect val attr butes,  f asked for.  T  calls TLS, wh ch may call TFlock  f  ems are not  n cac .
  default_ava lab l y: 10000

t etyp e_hydrate_perspect ves_ed s_for_t  l nes:
  com nt:
    Hydrated perspect val attr butes across vers ons of t et ed ,
    for t  l nes safety levels  f asked for.
    T  results  n more TLS calls (one for each vers on of t et).
  default_ava lab l y: 0

t etyp e_hydrate_perspect ves_ed s_for_t et_deta ls:
  com nt:
    Hydrated perspect val attr butes across vers ons of t et ed ,
    for t et deta l safety levels  f asked for.
    T  results  n more TLS calls (one for each vers on of t et).
  default_ava lab l y: 0

t etyp e_hydrate_perspect ves_ed s_for_ot r_levels:
  com nt:
    Hydrated perspect val attr butes across vers ons of t et ed ,
    for safety levels not  nt oned  n ot r dec ders,  f asked for.
    T  results  n more TLS calls (one for each vers on of t et).
  default_ava lab l y: 0

t etyp e_hydrate_places:
  com nt: Hydrate place data,  f asked for. T  calls geoduck.
  default_ava lab l y: 10000

t etyp e_j m ny_dark_requests:
  com nt: Enables dark requests to t  J m ny backend for t  spec f ed % of traff c
  default_ava lab l y: 0

t etyp e_log_cac _except ons:
  com nt: Enables logg ng of cac  except ons to loglens.
  default_ava lab l y: 0

t etyp e_log_reads:
  com nt: Enables logg ng of reads.
  default_ava lab l y: 50

t etyp e_log_t et_cac _wr es:
  com nt: Scr be a record for each cac  wr e for t ets that pass t  dec der.
  default_ava lab l y: 0

t etyp e_log_wr es:
  com nt: Enables logg ng of status wr es.
  default_ava lab l y: 10000

t etyp e_log_ ng_t et_cac _wr es:
  com nt:
    Scr be a record of cac  wr es for recently-created t ets that
    pass t  dec der.
  default_ava lab l y: 0

t etyp e_log_vf_dark_read_m smatc s:
  com nt: Log m smatc s from t  t etyp e_dark_read_safety_labels_from_strato code path.
  default_ava lab l y: 0

t etyp e_max_request_w dth_enabled:
  com nt:
    Controls w t r t  max request w dth l m   s enabled or not.
    0  ans t  l m   s d sabled, 10000  ans    s turned on and
    request w dths > maxS ze w ll be rejected.
  default_ava lab l y: 0

t etyp e_ d a_refs_hydrator_ nclude_pasted_ d a:
  com nt:
    For debugg ng  d aRefsHydrator - determ ne  f extra calls to pasted  d a are caus ng t  GC  ssues.
  default_ava lab l y: 0

t etyp e_prefer_forwarded_serv ce_ dent f er_for_cl ent_ d:
  com nt: Effect ve cl ent  D log c prefers forwarded serv ce  dent f er to serv ce  dent f er  f ava lable.
  default_ava lab l y: 0

t etyp e_rate_l m _by_l m er_serv ce:
  com nt:
    Controls w t r   w ll consult l m er serv ce to see w t r a
    user  s allo d to create more t ets.
  default_ava lab l y: 10000

t etyp e_rate_l m _t et_creat on_fa lure:
  com nt:
    Controls w t r   rate l m  t et creat on based on fa led
    attempts to create t ets v a l m er serv ce. T   s separate
    from t  l m  of created t ets.    s  ntended to prevent
    unforeseen abuse by fa l ng t et creat on attempts  m d ately  f
    t  user has had too many recent t et creat on
    fa lures. D sabl ng t  dec der w ll reduce traff c to l m er
    serv ce, but w ll remove t  per-user abuse protect on.
  default_ava lab l y: 10000

t etyp e_repl cate_reads_to_atla:
  com nt: Send reads to deferredrpc for repl cat on to atla.   can use t  to warm cac s  n atla.
  default_ava lab l y: 0

t etyp e_repl cate_reads_to_pdxa:
  com nt: Send reads to deferredrpc for repl cat on to pdxa.   can use t  to warm cac s  n pdxa.
  default_ava lab l y: 0

t etyp e_d sable_ nv e_v a_ nt on:
  com nt:
    D sables  nv e v a  nt on f eld  n t  conversat on control struct of
    root t ets + reply t ets.
  default_ava lab l y: 0

t etyp e_s d_read_traff c_voluntar ly:
  com nt:
    Preferred way to reject read requests dur ng an  nc dent from a subset of cl ents that have
    volunteered to s d load.  T se cl ents have load_s d_envs set  n cl ents.yml, often for
    stag ng env ron nts.  Although t  dec der  s ava lable and cl ents have volunteered, should
    st ll only be used  n an e rgency.
  default_ava lab l y: 0

t etyp e_val date_card_ref_attach nt_andro d:
  com nt:
    W n enabled t et creates from Andro d cons der CardReference for t  TooManyAttach ntTypes error w n creat ng t ets w h more than one attach nt type.
  default_ava lab l y: 0

t etyp e_val date_card_ref_attach nt_non_andro d:
  com nt:
    W n enabled t et creates from non-Andro d cons der CardReference for t  TooManyAttach ntTypes error w n creat ng t ets w h more than one attach nt type
  default_ava lab l y: 0

# Add  onal F elds

t etyp e_short_c rcu _l kely_part al_t et_reads_ms:
  com nt:
    Spec f es a number of m ll seconds before wh ch,   short c rcu  l kely
    part al reads from MH and return NotFound t et response state.
    After exper  nt ng dec ded to go w h 1500 ms.
  default_ava lab l y: 0

t etyp e_populate_quoted_t et_results_as_contextual_t et_ref:
  com nt:
    CreateT et and CreateReT et column to return t  'quoted_t et_results' Prefetc d em as
    ContextualT etRef type  nstead of just t et d.
    T  w ll be used dur ng t  quotedT et.T et column m grat on (see http://go/qt-col-m grat on)
    Post-m grat on, t  w ll be removed.
  default_ava lab l y: 0
t etyp e_enable_un nt ons_t  l ne_warmup:
  com nt:
    W n enabled, read-path calls execute an async call to t  getUn nt onedUsersFromConverst on
    strato column to warm t  un nt oned NH/haplol e cac .
    http://go/un nt on- -onepager
  default_ava lab l y: 0

t etyp e_t et_v s b l y_l brary_enable_par y_test:
  com nt:  asure TVL par y aga nst VF federated serv ce, for a fract on of traff c
  default_ava lab l y: 0

t etyp e_enable_vf_feature_hydrat on_ n_quoted_t et_v s b l y_l brary_sh m:
  com nt: w n enabled, all features are hydrated  n QuotedT etV s b l yL brary sh m
  default_ava lab l y: 0

t etyp e_enable_remove_un nt oned_ mpl c _ nt ons:
  com nt:
    W n enabled,  mpl c   nt ons are f ltered based on users that have un nt oned t mselves
    from t  t et's conversat on.  http://go/un nt on- -onepager
  default_ava lab l y: 0

t etyp e_enable_stale_t et_val dat on:
  com nt: Controls w t r   w ll enforce stale t et pol cy on repl es and QT
  default_ava lab l y: 0

t etyp e_d sable_promoted_t et_ed :
  com nt:
    Controls w t r   w ll d sable ed s on promoted t ets
  default_ava lab l y: 0

t etyp e_should_mater al ze_conta ners:
  com nt:
    W n enabled, Creat ves Conta ner Serv ce w ll be called to mater al ze conta ner-backed t ets.
    Ot rw se, TP w ll not call CCS and return a StatusState of NotFound.
  default_ava lab l y: 0

t etyp e_c ck_tw ter_blue_subscr pt on_for_ed :
  com nt:
    Controls w t r   c ck  f t  User  s subscr bed to Tw ter Blue w n ed  ng a T et.
  default_ava lab l y: 0

t etyp e_hydrate_bookmarks_count:
  com nt:
    Controls w t r   hydrate bookmarks count for a T et
  default_ava lab l y: 0

t etyp e_hydrate_bookmarks_perspect ve:
  com nt:
    Controls w t r   request t  Bookmarked perspect ve from TLS
  default_ava lab l y: 0

t etyp e_set_ed _t  _w ndow_to_s xty_m nutes:
  com nt:
    Set t   w ndow  n wh ch T ets are ed able to 60 m nutes
  default_ava lab l y: 0

t etyp e_enable_federated_column_dark_traff c:
  com nt:
    Enable dark traff c for federated column.
  default_ava lab l y: 0
