http_or_https:
  - 'v ne\.co/v/[a-zA-Z0-9]+'
  - 'amp\.tw mg\.com/'
  - '(www\.)?da lymot on.com/v deo/[a-zA-Z0-9_\-/]+'
  - '(www\.)?da .ly/[a-zA-Z0-9_\-/]+'
  - '(www\.)? tu\.be/[a-zA-Z0-9_\-\?\&\=/]+'
  - '(www\.)? tube\.com/watch[a-zA-Z0-9_\-\?\&\=/]+'
  - '(www\.)?ustream\.tv/recorded/\d+'
  - '(www\.)?vevo\.com/watch/[\w-]+/[\w-]+/[a-zA-Z0-9_]+'
  - '(www\.)?fl ckr\.com/photos/[\w\@\-]+/\d+/?'
  - '(www\.)?fl c\.kr/p/[A-Z0-9a-z\-]+'
  - '([\w\-]+\.)dev antart\.com/(art|dev at on|v ew)/[\w\@-]+'
  - '(www\.)?v  o\.com/\d+'
  - '(www\.)?photozou\.(com|jp)/photo/show/\d+/\d+'
  - '(www\.)?tw p c\.com/(?!(place|photos|events)/)([a-zA-Z0-9\?\=\-]+)'
  - '(www\.)?mtv\.com/v deos/([a-z0-9\-\_]+/)+[0-9]+/[a-z0-9\-\_]+\.jhtml(#[a-z0-9\=\&]+)?'
  - '([\w\-\_]+\.)?wash ngtonpost\.com/wp-dyn/content/v deo/\d{4}/\d{2}/\d{2}/V \d+\.html([a-zA-Z0-9_#\.\-\?\&\=/]+)?'
  - '([\w\-\_]+\.)?msnbc\.msn\.com/ d/\d{1,8}/vp/\d{1,8}([a-zA-Z0-9_#\.\-\?\&\=/]+)?'
  - '((www|ed  on|us)\.)?cnn\.com/v deo/[\?|#]/[a-zA-Z0-9_#\.\-\?\&\=/]+'
  - ' unes\.apple\.com(/[a-z][a-z])?/(mus c-)?v deo/'
  - '(www\.)?bl p\.tv/((f le/[\w-]+)|(([\w-]+/)?[\w-]+-\d+))/?'
  - 'onl ne\.wsj\.com/v deo/[A-Z0-9a-z\-]+/[A-Z0-9a-z\-]+\.html'
  - '(www\.)?hulu\.com/w(atch)?/[a-zA-Z0-9]+'
  - 'v deo\.([a-z]{4,11}\.)?nhl\.com/v deocenter/console\?(((cat d=-?\d+&)? d=\d+)|(hlg=\d{8},\d,\d{1,4}(&event=[A-Z0-9]{4,6})?)|(hlp=\d{5,10}(&event=[A-Z0-9]{4,6})?))'
  - '([a-zA-Z0-9\-]+\.)*grabyo\.com/((g/v/[a-zA-Z0-9]{11})|((stud o/)?stud ot  l ne\.jsp\?share d=[a-zA-Z0-9]{11}))[a-zA-Z0-9_?&=#:%/\.\-]*'

http_only:
  - 'on\.nba\.com/[a-zA-Z0-9]+'
  - 'on\.nfl\.com/[a-zA-Z0-9]+'
  - 'snpy\.tv/[a-zA-Z0-9]+'
