scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f natra/ nject/ nject-core/src/ma n/scala",
        "representat on-manager/server/src/ma n/scala/com/tw ter/representat on_manager/columns",
        "representat on-manager/server/src/ma n/scala/com/tw ter/representat on_manager/modules",
        "representat on-manager/server/src/ma n/scala/com/tw ter/representat on_manager/store",
        "representat on-manager/server/src/ma n/thr ft:thr ft-scala",
        "strato/src/ma n/scala/com/tw ter/strato/fed",
        "strato/src/ma n/scala/com/tw ter/strato/fed/server",
    ],
)
