scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/fasterxml/jackson/core:jackson-annotat ons",
        "3rdparty/jvm/javax/ nject:javax. nject",
        "3rdparty/jvm/javax/ma l",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/common/alert/pred cate",
        "strato/src/ma n/scala/com/tw ter/strato/catalog",
        "ut l/ut l-core:scala",
    ],
    exports = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/common/alert/pred cate",
        "strato/src/ma n/scala/com/tw ter/strato/catalog",
        "ut l/ut l-core:scala",
    ],
)
