scala_l brary(
    s ces = [
        "*.scala",
    ],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    #   runt    s us ng Java 11, but for compat b l y w h ot r  nternal l brar es that
    # are st ll on Java 8,  'll make   target platform to be Java 8 as  ll unt l everyone can
    # m grate.
    platform = "java8",
    tags = ["bazel-compat ble"],
)
