scala_l brary(
    s ces = ["*.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/graphjet",
        "servo/request/src/ma n/scala",
        "src/scala/com/tw ter/recos/user_t et_graph/store",
        "src/scala/com/tw ter/recos/user_t et_graph/ut l",
        "src/scala/com/tw ter/recos/ut l:recos-ut l",
        "src/thr ft/com/tw ter/recos/user_t et_graph:user_t et_graph-scala",
    ],
)
