scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "src/java/com/tw ter/common/text/language:language- dent f er",
        "src/java/com/tw ter/common/text/language:locale-ut l",
        "src/java/com/tw ter/common/text/p pel ne",
        "src/java/com/tw ter/common/text/token",
        "src/java/com/tw ter/common_ nternal/text",
        "src/java/com/tw ter/common_ nternal/text/vers on",
        "t etyp e/src/res ces/com/tw ter/t etyp e/match ng",
        "ut l/ut l-core/src/ma n/scala/com/tw ter/concurrent",
        "ut l/ut l-core/src/ma n/scala/com/tw ter/ o",
    ],
)
