scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator/featurestorev1",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common/ dent f er",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/serv ce",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator/featurestorev1",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common/ dent f er",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/serv ce",
    ],
)
