target(
    na  = "adapter",
    dependenc es = ["t  l neranker/common/src/ma n/scala/com/tw ter/t  l neranker/adapter"],
)

target(
    na  = "model",
    dependenc es = ["t  l neranker/common/src/ma n/scala/com/tw ter/t  l neranker/model"],
)

target(
    tags = ["bazel-compat ble"],
    dependenc es = [
        ":adapter",
        ":model",
    ],
)
