scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "eventdetect on/common/src/ma n/java/com/tw ter/eventdetect on/common/louva n",
        "eventdetect on/common/src/ma n/java/com/tw ter/eventdetect on/common/model",
        "src/java/com/tw ter/sbf/graph",
        "src/scala/com/tw ter/s mclusters_v2/scald ng/common",
    ],
)
