scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/l haoy :s cecode",
        "ut l/ut l-core",
        "ut l/ut l-jackson/src/ma n/scala/com/tw ter/ut l/jackson",
    ],
    exports = [
        "3rdparty/jvm/com/l haoy :s cecode",
    ],
)
