res ces(
    s ces = [
        "*.tsv",
        "*.xml",
        "**/*",
        "conf g/*.yml",
    ],
)

# Created for Bazel compat b l y.
#  n Bazel, loose f les must be part of a target to be  ncluded  nto a bundle.
f les(
    na  = "frs_res ces",
    s ces = [
        "*.tsv",
        "*.xml",
        "*.yml",
        "**/*",
    ],
)
