scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "f nagle/f nagle-mux/src/ma n/scala",
        "f natra/ nject/ nject-core/src/ma n/scala",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common/ dent f er",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne:query",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "servo/ut l",
        "st ch/st ch-core",
        "ut l/ut l-core",
    ],
)
