scala_l brary(
    s ces = ["com/tw ter/t  l neranker/cl ent/*.scala"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle-core/src/ma n",
        "f nagle/f nagle-stats",
        "f nagle/f nagle-thr ft/src/ma n/java",
        "servo/cl ent/src/ma n/scala/com/tw ter/servo/cl ent",
        "src/thr ft/com/tw ter/t  l neranker:thr ft-scala",
        "src/thr ft/com/tw ter/t  l neranker/server/model:thr ft-scala",
        "t  l neranker/common:model",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/ut l/stats",
        "ut l/ut l-stats/src/ma n/scala",
    ],
)
