scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "dec der/src/ma n/scala",
        "f nagle/f nagle- mcac d",
        " rm / rm -core/src/ma n/scala/com/tw ter/ rm /store/common",
        "relevance-platform/src/ma n/scala/com/tw ter/relevance_platform/common/ nject on",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
    ],
)
