/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class Al gnedTableU nt8 {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected Al gnedTableU nt8(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(Al gnedTableU nt8 obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_Al gnedTableU nt8(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setTab(SW GTYPE_p_fa ss__Al gnedTableT ghtAllocT_uns gned_char_32_t value) {
    sw gfa ssJN .Al gnedTableU nt8_tab_set(sw gCPtr, t , SW GTYPE_p_fa ss__Al gnedTableT ghtAllocT_uns gned_char_32_t.getCPtr(value));
  }

  publ c SW GTYPE_p_fa ss__Al gnedTableT ghtAllocT_uns gned_char_32_t getTab() {
    long cPtr = sw gfa ssJN .Al gnedTableU nt8_tab_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_fa ss__Al gnedTableT ghtAllocT_uns gned_char_32_t(cPtr, false);
  }

  publ c vo d setNu l(long value) {
    sw gfa ssJN .Al gnedTableU nt8_nu l_set(sw gCPtr, t , value);
  }

  publ c long getNu l() {
    return sw gfa ssJN .Al gnedTableU nt8_nu l_get(sw gCPtr, t );
  }

  publ c stat c long round_capac y(long n) {
    return sw gfa ssJN .Al gnedTableU nt8_round_capac y(n);
  }

  publ c Al gnedTableU nt8() {
    t (sw gfa ssJN .new_Al gnedTableU nt8__SW G_0(), true);
  }

  publ c Al gnedTableU nt8(long n) {
    t (sw gfa ssJN .new_Al gnedTableU nt8__SW G_1(n), true);
  }

  publ c long  ems ze() {
    return sw gfa ssJN .Al gnedTableU nt8_ ems ze(sw gCPtr, t );
  }

  publ c vo d res ze(long n) {
    sw gfa ssJN .Al gnedTableU nt8_res ze(sw gCPtr, t , n);
  }

  publ c vo d clear() {
    sw gfa ssJN .Al gnedTableU nt8_clear(sw gCPtr, t );
  }

  publ c long s ze() {
    return sw gfa ssJN .Al gnedTableU nt8_s ze(sw gCPtr, t );
  }

  publ c long nbytes() {
    return sw gfa ssJN .Al gnedTableU nt8_nbytes(sw gCPtr, t );
  }

  publ c SW GTYPE_p_uns gned_char get() {
    long cPtr = sw gfa ssJN .Al gnedTableU nt8_get__SW G_0(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_uns gned_char(cPtr, false);
  }

  publ c SW GTYPE_p_uns gned_char data() {
    long cPtr = sw gfa ssJN .Al gnedTableU nt8_data__SW G_0(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_uns gned_char(cPtr, false);
  }

}
