java_l brary(
    na  = "sw g-local",
    s ces = ["*.java"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = [
        "bazel-compat ble",
        "bazel-only",
    ],
    dependenc es = [
        "ann/src/ma n/java/com/tw ter/ann/fa ss:sw g-nat ve-ut ls",
        "ann/src/ma n/java/com/tw ter/ann/fa ss/sw g/res ces",
    ],
)

java_l brary(
    na  = "sw g-art factory",
    s ces = ["*.java"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/ann/fa ss/sw g:res ces",
        "ann/src/ma n/java/com/tw ter/ann/fa ss:sw g-nat ve-ut ls",
    ],
)
