/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class CharVector {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected CharVector(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(CharVector obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_CharVector(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c CharVector() {
    t (sw gfa ssJN .new_CharVector(), true);
  }

  publ c vo d push_back(char arg0) {
    sw gfa ssJN .CharVector_push_back(sw gCPtr, t , arg0);
  }

  publ c vo d clear() {
    sw gfa ssJN .CharVector_clear(sw gCPtr, t );
  }

  publ c Str ng data() {
    return sw gfa ssJN .CharVector_data(sw gCPtr, t );
  }

  publ c long s ze() {
    return sw gfa ssJN .CharVector_s ze(sw gCPtr, t );
  }

  publ c char at(long n) {
    return sw gfa ssJN .CharVector_at(sw gCPtr, t , n);
  }

  publ c vo d res ze(long n) {
    sw gfa ssJN .CharVector_res ze(sw gCPtr, t , n);
  }

  publ c vo d reserve(long n) {
    sw gfa ssJN .CharVector_reserve(sw gCPtr, t , n);
  }

  publ c vo d swap(CharVector ot r) {
    sw gfa ssJN .CharVector_swap(sw gCPtr, t , CharVector.getCPtr(ot r), ot r);
  }

}
