/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class D stanceComputer {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected D stanceComputer(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(D stanceComputer obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_D stanceComputer(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d set_query(SW GTYPE_p_float x) {
    sw gfa ssJN .D stanceComputer_set_query(sw gCPtr, t , SW GTYPE_p_float.getCPtr(x));
  }

  publ c float sym tr c_d s(long  , long j) {
    return sw gfa ssJN .D stanceComputer_sym tr c_d s(sw gCPtr, t ,  , j);
  }

}
