/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class float_m n ap_array_t {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected float_m n ap_array_t(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(float_m n ap_array_t obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_float_m n ap_array_t(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setNh(long value) {
    sw gfa ssJN .float_m n ap_array_t_nh_set(sw gCPtr, t , value);
  }

  publ c long getNh() {
    return sw gfa ssJN .float_m n ap_array_t_nh_get(sw gCPtr, t );
  }

  publ c vo d setK(long value) {
    sw gfa ssJN .float_m n ap_array_t_k_set(sw gCPtr, t , value);
  }

  publ c long getK() {
    return sw gfa ssJN .float_m n ap_array_t_k_get(sw gCPtr, t );
  }

  publ c vo d set ds(LongVector value) {
    sw gfa ssJN .float_m n ap_array_t_ ds_set(sw gCPtr, t , SW GTYPE_p_long_long.getCPtr(value.data()), value);
  }

  publ c LongVector get ds() {
    return new LongVector(sw gfa ssJN .float_m n ap_array_t_ ds_get(sw gCPtr, t ), false);
}

  publ c vo d setVal(SW GTYPE_p_float value) {
    sw gfa ssJN .float_m n ap_array_t_val_set(sw gCPtr, t , SW GTYPE_p_float.getCPtr(value));
  }

  publ c SW GTYPE_p_float getVal() {
    long cPtr = sw gfa ssJN .float_m n ap_array_t_val_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_float(cPtr, false);
  }

  publ c SW GTYPE_p_float get_val(long key) {
    long cPtr = sw gfa ssJN .float_m n ap_array_t_get_val(sw gCPtr, t , key);
    return (cPtr == 0) ? null : new SW GTYPE_p_float(cPtr, false);
  }

  publ c LongVector get_ ds(long key) {
    return new LongVector(sw gfa ssJN .float_m n ap_array_t_get_ ds(sw gCPtr, t , key), false);
}

  publ c vo d  ap fy() {
    sw gfa ssJN .float_m n ap_array_t_ ap fy(sw gCPtr, t );
  }

  publ c vo d addn(long nj, SW GTYPE_p_float v n, long j0, long  0, long n ) {
    sw gfa ssJN .float_m n ap_array_t_addn__SW G_0(sw gCPtr, t , nj, SW GTYPE_p_float.getCPtr(v n), j0,  0, n );
  }

  publ c vo d addn(long nj, SW GTYPE_p_float v n, long j0, long  0) {
    sw gfa ssJN .float_m n ap_array_t_addn__SW G_1(sw gCPtr, t , nj, SW GTYPE_p_float.getCPtr(v n), j0,  0);
  }

  publ c vo d addn(long nj, SW GTYPE_p_float v n, long j0) {
    sw gfa ssJN .float_m n ap_array_t_addn__SW G_2(sw gCPtr, t , nj, SW GTYPE_p_float.getCPtr(v n), j0);
  }

  publ c vo d addn(long nj, SW GTYPE_p_float v n) {
    sw gfa ssJN .float_m n ap_array_t_addn__SW G_3(sw gCPtr, t , nj, SW GTYPE_p_float.getCPtr(v n));
  }

  publ c vo d addn_w h_ ds(long nj, SW GTYPE_p_float v n, LongVector  d_ n, long  d_str de, long  0, long n ) {
    sw gfa ssJN .float_m n ap_array_t_addn_w h_ ds__SW G_0(sw gCPtr, t , nj, SW GTYPE_p_float.getCPtr(v n), SW GTYPE_p_long_long.getCPtr( d_ n.data()),  d_ n,  d_str de,  0, n );
  }

  publ c vo d addn_w h_ ds(long nj, SW GTYPE_p_float v n, LongVector  d_ n, long  d_str de, long  0) {
    sw gfa ssJN .float_m n ap_array_t_addn_w h_ ds__SW G_1(sw gCPtr, t , nj, SW GTYPE_p_float.getCPtr(v n), SW GTYPE_p_long_long.getCPtr( d_ n.data()),  d_ n,  d_str de,  0);
  }

  publ c vo d addn_w h_ ds(long nj, SW GTYPE_p_float v n, LongVector  d_ n, long  d_str de) {
    sw gfa ssJN .float_m n ap_array_t_addn_w h_ ds__SW G_2(sw gCPtr, t , nj, SW GTYPE_p_float.getCPtr(v n), SW GTYPE_p_long_long.getCPtr( d_ n.data()),  d_ n,  d_str de);
  }

  publ c vo d addn_w h_ ds(long nj, SW GTYPE_p_float v n, LongVector  d_ n) {
    sw gfa ssJN .float_m n ap_array_t_addn_w h_ ds__SW G_3(sw gCPtr, t , nj, SW GTYPE_p_float.getCPtr(v n), SW GTYPE_p_long_long.getCPtr( d_ n.data()),  d_ n);
  }

  publ c vo d addn_w h_ ds(long nj, SW GTYPE_p_float v n) {
    sw gfa ssJN .float_m n ap_array_t_addn_w h_ ds__SW G_4(sw gCPtr, t , nj, SW GTYPE_p_float.getCPtr(v n));
  }

  publ c vo d reorder() {
    sw gfa ssJN .float_m n ap_array_t_reorder(sw gCPtr, t );
  }

  publ c vo d per_l ne_extrema(SW GTYPE_p_float vals_out, LongVector  dx_out) {
    sw gfa ssJN .float_m n ap_array_t_per_l ne_extrema(sw gCPtr, t , SW GTYPE_p_float.getCPtr(vals_out), SW GTYPE_p_long_long.getCPtr( dx_out.data()),  dx_out);
  }

  publ c float_m n ap_array_t() {
    t (sw gfa ssJN .new_float_m n ap_array_t(), true);
  }

}
