/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class Hamm ngComputer20 {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected Hamm ngComputer20(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(Hamm ngComputer20 obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_Hamm ngComputer20(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setA0(long value) {
    sw gfa ssJN .Hamm ngComputer20_a0_set(sw gCPtr, t , value);
  }

  publ c long getA0() {
    return sw gfa ssJN .Hamm ngComputer20_a0_get(sw gCPtr, t );
  }

  publ c vo d setA1(long value) {
    sw gfa ssJN .Hamm ngComputer20_a1_set(sw gCPtr, t , value);
  }

  publ c long getA1() {
    return sw gfa ssJN .Hamm ngComputer20_a1_get(sw gCPtr, t );
  }

  publ c vo d setA2(SW GTYPE_p_u nt32_t value) {
    sw gfa ssJN .Hamm ngComputer20_a2_set(sw gCPtr, t , SW GTYPE_p_u nt32_t.getCPtr(value));
  }

  publ c SW GTYPE_p_u nt32_t getA2() {
    return new SW GTYPE_p_u nt32_t(sw gfa ssJN .Hamm ngComputer20_a2_get(sw gCPtr, t ), true);
  }

  publ c Hamm ngComputer20() {
    t (sw gfa ssJN .new_Hamm ngComputer20__SW G_0(), true);
  }

  publ c Hamm ngComputer20(SW GTYPE_p_uns gned_char a8,  nt code_s ze) {
    t (sw gfa ssJN .new_Hamm ngComputer20__SW G_1(SW GTYPE_p_uns gned_char.getCPtr(a8), code_s ze), true);
  }

  publ c vo d set(SW GTYPE_p_uns gned_char a8,  nt code_s ze) {
    sw gfa ssJN .Hamm ngComputer20_set(sw gCPtr, t , SW GTYPE_p_uns gned_char.getCPtr(a8), code_s ze);
  }

  publ c  nt hamm ng(SW GTYPE_p_uns gned_char b8) {
    return sw gfa ssJN .Hamm ngComputer20_hamm ng(sw gCPtr, t , SW GTYPE_p_uns gned_char.getCPtr(b8));
  }

}
