/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class Hamm ngComputerDefault {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected Hamm ngComputerDefault(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(Hamm ngComputerDefault obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_Hamm ngComputerDefault(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setA8(SW GTYPE_p_uns gned_char value) {
    sw gfa ssJN .Hamm ngComputerDefault_a8_set(sw gCPtr, t , SW GTYPE_p_uns gned_char.getCPtr(value));
  }

  publ c SW GTYPE_p_uns gned_char getA8() {
    long cPtr = sw gfa ssJN .Hamm ngComputerDefault_a8_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_uns gned_char(cPtr, false);
  }

  publ c vo d setQuot ent8( nt value) {
    sw gfa ssJN .Hamm ngComputerDefault_quot ent8_set(sw gCPtr, t , value);
  }

  publ c  nt getQuot ent8() {
    return sw gfa ssJN .Hamm ngComputerDefault_quot ent8_get(sw gCPtr, t );
  }

  publ c vo d setRema nder8( nt value) {
    sw gfa ssJN .Hamm ngComputerDefault_rema nder8_set(sw gCPtr, t , value);
  }

  publ c  nt getRema nder8() {
    return sw gfa ssJN .Hamm ngComputerDefault_rema nder8_get(sw gCPtr, t );
  }

  publ c Hamm ngComputerDefault() {
    t (sw gfa ssJN .new_Hamm ngComputerDefault__SW G_0(), true);
  }

  publ c Hamm ngComputerDefault(SW GTYPE_p_uns gned_char a8,  nt code_s ze) {
    t (sw gfa ssJN .new_Hamm ngComputerDefault__SW G_1(SW GTYPE_p_uns gned_char.getCPtr(a8), code_s ze), true);
  }

  publ c vo d set(SW GTYPE_p_uns gned_char a8,  nt code_s ze) {
    sw gfa ssJN .Hamm ngComputerDefault_set(sw gCPtr, t , SW GTYPE_p_uns gned_char.getCPtr(a8), code_s ze);
  }

  publ c  nt hamm ng(SW GTYPE_p_uns gned_char b8) {
    return sw gfa ssJN .Hamm ngComputerDefault_hamm ng(sw gCPtr, t , SW GTYPE_p_uns gned_char.getCPtr(b8));
  }

}
