/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class Hamm ngComputerM4 {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected Hamm ngComputerM4(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(Hamm ngComputerM4 obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_Hamm ngComputerM4(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setA(SW GTYPE_p_u nt32_t value) {
    sw gfa ssJN .Hamm ngComputerM4_a_set(sw gCPtr, t , SW GTYPE_p_u nt32_t.getCPtr(value));
  }

  publ c SW GTYPE_p_u nt32_t getA() {
    long cPtr = sw gfa ssJN .Hamm ngComputerM4_a_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_u nt32_t(cPtr, false);
  }

  publ c vo d setN( nt value) {
    sw gfa ssJN .Hamm ngComputerM4_n_set(sw gCPtr, t , value);
  }

  publ c  nt getN() {
    return sw gfa ssJN .Hamm ngComputerM4_n_get(sw gCPtr, t );
  }

  publ c Hamm ngComputerM4() {
    t (sw gfa ssJN .new_Hamm ngComputerM4__SW G_0(), true);
  }

  publ c Hamm ngComputerM4(SW GTYPE_p_uns gned_char a4,  nt code_s ze) {
    t (sw gfa ssJN .new_Hamm ngComputerM4__SW G_1(SW GTYPE_p_uns gned_char.getCPtr(a4), code_s ze), true);
  }

  publ c vo d set(SW GTYPE_p_uns gned_char a4,  nt code_s ze) {
    sw gfa ssJN .Hamm ngComputerM4_set(sw gCPtr, t , SW GTYPE_p_uns gned_char.getCPtr(a4), code_s ze);
  }

  publ c  nt hamm ng(SW GTYPE_p_uns gned_char b8) {
    return sw gfa ssJN .Hamm ngComputerM4_hamm ng(sw gCPtr, t , SW GTYPE_p_uns gned_char.getCPtr(b8));
  }

}
