/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  DSelectorBatch extends  DSelector {
  pr vate trans ent long sw gCPtr;

  protected  DSelectorBatch(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . DSelectorBatch_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( DSelectorBatch obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ DSelectorBatch(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d setNb s( nt value) {
    sw gfa ssJN . DSelectorBatch_nb s_set(sw gCPtr, t , value);
  }

  publ c  nt getNb s() {
    return sw gfa ssJN . DSelectorBatch_nb s_get(sw gCPtr, t );
  }

  publ c vo d setMask(long value) {
    sw gfa ssJN . DSelectorBatch_mask_set(sw gCPtr, t , value);
  }

  publ c long getMask() {
    return sw gfa ssJN . DSelectorBatch_mask_get(sw gCPtr, t );
}

  publ c  DSelectorBatch(long n, LongVector  nd ces) {
    t (sw gfa ssJN .new_ DSelectorBatch(n, SW GTYPE_p_long_long.getCPtr( nd ces.data()),  nd ces), true);
  }

  publ c boolean  s_ mber(long  d) {
    return sw gfa ssJN . DSelectorBatch_ s_ mber(sw gCPtr, t ,  d);
  }

}
