/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndexHNSWPQ extends  ndexHNSW {
  pr vate trans ent long sw gCPtr;

  protected  ndexHNSWPQ(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . ndexHNSWPQ_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndexHNSWPQ obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndexHNSWPQ(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c  ndexHNSWPQ() {
    t (sw gfa ssJN .new_ ndexHNSWPQ__SW G_0(), true);
  }

  publ c  ndexHNSWPQ( nt d,  nt pq_m,  nt M) {
    t (sw gfa ssJN .new_ ndexHNSWPQ__SW G_1(d, pq_m, M), true);
  }

  publ c vo d tra n(long n, SW GTYPE_p_float x) {
    sw gfa ssJN . ndexHNSWPQ_tra n(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x));
  }

}
