/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndexFlatCodes extends  ndex {
  pr vate trans ent long sw gCPtr;

  protected  ndexFlatCodes(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . ndexFlatCodes_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndexFlatCodes obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndexFlatCodes(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d setCode_s ze(long value) {
    sw gfa ssJN . ndexFlatCodes_code_s ze_set(sw gCPtr, t , value);
  }

  publ c long getCode_s ze() {
    return sw gfa ssJN . ndexFlatCodes_code_s ze_get(sw gCPtr, t );
  }

  publ c vo d setCodes(ByteVector value) {
    sw gfa ssJN . ndexFlatCodes_codes_set(sw gCPtr, t , ByteVector.getCPtr(value), value);
  }

  publ c ByteVector getCodes() {
    long cPtr = sw gfa ssJN . ndexFlatCodes_codes_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new ByteVector(cPtr, false);
  }

  publ c vo d add(long n, SW GTYPE_p_float x) {
    sw gfa ssJN . ndexFlatCodes_add(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x));
  }

  publ c vo d reset() {
    sw gfa ssJN . ndexFlatCodes_reset(sw gCPtr, t );
  }

  publ c vo d reconstruct_n(long  0, long n , SW GTYPE_p_float recons) {
    sw gfa ssJN . ndexFlatCodes_reconstruct_n(sw gCPtr, t ,  0, n , SW GTYPE_p_float.getCPtr(recons));
  }

  publ c vo d reconstruct(long key, SW GTYPE_p_float recons) {
    sw gfa ssJN . ndexFlatCodes_reconstruct(sw gCPtr, t , key, SW GTYPE_p_float.getCPtr(recons));
  }

  publ c long sa_code_s ze() {
    return sw gfa ssJN . ndexFlatCodes_sa_code_s ze(sw gCPtr, t );
  }

  publ c long remove_ ds( DSelector sel) {
    return sw gfa ssJN . ndexFlatCodes_remove_ ds(sw gCPtr, t ,  DSelector.getCPtr(sel), sel);
  }

}
