/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndexB nary VF extends  ndexB nary {
  pr vate trans ent long sw gCPtr;

  protected  ndexB nary VF(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . ndexB nary VF_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndexB nary VF obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndexB nary VF(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d set nvl sts( nvertedL sts value) {
    sw gfa ssJN . ndexB nary VF_ nvl sts_set(sw gCPtr, t ,  nvertedL sts.getCPtr(value), value);
  }

  publ c  nvertedL sts get nvl sts() {
    long cPtr = sw gfa ssJN . ndexB nary VF_ nvl sts_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new  nvertedL sts(cPtr, false);
  }

  publ c vo d setOwn_ nvl sts(boolean value) {
    sw gfa ssJN . ndexB nary VF_own_ nvl sts_set(sw gCPtr, t , value);
  }

  publ c boolean getOwn_ nvl sts() {
    return sw gfa ssJN . ndexB nary VF_own_ nvl sts_get(sw gCPtr, t );
  }

  publ c vo d setNprobe(long value) {
    sw gfa ssJN . ndexB nary VF_nprobe_set(sw gCPtr, t , value);
  }

  publ c long getNprobe() {
    return sw gfa ssJN . ndexB nary VF_nprobe_get(sw gCPtr, t );
  }

  publ c vo d setMax_codes(long value) {
    sw gfa ssJN . ndexB nary VF_max_codes_set(sw gCPtr, t , value);
  }

  publ c long getMax_codes() {
    return sw gfa ssJN . ndexB nary VF_max_codes_get(sw gCPtr, t );
  }

  publ c vo d setUse_ ap(boolean value) {
    sw gfa ssJN . ndexB nary VF_use_ ap_set(sw gCPtr, t , value);
  }

  publ c boolean getUse_ ap() {
    return sw gfa ssJN . ndexB nary VF_use_ ap_get(sw gCPtr, t );
  }

  publ c vo d setD rect_map(SW GTYPE_p_D rectMap value) {
    sw gfa ssJN . ndexB nary VF_d rect_map_set(sw gCPtr, t , SW GTYPE_p_D rectMap.getCPtr(value));
  }

  publ c SW GTYPE_p_D rectMap getD rect_map() {
    return new SW GTYPE_p_D rectMap(sw gfa ssJN . ndexB nary VF_d rect_map_get(sw gCPtr, t ), true);
  }

  publ c vo d setQuant zer( ndexB nary value) {
    sw gfa ssJN . ndexB nary VF_quant zer_set(sw gCPtr, t ,  ndexB nary.getCPtr(value), value);
  }

  publ c  ndexB nary getQuant zer() {
    long cPtr = sw gfa ssJN . ndexB nary VF_quant zer_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new  ndexB nary(cPtr, false);
  }

  publ c vo d setNl st(long value) {
    sw gfa ssJN . ndexB nary VF_nl st_set(sw gCPtr, t , value);
  }

  publ c long getNl st() {
    return sw gfa ssJN . ndexB nary VF_nl st_get(sw gCPtr, t );
  }

  publ c vo d setOwn_f elds(boolean value) {
    sw gfa ssJN . ndexB nary VF_own_f elds_set(sw gCPtr, t , value);
  }

  publ c boolean getOwn_f elds() {
    return sw gfa ssJN . ndexB nary VF_own_f elds_get(sw gCPtr, t );
  }

  publ c vo d setCp(Cluster ngPara ters value) {
    sw gfa ssJN . ndexB nary VF_cp_set(sw gCPtr, t , Cluster ngPara ters.getCPtr(value), value);
  }

  publ c Cluster ngPara ters getCp() {
    long cPtr = sw gfa ssJN . ndexB nary VF_cp_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new Cluster ngPara ters(cPtr, false);
  }

  publ c vo d setCluster ng_ ndex( ndex value) {
    sw gfa ssJN . ndexB nary VF_cluster ng_ ndex_set(sw gCPtr, t ,  ndex.getCPtr(value), value);
  }

  publ c  ndex getCluster ng_ ndex() {
    long cPtr = sw gfa ssJN . ndexB nary VF_cluster ng_ ndex_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new  ndex(cPtr, false);
  }

  publ c  ndexB nary VF( ndexB nary quant zer, long d, long nl st) {
    t (sw gfa ssJN .new_ ndexB nary VF__SW G_0( ndexB nary.getCPtr(quant zer), quant zer, d, nl st), true);
  }

  publ c  ndexB nary VF() {
    t (sw gfa ssJN .new_ ndexB nary VF__SW G_1(), true);
  }

  publ c vo d reset() {
    sw gfa ssJN . ndexB nary VF_reset(sw gCPtr, t );
  }

  publ c vo d tra n(long n, SW GTYPE_p_uns gned_char x) {
    sw gfa ssJN . ndexB nary VF_tra n(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x));
  }

  publ c vo d add(long n, SW GTYPE_p_uns gned_char x) {
    sw gfa ssJN . ndexB nary VF_add(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x));
  }

  publ c vo d add_w h_ ds(long n, SW GTYPE_p_uns gned_char x, LongVector x ds) {
    sw gfa ssJN . ndexB nary VF_add_w h_ ds(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x), SW GTYPE_p_long_long.getCPtr(x ds.data()), x ds);
  }

  publ c vo d add_core(long n, SW GTYPE_p_uns gned_char x, LongVector x ds, LongVector precomputed_ dx) {
    sw gfa ssJN . ndexB nary VF_add_core(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x), SW GTYPE_p_long_long.getCPtr(x ds.data()), x ds, SW GTYPE_p_long_long.getCPtr(precomputed_ dx.data()), precomputed_ dx);
  }

  publ c vo d search_preass gned(long n, SW GTYPE_p_uns gned_char x, long k, LongVector ass gn, SW GTYPE_p_ nt centro d_d s, SW GTYPE_p_ nt d stances, LongVector labels, boolean store_pa rs,  VFSearchPara ters params) {
    sw gfa ssJN . ndexB nary VF_search_preass gned__SW G_0(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x), k, SW GTYPE_p_long_long.getCPtr(ass gn.data()), ass gn, SW GTYPE_p_ nt.getCPtr(centro d_d s), SW GTYPE_p_ nt.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels, store_pa rs,  VFSearchPara ters.getCPtr(params), params);
  }

  publ c vo d search_preass gned(long n, SW GTYPE_p_uns gned_char x, long k, LongVector ass gn, SW GTYPE_p_ nt centro d_d s, SW GTYPE_p_ nt d stances, LongVector labels, boolean store_pa rs) {
    sw gfa ssJN . ndexB nary VF_search_preass gned__SW G_1(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x), k, SW GTYPE_p_long_long.getCPtr(ass gn.data()), ass gn, SW GTYPE_p_ nt.getCPtr(centro d_d s), SW GTYPE_p_ nt.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels, store_pa rs);
  }

  publ c SW GTYPE_p_fa ss__B nary nvertedL stScanner get_ nvertedL stScanner(boolean store_pa rs) {
    long cPtr = sw gfa ssJN . ndexB nary VF_get_ nvertedL stScanner__SW G_0(sw gCPtr, t , store_pa rs);
    return (cPtr == 0) ? null : new SW GTYPE_p_fa ss__B nary nvertedL stScanner(cPtr, false);
  }

  publ c SW GTYPE_p_fa ss__B nary nvertedL stScanner get_ nvertedL stScanner() {
    long cPtr = sw gfa ssJN . ndexB nary VF_get_ nvertedL stScanner__SW G_1(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_fa ss__B nary nvertedL stScanner(cPtr, false);
  }

  publ c vo d search(long n, SW GTYPE_p_uns gned_char x, long k, SW GTYPE_p_ nt d stances, LongVector labels) {
    sw gfa ssJN . ndexB nary VF_search(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x), k, SW GTYPE_p_ nt.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels);
  }

  publ c vo d range_search(long n, SW GTYPE_p_uns gned_char x,  nt rad us, RangeSearchResult result) {
    sw gfa ssJN . ndexB nary VF_range_search(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x), rad us, RangeSearchResult.getCPtr(result), result);
  }

  publ c vo d range_search_preass gned(long n, SW GTYPE_p_uns gned_char x,  nt rad us, LongVector ass gn, SW GTYPE_p_ nt centro d_d s, RangeSearchResult result) {
    sw gfa ssJN . ndexB nary VF_range_search_preass gned(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x), rad us, SW GTYPE_p_long_long.getCPtr(ass gn.data()), ass gn, SW GTYPE_p_ nt.getCPtr(centro d_d s), RangeSearchResult.getCPtr(result), result);
  }

  publ c vo d reconstruct(long key, SW GTYPE_p_uns gned_char recons) {
    sw gfa ssJN . ndexB nary VF_reconstruct(sw gCPtr, t , key, SW GTYPE_p_uns gned_char.getCPtr(recons));
  }

  publ c vo d reconstruct_n(long  0, long n , SW GTYPE_p_uns gned_char recons) {
    sw gfa ssJN . ndexB nary VF_reconstruct_n(sw gCPtr, t ,  0, n , SW GTYPE_p_uns gned_char.getCPtr(recons));
  }

  publ c vo d search_and_reconstruct(long n, SW GTYPE_p_uns gned_char x, long k, SW GTYPE_p_ nt d stances, LongVector labels, SW GTYPE_p_uns gned_char recons) {
    sw gfa ssJN . ndexB nary VF_search_and_reconstruct(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x), k, SW GTYPE_p_ nt.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels, SW GTYPE_p_uns gned_char.getCPtr(recons));
  }

  publ c vo d reconstruct_from_offset(long l st_no, long offset, SW GTYPE_p_uns gned_char recons) {
    sw gfa ssJN . ndexB nary VF_reconstruct_from_offset(sw gCPtr, t , l st_no, offset, SW GTYPE_p_uns gned_char.getCPtr(recons));
  }

  publ c long remove_ ds( DSelector sel) {
    return sw gfa ssJN . ndexB nary VF_remove_ ds(sw gCPtr, t ,  DSelector.getCPtr(sel), sel);
  }

  publ c vo d  rge_from( ndexB nary VF ot r, long add_ d) {
    sw gfa ssJN . ndexB nary VF_ rge_from(sw gCPtr, t ,  ndexB nary VF.getCPtr(ot r), ot r, add_ d);
  }

  publ c long get_l st_s ze(long l st_no) {
    return sw gfa ssJN . ndexB nary VF_get_l st_s ze(sw gCPtr, t , l st_no);
  }

  publ c vo d make_d rect_map(boolean new_ma nta n_d rect_map) {
    sw gfa ssJN . ndexB nary VF_make_d rect_map__SW G_0(sw gCPtr, t , new_ma nta n_d rect_map);
  }

  publ c vo d make_d rect_map() {
    sw gfa ssJN . ndexB nary VF_make_d rect_map__SW G_1(sw gCPtr, t );
  }

  publ c vo d set_d rect_map_type(SW GTYPE_p_D rectMap__Type type) {
    sw gfa ssJN . ndexB nary VF_set_d rect_map_type(sw gCPtr, t , SW GTYPE_p_D rectMap__Type.getCPtr(type));
  }

  publ c vo d replace_ nvl sts( nvertedL sts  l, boolean own) {
    sw gfa ssJN . ndexB nary VF_replace_ nvl sts__SW G_0(sw gCPtr, t ,  nvertedL sts.getCPtr( l),  l, own);
  }

  publ c vo d replace_ nvl sts( nvertedL sts  l) {
    sw gfa ssJN . ndexB nary VF_replace_ nvl sts__SW G_1(sw gCPtr, t ,  nvertedL sts.getCPtr( l),  l);
  }

}
