/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndexB naryFromFloat extends  ndexB nary {
  pr vate trans ent long sw gCPtr;

  protected  ndexB naryFromFloat(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . ndexB naryFromFloat_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndexB naryFromFloat obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndexB naryFromFloat(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d set ndex( ndex value) {
    sw gfa ssJN . ndexB naryFromFloat_ ndex_set(sw gCPtr, t ,  ndex.getCPtr(value), value);
  }

  publ c  ndex get ndex() {
    long cPtr = sw gfa ssJN . ndexB naryFromFloat_ ndex_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new  ndex(cPtr, false);
  }

  publ c vo d setOwn_f elds(boolean value) {
    sw gfa ssJN . ndexB naryFromFloat_own_f elds_set(sw gCPtr, t , value);
  }

  publ c boolean getOwn_f elds() {
    return sw gfa ssJN . ndexB naryFromFloat_own_f elds_get(sw gCPtr, t );
  }

  publ c  ndexB naryFromFloat() {
    t (sw gfa ssJN .new_ ndexB naryFromFloat__SW G_0(), true);
  }

  publ c  ndexB naryFromFloat( ndex  ndex) {
    t (sw gfa ssJN .new_ ndexB naryFromFloat__SW G_1( ndex.getCPtr( ndex),  ndex), true);
  }

  publ c vo d add(long n, SW GTYPE_p_uns gned_char x) {
    sw gfa ssJN . ndexB naryFromFloat_add(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x));
  }

  publ c vo d reset() {
    sw gfa ssJN . ndexB naryFromFloat_reset(sw gCPtr, t );
  }

  publ c vo d search(long n, SW GTYPE_p_uns gned_char x, long k, SW GTYPE_p_ nt d stances, LongVector labels) {
    sw gfa ssJN . ndexB naryFromFloat_search(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x), k, SW GTYPE_p_ nt.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels);
  }

  publ c vo d tra n(long n, SW GTYPE_p_uns gned_char x) {
    sw gfa ssJN . ndexB naryFromFloat_tra n(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x));
  }

}
