/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndexHNSW extends  ndex {
  pr vate trans ent long sw gCPtr;

  protected  ndexHNSW(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . ndexHNSW_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndexHNSW obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndexHNSW(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d setHnsw(HNSW value) {
    sw gfa ssJN . ndexHNSW_hnsw_set(sw gCPtr, t , HNSW.getCPtr(value), value);
  }

  publ c HNSW getHnsw() {
    long cPtr = sw gfa ssJN . ndexHNSW_hnsw_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new HNSW(cPtr, false);
  }

  publ c vo d setOwn_f elds(boolean value) {
    sw gfa ssJN . ndexHNSW_own_f elds_set(sw gCPtr, t , value);
  }

  publ c boolean getOwn_f elds() {
    return sw gfa ssJN . ndexHNSW_own_f elds_get(sw gCPtr, t );
  }

  publ c vo d setStorage( ndex value) {
    sw gfa ssJN . ndexHNSW_storage_set(sw gCPtr, t ,  ndex.getCPtr(value), value);
  }

  publ c  ndex getStorage() {
    long cPtr = sw gfa ssJN . ndexHNSW_storage_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new  ndex(cPtr, false);
  }

  publ c vo d setReconstruct_from_ne ghbors(ReconstructFromNe ghbors value) {
    sw gfa ssJN . ndexHNSW_reconstruct_from_ne ghbors_set(sw gCPtr, t , ReconstructFromNe ghbors.getCPtr(value), value);
  }

  publ c ReconstructFromNe ghbors getReconstruct_from_ne ghbors() {
    long cPtr = sw gfa ssJN . ndexHNSW_reconstruct_from_ne ghbors_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new ReconstructFromNe ghbors(cPtr, false);
  }

  publ c  ndexHNSW( nt d,  nt M,  tr cType  tr c) {
    t (sw gfa ssJN .new_ ndexHNSW__SW G_0(d, M,  tr c.sw gValue()), true);
  }

  publ c  ndexHNSW( nt d,  nt M) {
    t (sw gfa ssJN .new_ ndexHNSW__SW G_1(d, M), true);
  }

  publ c  ndexHNSW( nt d) {
    t (sw gfa ssJN .new_ ndexHNSW__SW G_2(d), true);
  }

  publ c  ndexHNSW() {
    t (sw gfa ssJN .new_ ndexHNSW__SW G_3(), true);
  }

  publ c  ndexHNSW( ndex storage,  nt M) {
    t (sw gfa ssJN .new_ ndexHNSW__SW G_4( ndex.getCPtr(storage), storage, M), true);
  }

  publ c  ndexHNSW( ndex storage) {
    t (sw gfa ssJN .new_ ndexHNSW__SW G_5( ndex.getCPtr(storage), storage), true);
  }

  publ c vo d add(long n, SW GTYPE_p_float x) {
    sw gfa ssJN . ndexHNSW_add(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x));
  }

  publ c vo d tra n(long n, SW GTYPE_p_float x) {
    sw gfa ssJN . ndexHNSW_tra n(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x));
  }

  publ c vo d search(long n, SW GTYPE_p_float x, long k, SW GTYPE_p_float d stances, LongVector labels) {
    sw gfa ssJN . ndexHNSW_search(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels);
  }

  publ c vo d reconstruct(long key, SW GTYPE_p_float recons) {
    sw gfa ssJN . ndexHNSW_reconstruct(sw gCPtr, t , key, SW GTYPE_p_float.getCPtr(recons));
  }

  publ c vo d reset() {
    sw gfa ssJN . ndexHNSW_reset(sw gCPtr, t );
  }

  publ c vo d shr nk_level_0_ne ghbors( nt s ze) {
    sw gfa ssJN . ndexHNSW_shr nk_level_0_ne ghbors(sw gCPtr, t , s ze);
  }

  publ c vo d search_level_0(long n, SW GTYPE_p_float x, long k, SW GTYPE_p_ nt nearest, SW GTYPE_p_float nearest_d, SW GTYPE_p_float d stances, LongVector labels,  nt nprobe,  nt search_type) {
    sw gfa ssJN . ndexHNSW_search_level_0__SW G_0(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_ nt.getCPtr(nearest), SW GTYPE_p_float.getCPtr(nearest_d), SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels, nprobe, search_type);
  }

  publ c vo d search_level_0(long n, SW GTYPE_p_float x, long k, SW GTYPE_p_ nt nearest, SW GTYPE_p_float nearest_d, SW GTYPE_p_float d stances, LongVector labels,  nt nprobe) {
    sw gfa ssJN . ndexHNSW_search_level_0__SW G_1(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_ nt.getCPtr(nearest), SW GTYPE_p_float.getCPtr(nearest_d), SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels, nprobe);
  }

  publ c vo d search_level_0(long n, SW GTYPE_p_float x, long k, SW GTYPE_p_ nt nearest, SW GTYPE_p_float nearest_d, SW GTYPE_p_float d stances, LongVector labels) {
    sw gfa ssJN . ndexHNSW_search_level_0__SW G_2(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_ nt.getCPtr(nearest), SW GTYPE_p_float.getCPtr(nearest_d), SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels);
  }

  publ c vo d  n _level_0_from_knngraph( nt k, SW GTYPE_p_float D, LongVector  ) {
    sw gfa ssJN . ndexHNSW_ n _level_0_from_knngraph(sw gCPtr, t , k, SW GTYPE_p_float.getCPtr(D), SW GTYPE_p_long_long.getCPtr( .data()),  );
  }

  publ c vo d  n _level_0_from_entry_po nts( nt npt, SW GTYPE_p_ nt po nts, SW GTYPE_p_ nt nearests) {
    sw gfa ssJN . ndexHNSW_ n _level_0_from_entry_po nts(sw gCPtr, t , npt, SW GTYPE_p_ nt.getCPtr(po nts), SW GTYPE_p_ nt.getCPtr(nearests));
  }

  publ c vo d reorder_l nks() {
    sw gfa ssJN . ndexHNSW_reorder_l nks(sw gCPtr, t );
  }

  publ c vo d l nk_s ngletons() {
    sw gfa ssJN . ndexHNSW_l nk_s ngletons(sw gCPtr, t );
  }

}
