/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndex VFPQStats {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected  ndex VFPQStats(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndex VFPQStats obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndex VFPQStats(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setNref ne(long value) {
    sw gfa ssJN . ndex VFPQStats_nref ne_set(sw gCPtr, t , value);
  }

  publ c long getNref ne() {
    return sw gfa ssJN . ndex VFPQStats_nref ne_get(sw gCPtr, t );
  }

  publ c vo d setN_hamm ng_pass(long value) {
    sw gfa ssJN . ndex VFPQStats_n_hamm ng_pass_set(sw gCPtr, t , value);
  }

  publ c long getN_hamm ng_pass() {
    return sw gfa ssJN . ndex VFPQStats_n_hamm ng_pass_get(sw gCPtr, t );
  }

  publ c vo d setSearch_cycles(long value) {
    sw gfa ssJN . ndex VFPQStats_search_cycles_set(sw gCPtr, t , value);
  }

  publ c long getSearch_cycles() {
    return sw gfa ssJN . ndex VFPQStats_search_cycles_get(sw gCPtr, t );
  }

  publ c vo d setRef ne_cycles(long value) {
    sw gfa ssJN . ndex VFPQStats_ref ne_cycles_set(sw gCPtr, t , value);
  }

  publ c long getRef ne_cycles() {
    return sw gfa ssJN . ndex VFPQStats_ref ne_cycles_get(sw gCPtr, t );
  }

  publ c  ndex VFPQStats() {
    t (sw gfa ssJN .new_ ndex VFPQStats(), true);
  }

  publ c vo d reset() {
    sw gfa ssJN . ndex VFPQStats_reset(sw gCPtr, t );
  }

}
