/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndexPQ extends  ndexFlatCodes {
  pr vate trans ent long sw gCPtr;

  protected  ndexPQ(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . ndexPQ_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndexPQ obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndexPQ(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d setPq(ProductQuant zer value) {
    sw gfa ssJN . ndexPQ_pq_set(sw gCPtr, t , ProductQuant zer.getCPtr(value), value);
  }

  publ c ProductQuant zer getPq() {
    long cPtr = sw gfa ssJN . ndexPQ_pq_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new ProductQuant zer(cPtr, false);
  }

  publ c  ndexPQ( nt d, long M, long nb s,  tr cType  tr c) {
    t (sw gfa ssJN .new_ ndexPQ__SW G_0(d, M, nb s,  tr c.sw gValue()), true);
  }

  publ c  ndexPQ( nt d, long M, long nb s) {
    t (sw gfa ssJN .new_ ndexPQ__SW G_1(d, M, nb s), true);
  }

  publ c  ndexPQ() {
    t (sw gfa ssJN .new_ ndexPQ__SW G_2(), true);
  }

  publ c vo d tra n(long n, SW GTYPE_p_float x) {
    sw gfa ssJN . ndexPQ_tra n(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x));
  }

  publ c vo d search(long n, SW GTYPE_p_float x, long k, SW GTYPE_p_float d stances, LongVector labels) {
    sw gfa ssJN . ndexPQ_search(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels);
  }

  publ c vo d sa_encode(long n, SW GTYPE_p_float x, SW GTYPE_p_uns gned_char bytes) {
    sw gfa ssJN . ndexPQ_sa_encode(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), SW GTYPE_p_uns gned_char.getCPtr(bytes));
  }

  publ c vo d sa_decode(long n, SW GTYPE_p_uns gned_char bytes, SW GTYPE_p_float x) {
    sw gfa ssJN . ndexPQ_sa_decode(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(bytes), SW GTYPE_p_float.getCPtr(x));
  }

  publ c D stanceComputer get_d stance_computer() {
    long cPtr = sw gfa ssJN . ndexPQ_get_d stance_computer(sw gCPtr, t );
    return (cPtr == 0) ? null : new D stanceComputer(cPtr, false);
  }

  publ c vo d setDo_polysemous_tra n ng(boolean value) {
    sw gfa ssJN . ndexPQ_do_polysemous_tra n ng_set(sw gCPtr, t , value);
  }

  publ c boolean getDo_polysemous_tra n ng() {
    return sw gfa ssJN . ndexPQ_do_polysemous_tra n ng_get(sw gCPtr, t );
  }

  publ c vo d setPolysemous_tra n ng(PolysemousTra n ng value) {
    sw gfa ssJN . ndexPQ_polysemous_tra n ng_set(sw gCPtr, t , PolysemousTra n ng.getCPtr(value), value);
  }

  publ c PolysemousTra n ng getPolysemous_tra n ng() {
    long cPtr = sw gfa ssJN . ndexPQ_polysemous_tra n ng_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new PolysemousTra n ng(cPtr, false);
  }

  publ c vo d setSearch_type( ndexPQ.Search_type_t value) {
    sw gfa ssJN . ndexPQ_search_type_set(sw gCPtr, t , value.sw gValue());
  }

  publ c  ndexPQ.Search_type_t getSearch_type() {
    return  ndexPQ.Search_type_t.sw gToEnum(sw gfa ssJN . ndexPQ_search_type_get(sw gCPtr, t ));
  }

  publ c vo d setEncode_s gns(boolean value) {
    sw gfa ssJN . ndexPQ_encode_s gns_set(sw gCPtr, t , value);
  }

  publ c boolean getEncode_s gns() {
    return sw gfa ssJN . ndexPQ_encode_s gns_get(sw gCPtr, t );
  }

  publ c vo d setPolysemous_ht( nt value) {
    sw gfa ssJN . ndexPQ_polysemous_ht_set(sw gCPtr, t , value);
  }

  publ c  nt getPolysemous_ht() {
    return sw gfa ssJN . ndexPQ_polysemous_ht_get(sw gCPtr, t );
  }

  publ c vo d search_core_polysemous(long n, SW GTYPE_p_float x, long k, SW GTYPE_p_float d stances, LongVector labels) {
    sw gfa ssJN . ndexPQ_search_core_polysemous(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels);
  }

  publ c vo d hamm ng_d stance_ togram(long n, SW GTYPE_p_float x, long nb, SW GTYPE_p_float xb, LongVector d st_ togram) {
    sw gfa ssJN . ndexPQ_hamm ng_d stance_ togram(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), nb, SW GTYPE_p_float.getCPtr(xb), SW GTYPE_p_long_long.getCPtr(d st_ togram.data()), d st_ togram);
  }

  publ c vo d hamm ng_d stance_table(long n, SW GTYPE_p_float x, SW GTYPE_p_ nt d s) {
    sw gfa ssJN . ndexPQ_hamm ng_d stance_table(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), SW GTYPE_p_ nt.getCPtr(d s));
  }

  publ c f nal stat c class Search_type_t {
    publ c f nal stat c  ndexPQ.Search_type_t ST_PQ = new  ndexPQ.Search_type_t("ST_PQ");
    publ c f nal stat c  ndexPQ.Search_type_t ST_HE = new  ndexPQ.Search_type_t("ST_HE");
    publ c f nal stat c  ndexPQ.Search_type_t ST_general zed_HE = new  ndexPQ.Search_type_t("ST_general zed_HE");
    publ c f nal stat c  ndexPQ.Search_type_t ST_SDC = new  ndexPQ.Search_type_t("ST_SDC");
    publ c f nal stat c  ndexPQ.Search_type_t ST_polysemous = new  ndexPQ.Search_type_t("ST_polysemous");
    publ c f nal stat c  ndexPQ.Search_type_t ST_polysemous_general ze = new  ndexPQ.Search_type_t("ST_polysemous_general ze");

    publ c f nal  nt sw gValue() {
      return sw gValue;
    }

    publ c Str ng toStr ng() {
      return sw gNa ;
    }

    publ c stat c Search_type_t sw gToEnum( nt sw gValue) {
       f (sw gValue < sw gValues.length && sw gValue >= 0 && sw gValues[sw gValue].sw gValue == sw gValue)
        return sw gValues[sw gValue];
      for ( nt   = 0;   < sw gValues.length;  ++)
         f (sw gValues[ ].sw gValue == sw gValue)
          return sw gValues[ ];
      throw new  llegalArgu ntExcept on("No enum " + Search_type_t.class + " w h value " + sw gValue);
    }

    pr vate Search_type_t(Str ng sw gNa ) {
      t .sw gNa  = sw gNa ;
      t .sw gValue = sw gNext++;
    }

    pr vate Search_type_t(Str ng sw gNa ,  nt sw gValue) {
      t .sw gNa  = sw gNa ;
      t .sw gValue = sw gValue;
      sw gNext = sw gValue+1;
    }

    pr vate Search_type_t(Str ng sw gNa , Search_type_t sw gEnum) {
      t .sw gNa  = sw gNa ;
      t .sw gValue = sw gEnum.sw gValue;
      sw gNext = t .sw gValue+1;
    }

    pr vate stat c Search_type_t[] sw gValues = { ST_PQ, ST_HE, ST_general zed_HE, ST_SDC, ST_polysemous, ST_polysemous_general ze };
    pr vate stat c  nt sw gNext = 0;
    pr vate f nal  nt sw gValue;
    pr vate f nal Str ng sw gNa ;
  }

}
