/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndexFlat1D extends  ndexFlatL2 {
  pr vate trans ent long sw gCPtr;

  protected  ndexFlat1D(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . ndexFlat1D_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndexFlat1D obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndexFlat1D(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d setCont nuous_update(boolean value) {
    sw gfa ssJN . ndexFlat1D_cont nuous_update_set(sw gCPtr, t , value);
  }

  publ c boolean getCont nuous_update() {
    return sw gfa ssJN . ndexFlat1D_cont nuous_update_get(sw gCPtr, t );
  }

  publ c vo d setPerm(SW GTYPE_p_std__vectorT_ nt64_t_t value) {
    sw gfa ssJN . ndexFlat1D_perm_set(sw gCPtr, t , SW GTYPE_p_std__vectorT_ nt64_t_t.getCPtr(value));
  }

  publ c SW GTYPE_p_std__vectorT_ nt64_t_t getPerm() {
    long cPtr = sw gfa ssJN . ndexFlat1D_perm_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_std__vectorT_ nt64_t_t(cPtr, false);
  }

  publ c  ndexFlat1D(boolean cont nuous_update) {
    t (sw gfa ssJN .new_ ndexFlat1D__SW G_0(cont nuous_update), true);
  }

  publ c  ndexFlat1D() {
    t (sw gfa ssJN .new_ ndexFlat1D__SW G_1(), true);
  }

  publ c vo d update_permutat on() {
    sw gfa ssJN . ndexFlat1D_update_permutat on(sw gCPtr, t );
  }

  publ c vo d add(long n, SW GTYPE_p_float x) {
    sw gfa ssJN . ndexFlat1D_add(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x));
  }

  publ c vo d reset() {
    sw gfa ssJN . ndexFlat1D_reset(sw gCPtr, t );
  }

  publ c vo d search(long n, SW GTYPE_p_float x, long k, SW GTYPE_p_float d stances, LongVector labels) {
    sw gfa ssJN . ndexFlat1D_search(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels);
  }

}
