/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndexHNSW2Level extends  ndexHNSW {
  pr vate trans ent long sw gCPtr;

  protected  ndexHNSW2Level(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . ndexHNSW2Level_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndexHNSW2Level obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndexHNSW2Level(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c  ndexHNSW2Level() {
    t (sw gfa ssJN .new_ ndexHNSW2Level__SW G_0(), true);
  }

  publ c  ndexHNSW2Level( ndex quant zer, long nl st,  nt m_pq,  nt M) {
    t (sw gfa ssJN .new_ ndexHNSW2Level__SW G_1( ndex.getCPtr(quant zer), quant zer, nl st, m_pq, M), true);
  }

  publ c vo d fl p_to_ vf() {
    sw gfa ssJN . ndexHNSW2Level_fl p_to_ vf(sw gCPtr, t );
  }

  publ c vo d search(long n, SW GTYPE_p_float x, long k, SW GTYPE_p_float d stances, LongVector labels) {
    sw gfa ssJN . ndexHNSW2Level_search(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels);
  }

}
