/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndexRef ne extends  ndex {
  pr vate trans ent long sw gCPtr;

  protected  ndexRef ne(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . ndexRef ne_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndexRef ne obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndexRef ne(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d setBase_ ndex( ndex value) {
    sw gfa ssJN . ndexRef ne_base_ ndex_set(sw gCPtr, t ,  ndex.getCPtr(value), value);
  }

  publ c  ndex getBase_ ndex() {
    long cPtr = sw gfa ssJN . ndexRef ne_base_ ndex_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new  ndex(cPtr, false);
  }

  publ c vo d setRef ne_ ndex( ndex value) {
    sw gfa ssJN . ndexRef ne_ref ne_ ndex_set(sw gCPtr, t ,  ndex.getCPtr(value), value);
  }

  publ c  ndex getRef ne_ ndex() {
    long cPtr = sw gfa ssJN . ndexRef ne_ref ne_ ndex_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new  ndex(cPtr, false);
  }

  publ c vo d setOwn_f elds(boolean value) {
    sw gfa ssJN . ndexRef ne_own_f elds_set(sw gCPtr, t , value);
  }

  publ c boolean getOwn_f elds() {
    return sw gfa ssJN . ndexRef ne_own_f elds_get(sw gCPtr, t );
  }

  publ c vo d setOwn_ref ne_ ndex(boolean value) {
    sw gfa ssJN . ndexRef ne_own_ref ne_ ndex_set(sw gCPtr, t , value);
  }

  publ c boolean getOwn_ref ne_ ndex() {
    return sw gfa ssJN . ndexRef ne_own_ref ne_ ndex_get(sw gCPtr, t );
  }

  publ c vo d setK_factor(float value) {
    sw gfa ssJN . ndexRef ne_k_factor_set(sw gCPtr, t , value);
  }

  publ c float getK_factor() {
    return sw gfa ssJN . ndexRef ne_k_factor_get(sw gCPtr, t );
  }

  publ c  ndexRef ne( ndex base_ ndex,  ndex ref ne_ ndex) {
    t (sw gfa ssJN .new_ ndexRef ne__SW G_0( ndex.getCPtr(base_ ndex), base_ ndex,  ndex.getCPtr(ref ne_ ndex), ref ne_ ndex), true);
  }

  publ c  ndexRef ne() {
    t (sw gfa ssJN .new_ ndexRef ne__SW G_1(), true);
  }

  publ c vo d tra n(long n, SW GTYPE_p_float x) {
    sw gfa ssJN . ndexRef ne_tra n(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x));
  }

  publ c vo d add(long n, SW GTYPE_p_float x) {
    sw gfa ssJN . ndexRef ne_add(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x));
  }

  publ c vo d reset() {
    sw gfa ssJN . ndexRef ne_reset(sw gCPtr, t );
  }

  publ c vo d search(long n, SW GTYPE_p_float x, long k, SW GTYPE_p_float d stances, LongVector labels) {
    sw gfa ssJN . ndexRef ne_search(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels);
  }

  publ c vo d reconstruct(long key, SW GTYPE_p_float recons) {
    sw gfa ssJN . ndexRef ne_reconstruct(sw gCPtr, t , key, SW GTYPE_p_float.getCPtr(recons));
  }

  publ c long sa_code_s ze() {
    return sw gfa ssJN . ndexRef ne_sa_code_s ze(sw gCPtr, t );
  }

  publ c vo d sa_encode(long n, SW GTYPE_p_float x, SW GTYPE_p_uns gned_char bytes) {
    sw gfa ssJN . ndexRef ne_sa_encode(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x), SW GTYPE_p_uns gned_char.getCPtr(bytes));
  }

  publ c vo d sa_decode(long n, SW GTYPE_p_uns gned_char bytes, SW GTYPE_p_float x) {
    sw gfa ssJN . ndexRef ne_sa_decode(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(bytes), SW GTYPE_p_float.getCPtr(x));
  }

}
