/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndex VFStats {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected  ndex VFStats(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndex VFStats obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndex VFStats(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setNq(long value) {
    sw gfa ssJN . ndex VFStats_nq_set(sw gCPtr, t , value);
  }

  publ c long getNq() {
    return sw gfa ssJN . ndex VFStats_nq_get(sw gCPtr, t );
  }

  publ c vo d setNl st(long value) {
    sw gfa ssJN . ndex VFStats_nl st_set(sw gCPtr, t , value);
  }

  publ c long getNl st() {
    return sw gfa ssJN . ndex VFStats_nl st_get(sw gCPtr, t );
  }

  publ c vo d setNd s(long value) {
    sw gfa ssJN . ndex VFStats_nd s_set(sw gCPtr, t , value);
  }

  publ c long getNd s() {
    return sw gfa ssJN . ndex VFStats_nd s_get(sw gCPtr, t );
  }

  publ c vo d setN ap_updates(long value) {
    sw gfa ssJN . ndex VFStats_n ap_updates_set(sw gCPtr, t , value);
  }

  publ c long getN ap_updates() {
    return sw gfa ssJN . ndex VFStats_n ap_updates_get(sw gCPtr, t );
  }

  publ c vo d setQuant zat on_t  (double value) {
    sw gfa ssJN . ndex VFStats_quant zat on_t  _set(sw gCPtr, t , value);
  }

  publ c double getQuant zat on_t  () {
    return sw gfa ssJN . ndex VFStats_quant zat on_t  _get(sw gCPtr, t );
  }

  publ c vo d setSearch_t  (double value) {
    sw gfa ssJN . ndex VFStats_search_t  _set(sw gCPtr, t , value);
  }

  publ c double getSearch_t  () {
    return sw gfa ssJN . ndex VFStats_search_t  _get(sw gCPtr, t );
  }

  publ c  ndex VFStats() {
    t (sw gfa ssJN .new_ ndex VFStats(), true);
  }

  publ c vo d reset() {
    sw gfa ssJN . ndex VFStats_reset(sw gCPtr, t );
  }

  publ c vo d add( ndex VFStats ot r) {
    sw gfa ssJN . ndex VFStats_add(sw gCPtr, t ,  ndex VFStats.getCPtr(ot r), ot r);
  }

}
