/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ndexB naryHNSW extends  ndexB nary {
  pr vate trans ent long sw gCPtr;

  protected  ndexB naryHNSW(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . ndexB naryHNSW_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ndexB naryHNSW obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ndexB naryHNSW(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d setHnsw(HNSW value) {
    sw gfa ssJN . ndexB naryHNSW_hnsw_set(sw gCPtr, t , HNSW.getCPtr(value), value);
  }

  publ c HNSW getHnsw() {
    long cPtr = sw gfa ssJN . ndexB naryHNSW_hnsw_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new HNSW(cPtr, false);
  }

  publ c vo d setOwn_f elds(boolean value) {
    sw gfa ssJN . ndexB naryHNSW_own_f elds_set(sw gCPtr, t , value);
  }

  publ c boolean getOwn_f elds() {
    return sw gfa ssJN . ndexB naryHNSW_own_f elds_get(sw gCPtr, t );
  }

  publ c vo d setStorage( ndexB nary value) {
    sw gfa ssJN . ndexB naryHNSW_storage_set(sw gCPtr, t ,  ndexB nary.getCPtr(value), value);
  }

  publ c  ndexB nary getStorage() {
    long cPtr = sw gfa ssJN . ndexB naryHNSW_storage_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new  ndexB nary(cPtr, false);
  }

  publ c  ndexB naryHNSW() {
    t (sw gfa ssJN .new_ ndexB naryHNSW__SW G_0(), true);
  }

  publ c  ndexB naryHNSW( nt d,  nt M) {
    t (sw gfa ssJN .new_ ndexB naryHNSW__SW G_1(d, M), true);
  }

  publ c  ndexB naryHNSW( nt d) {
    t (sw gfa ssJN .new_ ndexB naryHNSW__SW G_2(d), true);
  }

  publ c  ndexB naryHNSW( ndexB nary storage,  nt M) {
    t (sw gfa ssJN .new_ ndexB naryHNSW__SW G_3( ndexB nary.getCPtr(storage), storage, M), true);
  }

  publ c  ndexB naryHNSW( ndexB nary storage) {
    t (sw gfa ssJN .new_ ndexB naryHNSW__SW G_4( ndexB nary.getCPtr(storage), storage), true);
  }

  publ c D stanceComputer get_d stance_computer() {
    long cPtr = sw gfa ssJN . ndexB naryHNSW_get_d stance_computer(sw gCPtr, t );
    return (cPtr == 0) ? null : new D stanceComputer(cPtr, false);
  }

  publ c vo d add(long n, SW GTYPE_p_uns gned_char x) {
    sw gfa ssJN . ndexB naryHNSW_add(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x));
  }

  publ c vo d tra n(long n, SW GTYPE_p_uns gned_char x) {
    sw gfa ssJN . ndexB naryHNSW_tra n(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x));
  }

  publ c vo d search(long n, SW GTYPE_p_uns gned_char x, long k, SW GTYPE_p_ nt d stances, LongVector labels) {
    sw gfa ssJN . ndexB naryHNSW_search(sw gCPtr, t , n, SW GTYPE_p_uns gned_char.getCPtr(x), k, SW GTYPE_p_ nt.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels);
  }

  publ c vo d reconstruct(long key, SW GTYPE_p_uns gned_char recons) {
    sw gfa ssJN . ndexB naryHNSW_reconstruct(sw gCPtr, t , key, SW GTYPE_p_uns gned_char.getCPtr(recons));
  }

  publ c vo d reset() {
    sw gfa ssJN . ndexB naryHNSW_reset(sw gCPtr, t );
  }

}
