/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  ntersect onCr er on extends AutoTuneCr er on {
  pr vate trans ent long sw gCPtr;

  protected  ntersect onCr er on(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . ntersect onCr er on_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( ntersect onCr er on obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ ntersect onCr er on(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d setR(long value) {
    sw gfa ssJN . ntersect onCr er on_R_set(sw gCPtr, t , value);
  }

  publ c long getR() {
    return sw gfa ssJN . ntersect onCr er on_R_get(sw gCPtr, t );
}

  publ c  ntersect onCr er on(long nq, long R) {
    t (sw gfa ssJN .new_ ntersect onCr er on(nq, R), true);
  }

  publ c double evaluate(SW GTYPE_p_float D, LongVector  ) {
    return sw gfa ssJN . ntersect onCr er on_evaluate(sw gCPtr, t , SW GTYPE_p_float.getCPtr(D), SW GTYPE_p_long_long.getCPtr( .data()),  );
  }

}
