/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  nterruptCallback {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected  nterruptCallback(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( nterruptCallback obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ nterruptCallback(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c boolean want_ nterrupt() {
    return sw gfa ssJN . nterruptCallback_want_ nterrupt(sw gCPtr, t );
  }

  publ c stat c vo d clear_ nstance() {
    sw gfa ssJN . nterruptCallback_clear_ nstance();
  }

  publ c stat c vo d c ck() {
    sw gfa ssJN . nterruptCallback_c ck();
  }

  publ c stat c boolean  s_ nterrupted() {
    return sw gfa ssJN . nterruptCallback_ s_ nterrupted();
  }

  publ c stat c long get_per od_h nt(long flops) {
    return sw gfa ssJN . nterruptCallback_get_per od_h nt(flops);
  }

}
