/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  nvertedL stsPtrVector {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected  nvertedL stsPtrVector(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( nvertedL stsPtrVector obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ nvertedL stsPtrVector(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c  nvertedL stsPtrVector() {
    t (sw gfa ssJN .new_ nvertedL stsPtrVector(), true);
  }

  publ c vo d push_back( nvertedL sts arg0) {
    sw gfa ssJN . nvertedL stsPtrVector_push_back(sw gCPtr, t ,  nvertedL sts.getCPtr(arg0), arg0);
  }

  publ c vo d clear() {
    sw gfa ssJN . nvertedL stsPtrVector_clear(sw gCPtr, t );
  }

  publ c SW GTYPE_p_p_fa ss__ nvertedL sts data() {
    long cPtr = sw gfa ssJN . nvertedL stsPtrVector_data(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_p_fa ss__ nvertedL sts(cPtr, false);
  }

  publ c long s ze() {
    return sw gfa ssJN . nvertedL stsPtrVector_s ze(sw gCPtr, t );
  }

  publ c  nvertedL sts at(long n) {
    long cPtr = sw gfa ssJN . nvertedL stsPtrVector_at(sw gCPtr, t , n);
    return (cPtr == 0) ? null : new  nvertedL sts(cPtr, false);
  }

  publ c vo d res ze(long n) {
    sw gfa ssJN . nvertedL stsPtrVector_res ze(sw gCPtr, t , n);
  }

  publ c vo d reserve(long n) {
    sw gfa ssJN . nvertedL stsPtrVector_reserve(sw gCPtr, t , n);
  }

  publ c vo d swap( nvertedL stsPtrVector ot r) {
    sw gfa ssJN . nvertedL stsPtrVector_swap(sw gCPtr, t ,  nvertedL stsPtrVector.getCPtr(ot r), ot r);
  }

}
