/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class  VFPQSearchPara ters extends  VFSearchPara ters {
  pr vate trans ent long sw gCPtr;

  protected  VFPQSearchPara ters(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN . VFPQSearchPara ters_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr( VFPQSearchPara ters obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ VFPQSearchPara ters(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d setScan_table_threshold(long value) {
    sw gfa ssJN . VFPQSearchPara ters_scan_table_threshold_set(sw gCPtr, t , value);
  }

  publ c long getScan_table_threshold() {
    return sw gfa ssJN . VFPQSearchPara ters_scan_table_threshold_get(sw gCPtr, t );
  }

  publ c vo d setPolysemous_ht( nt value) {
    sw gfa ssJN . VFPQSearchPara ters_polysemous_ht_set(sw gCPtr, t , value);
  }

  publ c  nt getPolysemous_ht() {
    return sw gfa ssJN . VFPQSearchPara ters_polysemous_ht_get(sw gCPtr, t );
  }

  publ c  VFPQSearchPara ters() {
    t (sw gfa ssJN .new_ VFPQSearchPara ters(), true);
  }

}
