/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class longArray {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected longArray(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(longArray obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_longArray(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c longArray( nt nele nts) {
    t (sw gfa ssJN .new_longArray(nele nts), true);
  }

  publ c long get em( nt  ndex) {
    return sw gfa ssJN .longArray_get em(sw gCPtr, t ,  ndex);
  }

  publ c vo d set em( nt  ndex, long value) {
    sw gfa ssJN .longArray_set em(sw gCPtr, t ,  ndex, value);
  }

  publ c SW GTYPE_p_long_long cast() {
    long cPtr = sw gfa ssJN .longArray_cast(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_long_long(cPtr, false);
  }

  publ c stat c longArray frompo nter(SW GTYPE_p_long_long t) {
    long cPtr = sw gfa ssJN .longArray_frompo nter(SW GTYPE_p_long_long.getCPtr(t));
    return (cPtr == 0) ? null : new longArray(cPtr, false);
  }

}
