/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class LongVectorVector {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected LongVectorVector(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(LongVectorVector obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_LongVectorVector(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c LongVectorVector() {
    t (sw gfa ssJN .new_LongVectorVector(), true);
  }

  publ c vo d push_back(SW GTYPE_p_std__vectorT_long_t arg0) {
    sw gfa ssJN .LongVectorVector_push_back(sw gCPtr, t , SW GTYPE_p_std__vectorT_long_t.getCPtr(arg0));
  }

  publ c vo d clear() {
    sw gfa ssJN .LongVectorVector_clear(sw gCPtr, t );
  }

  publ c SW GTYPE_p_std__vectorT_long_t data() {
    long cPtr = sw gfa ssJN .LongVectorVector_data(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_std__vectorT_long_t(cPtr, false);
  }

  publ c long s ze() {
    return sw gfa ssJN .LongVectorVector_s ze(sw gCPtr, t );
  }

  publ c SW GTYPE_p_std__vectorT_long_t at(long n) {
    return new SW GTYPE_p_std__vectorT_long_t(sw gfa ssJN .LongVectorVector_at(sw gCPtr, t , n), true);
  }

  publ c vo d res ze(long n) {
    sw gfa ssJN .LongVectorVector_res ze(sw gCPtr, t , n);
  }

  publ c vo d reserve(long n) {
    sw gfa ssJN .LongVectorVector_reserve(sw gCPtr, t , n);
  }

  publ c vo d swap(LongVectorVector ot r) {
    sw gfa ssJN .LongVectorVector_swap(sw gCPtr, t , LongVectorVector.getCPtr(ot r), ot r);
  }

}
