/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class Masked nvertedL sts extends ReadOnly nvertedL sts {
  pr vate trans ent long sw gCPtr;

  protected Masked nvertedL sts(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN .Masked nvertedL sts_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(Masked nvertedL sts obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_Masked nvertedL sts(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d set l0( nvertedL sts value) {
    sw gfa ssJN .Masked nvertedL sts_ l0_set(sw gCPtr, t ,  nvertedL sts.getCPtr(value), value);
  }

  publ c  nvertedL sts get l0() {
    long cPtr = sw gfa ssJN .Masked nvertedL sts_ l0_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new  nvertedL sts(cPtr, false);
  }

  publ c vo d set l1( nvertedL sts value) {
    sw gfa ssJN .Masked nvertedL sts_ l1_set(sw gCPtr, t ,  nvertedL sts.getCPtr(value), value);
  }

  publ c  nvertedL sts get l1() {
    long cPtr = sw gfa ssJN .Masked nvertedL sts_ l1_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new  nvertedL sts(cPtr, false);
  }

  publ c Masked nvertedL sts( nvertedL sts  l0,  nvertedL sts  l1) {
    t (sw gfa ssJN .new_Masked nvertedL sts( nvertedL sts.getCPtr( l0),  l0,  nvertedL sts.getCPtr( l1),  l1), true);
  }

  publ c long l st_s ze(long l st_no) {
    return sw gfa ssJN .Masked nvertedL sts_l st_s ze(sw gCPtr, t , l st_no);
  }

  publ c SW GTYPE_p_uns gned_char get_codes(long l st_no) {
    long cPtr = sw gfa ssJN .Masked nvertedL sts_get_codes(sw gCPtr, t , l st_no);
    return (cPtr == 0) ? null : new SW GTYPE_p_uns gned_char(cPtr, false);
  }

  publ c LongVector get_ ds(long l st_no) {
    return new LongVector(sw gfa ssJN .Masked nvertedL sts_get_ ds(sw gCPtr, t , l st_no), false);
}

  publ c vo d release_codes(long l st_no, SW GTYPE_p_uns gned_char codes) {
    sw gfa ssJN .Masked nvertedL sts_release_codes(sw gCPtr, t , l st_no, SW GTYPE_p_uns gned_char.getCPtr(codes));
  }

  publ c vo d release_ ds(long l st_no, LongVector  ds) {
    sw gfa ssJN .Masked nvertedL sts_release_ ds(sw gCPtr, t , l st_no, SW GTYPE_p_long_long.getCPtr( ds.data()),  ds);
  }

  publ c long get_s ngle_ d(long l st_no, long offset) {
    return sw gfa ssJN .Masked nvertedL sts_get_s ngle_ d(sw gCPtr, t , l st_no, offset);
}

  publ c SW GTYPE_p_uns gned_char get_s ngle_code(long l st_no, long offset) {
    long cPtr = sw gfa ssJN .Masked nvertedL sts_get_s ngle_code(sw gCPtr, t , l st_no, offset);
    return (cPtr == 0) ? null : new SW GTYPE_p_uns gned_char(cPtr, false);
  }

  publ c vo d prefetch_l sts(LongVector l st_nos,  nt nl st) {
    sw gfa ssJN .Masked nvertedL sts_prefetch_l sts(sw gCPtr, t , SW GTYPE_p_long_long.getCPtr(l st_nos.data()), l st_nos, nl st);
  }

}
