/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c f nal class  tr cType {
  publ c f nal stat c  tr cType METR C_ NNER_PRODUCT = new  tr cType("METR C_ NNER_PRODUCT", sw gfa ssJN .METR C_ NNER_PRODUCT_get());
  publ c f nal stat c  tr cType METR C_L2 = new  tr cType("METR C_L2", sw gfa ssJN .METR C_L2_get());
  publ c f nal stat c  tr cType METR C_L1 = new  tr cType("METR C_L1");
  publ c f nal stat c  tr cType METR C_L nf = new  tr cType("METR C_L nf");
  publ c f nal stat c  tr cType METR C_Lp = new  tr cType("METR C_Lp");
  publ c f nal stat c  tr cType METR C_Canberra = new  tr cType("METR C_Canberra", sw gfa ssJN .METR C_Canberra_get());
  publ c f nal stat c  tr cType METR C_BrayCurt s = new  tr cType("METR C_BrayCurt s");
  publ c f nal stat c  tr cType METR C_JensenShannon = new  tr cType("METR C_JensenShannon");

  publ c f nal  nt sw gValue() {
    return sw gValue;
  }

  publ c Str ng toStr ng() {
    return sw gNa ;
  }

  publ c stat c  tr cType sw gToEnum( nt sw gValue) {
     f (sw gValue < sw gValues.length && sw gValue >= 0 && sw gValues[sw gValue].sw gValue == sw gValue)
      return sw gValues[sw gValue];
    for ( nt   = 0;   < sw gValues.length;  ++)
       f (sw gValues[ ].sw gValue == sw gValue)
        return sw gValues[ ];
    throw new  llegalArgu ntExcept on("No enum " +  tr cType.class + " w h value " + sw gValue);
  }

  pr vate  tr cType(Str ng sw gNa ) {
    t .sw gNa  = sw gNa ;
    t .sw gValue = sw gNext++;
  }

  pr vate  tr cType(Str ng sw gNa ,  nt sw gValue) {
    t .sw gNa  = sw gNa ;
    t .sw gValue = sw gValue;
    sw gNext = sw gValue+1;
  }

  pr vate  tr cType(Str ng sw gNa ,  tr cType sw gEnum) {
    t .sw gNa  = sw gNa ;
    t .sw gValue = sw gEnum.sw gValue;
    sw gNext = t .sw gValue+1;
  }

  pr vate stat c  tr cType[] sw gValues = { METR C_ NNER_PRODUCT, METR C_L2, METR C_L1, METR C_L nf, METR C_Lp, METR C_Canberra, METR C_BrayCurt s, METR C_JensenShannon };
  pr vate stat c  nt sw gNext = 0;
  pr vate f nal  nt sw gValue;
  pr vate f nal Str ng sw gNa ;
}

