/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class Operat ngPo ntVector {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected Operat ngPo ntVector(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(Operat ngPo ntVector obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_Operat ngPo ntVector(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c Operat ngPo ntVector() {
    t (sw gfa ssJN .new_Operat ngPo ntVector(), true);
  }

  publ c vo d push_back(Operat ngPo nt arg0) {
    sw gfa ssJN .Operat ngPo ntVector_push_back(sw gCPtr, t , Operat ngPo nt.getCPtr(arg0), arg0);
  }

  publ c vo d clear() {
    sw gfa ssJN .Operat ngPo ntVector_clear(sw gCPtr, t );
  }

  publ c Operat ngPo nt data() {
    long cPtr = sw gfa ssJN .Operat ngPo ntVector_data(sw gCPtr, t );
    return (cPtr == 0) ? null : new Operat ngPo nt(cPtr, false);
  }

  publ c long s ze() {
    return sw gfa ssJN .Operat ngPo ntVector_s ze(sw gCPtr, t );
  }

  publ c Operat ngPo nt at(long n) {
    return new Operat ngPo nt(sw gfa ssJN .Operat ngPo ntVector_at(sw gCPtr, t , n), true);
  }

  publ c vo d res ze(long n) {
    sw gfa ssJN .Operat ngPo ntVector_res ze(sw gCPtr, t , n);
  }

  publ c vo d reserve(long n) {
    sw gfa ssJN .Operat ngPo ntVector_reserve(sw gCPtr, t , n);
  }

  publ c vo d swap(Operat ngPo ntVector ot r) {
    sw gfa ssJN .Operat ngPo ntVector_swap(sw gCPtr, t , Operat ngPo ntVector.getCPtr(ot r), ot r);
  }

}
