/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class Part  onStats {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected Part  onStats(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(Part  onStats obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_Part  onStats(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setB ssect_cycles(long value) {
    sw gfa ssJN .Part  onStats_b ssect_cycles_set(sw gCPtr, t , value);
  }

  publ c long getB ssect_cycles() {
    return sw gfa ssJN .Part  onStats_b ssect_cycles_get(sw gCPtr, t );
  }

  publ c vo d setCompress_cycles(long value) {
    sw gfa ssJN .Part  onStats_compress_cycles_set(sw gCPtr, t , value);
  }

  publ c long getCompress_cycles() {
    return sw gfa ssJN .Part  onStats_compress_cycles_get(sw gCPtr, t );
  }

  publ c Part  onStats() {
    t (sw gfa ssJN .new_Part  onStats(), true);
  }

  publ c vo d reset() {
    sw gfa ssJN .Part  onStats_reset(sw gCPtr, t );
  }

}
