/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class PQDecoderGener c {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected PQDecoderGener c(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(PQDecoderGener c obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_PQDecoderGener c(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setCode(SW GTYPE_p_uns gned_char value) {
    sw gfa ssJN .PQDecoderGener c_code_set(sw gCPtr, t , SW GTYPE_p_uns gned_char.getCPtr(value));
  }

  publ c SW GTYPE_p_uns gned_char getCode() {
    long cPtr = sw gfa ssJN .PQDecoderGener c_code_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_uns gned_char(cPtr, false);
  }

  publ c vo d setOffset(short value) {
    sw gfa ssJN .PQDecoderGener c_offset_set(sw gCPtr, t , value);
  }

  publ c short getOffset() {
    return sw gfa ssJN .PQDecoderGener c_offset_get(sw gCPtr, t );
  }

  publ c  nt getNb s() {
    return sw gfa ssJN .PQDecoderGener c_nb s_get(sw gCPtr, t );
  }

  publ c long getMask() {
    return sw gfa ssJN .PQDecoderGener c_mask_get(sw gCPtr, t );
  }

  publ c vo d setReg(short value) {
    sw gfa ssJN .PQDecoderGener c_reg_set(sw gCPtr, t , value);
  }

  publ c short getReg() {
    return sw gfa ssJN .PQDecoderGener c_reg_get(sw gCPtr, t );
  }

  publ c PQDecoderGener c(SW GTYPE_p_uns gned_char code,  nt nb s) {
    t (sw gfa ssJN .new_PQDecoderGener c(SW GTYPE_p_uns gned_char.getCPtr(code), nb s), true);
  }

  publ c long decode() {
    return sw gfa ssJN .PQDecoderGener c_decode(sw gCPtr, t );
  }

}
