/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class PQDecoder8 {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected PQDecoder8(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(PQDecoder8 obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_PQDecoder8(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setCode(SW GTYPE_p_uns gned_char value) {
    sw gfa ssJN .PQDecoder8_code_set(sw gCPtr, t , SW GTYPE_p_uns gned_char.getCPtr(value));
  }

  publ c SW GTYPE_p_uns gned_char getCode() {
    long cPtr = sw gfa ssJN .PQDecoder8_code_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_uns gned_char(cPtr, false);
  }

  publ c PQDecoder8(SW GTYPE_p_uns gned_char code,  nt nb s) {
    t (sw gfa ssJN .new_PQDecoder8(SW GTYPE_p_uns gned_char.getCPtr(code), nb s), true);
  }

  publ c long decode() {
    return sw gfa ssJN .PQDecoder8_decode(sw gCPtr, t );
  }

  publ c f nal stat c  nt nb s = sw gfa ssJN .PQDecoder8_nb s_get();
}
