/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class Progress veD m ndexFactory {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected Progress veD m ndexFactory(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(Progress veD m ndexFactory obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_Progress veD m ndexFactory(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c Progress veD m ndexFactory() {
    t (sw gfa ssJN .new_Progress veD m ndexFactory(), true);
  }

}
