/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class RandomRotat onMatr x extends L nearTransform {
  pr vate trans ent long sw gCPtr;

  protected RandomRotat onMatr x(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN .RandomRotat onMatr x_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(RandomRotat onMatr x obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_RandomRotat onMatr x(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c RandomRotat onMatr x( nt d_ n,  nt d_out) {
    t (sw gfa ssJN .new_RandomRotat onMatr x__SW G_0(d_ n, d_out), true);
  }

  publ c vo d  n ( nt seed) {
    sw gfa ssJN .RandomRotat onMatr x_ n (sw gCPtr, t , seed);
  }

  publ c vo d tra n(long n, SW GTYPE_p_float x) {
    sw gfa ssJN .RandomRotat onMatr x_tra n(sw gCPtr, t , n, SW GTYPE_p_float.getCPtr(x));
  }

  publ c RandomRotat onMatr x() {
    t (sw gfa ssJN .new_RandomRotat onMatr x__SW G_1(), true);
  }

}
