/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class RangeSearchResult {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected RangeSearchResult(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(RangeSearchResult obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_RangeSearchResult(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setNq(long value) {
    sw gfa ssJN .RangeSearchResult_nq_set(sw gCPtr, t , value);
  }

  publ c long getNq() {
    return sw gfa ssJN .RangeSearchResult_nq_get(sw gCPtr, t );
  }

  publ c vo d setL ms(SW GTYPE_p_uns gned_long value) {
    sw gfa ssJN .RangeSearchResult_l ms_set(sw gCPtr, t , SW GTYPE_p_uns gned_long.getCPtr(value));
  }

  publ c SW GTYPE_p_uns gned_long getL ms() {
    long cPtr = sw gfa ssJN .RangeSearchResult_l ms_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_uns gned_long(cPtr, false);
  }

  publ c vo d setLabels(LongVector value) {
    sw gfa ssJN .RangeSearchResult_labels_set(sw gCPtr, t , SW GTYPE_p_long_long.getCPtr(value.data()), value);
  }

  publ c LongVector getLabels() {
    return new LongVector(sw gfa ssJN .RangeSearchResult_labels_get(sw gCPtr, t ), false);
}

  publ c vo d setD stances(SW GTYPE_p_float value) {
    sw gfa ssJN .RangeSearchResult_d stances_set(sw gCPtr, t , SW GTYPE_p_float.getCPtr(value));
  }

  publ c SW GTYPE_p_float getD stances() {
    long cPtr = sw gfa ssJN .RangeSearchResult_d stances_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_float(cPtr, false);
  }

  publ c vo d setBuffer_s ze(long value) {
    sw gfa ssJN .RangeSearchResult_buffer_s ze_set(sw gCPtr, t , value);
  }

  publ c long getBuffer_s ze() {
    return sw gfa ssJN .RangeSearchResult_buffer_s ze_get(sw gCPtr, t );
  }

  publ c vo d do_allocat on() {
    sw gfa ssJN .RangeSearchResult_do_allocat on(sw gCPtr, t );
  }

}
