/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class RangeQueryResult {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected RangeQueryResult(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(RangeQueryResult obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_RangeQueryResult(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setQno(long value) {
    sw gfa ssJN .RangeQueryResult_qno_set(sw gCPtr, t , value);
  }

  publ c long getQno() {
    return sw gfa ssJN .RangeQueryResult_qno_get(sw gCPtr, t );
}

  publ c vo d setNres(long value) {
    sw gfa ssJN .RangeQueryResult_nres_set(sw gCPtr, t , value);
  }

  publ c long getNres() {
    return sw gfa ssJN .RangeQueryResult_nres_get(sw gCPtr, t );
  }

  publ c vo d setPres(RangeSearchPart alResult value) {
    sw gfa ssJN .RangeQueryResult_pres_set(sw gCPtr, t , RangeSearchPart alResult.getCPtr(value), value);
  }

  publ c RangeSearchPart alResult getPres() {
    long cPtr = sw gfa ssJN .RangeQueryResult_pres_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new RangeSearchPart alResult(cPtr, false);
  }

  publ c vo d add(float d s, long  d) {
    sw gfa ssJN .RangeQueryResult_add(sw gCPtr, t , d s,  d);
  }

  publ c RangeQueryResult() {
    t (sw gfa ssJN .new_RangeQueryResult(), true);
  }

}
