/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class ReadOnly nvertedL sts extends  nvertedL sts {
  pr vate trans ent long sw gCPtr;

  protected ReadOnly nvertedL sts(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN .ReadOnly nvertedL sts_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(ReadOnly nvertedL sts obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ReadOnly nvertedL sts(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c long add_entr es(long l st_no, long n_entry, LongVector  ds, SW GTYPE_p_uns gned_char code) {
    return sw gfa ssJN .ReadOnly nvertedL sts_add_entr es(sw gCPtr, t , l st_no, n_entry, SW GTYPE_p_long_long.getCPtr( ds.data()),  ds, SW GTYPE_p_uns gned_char.getCPtr(code));
  }

  publ c vo d update_entr es(long l st_no, long offset, long n_entry, LongVector  ds, SW GTYPE_p_uns gned_char code) {
    sw gfa ssJN .ReadOnly nvertedL sts_update_entr es(sw gCPtr, t , l st_no, offset, n_entry, SW GTYPE_p_long_long.getCPtr( ds.data()),  ds, SW GTYPE_p_uns gned_char.getCPtr(code));
  }

  publ c vo d res ze(long l st_no, long new_s ze) {
    sw gfa ssJN .ReadOnly nvertedL sts_res ze(sw gCPtr, t , l st_no, new_s ze);
  }

}
