/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class ReproduceD stancesObject ve extends Permutat onObject ve {
  pr vate trans ent long sw gCPtr;

  protected ReproduceD stancesObject ve(long cPtr, boolean c moryOwn) {
    super(sw gfa ssJN .ReproduceD stancesObject ve_SW GUpcast(cPtr), c moryOwn);
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(ReproduceD stancesObject ve obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_ReproduceD stancesObject ve(sw gCPtr);
      }
      sw gCPtr = 0;
    }
    super.delete();
  }

  publ c vo d setD s_  ght_factor(double value) {
    sw gfa ssJN .ReproduceD stancesObject ve_d s_  ght_factor_set(sw gCPtr, t , value);
  }

  publ c double getD s_  ght_factor() {
    return sw gfa ssJN .ReproduceD stancesObject ve_d s_  ght_factor_get(sw gCPtr, t );
  }

  publ c stat c double sqr(double x) {
    return sw gfa ssJN .ReproduceD stancesObject ve_sqr(x);
  }

  publ c double d s_  ght(double x) {
    return sw gfa ssJN .ReproduceD stancesObject ve_d s_  ght(sw gCPtr, t , x);
  }

  publ c vo d setS ce_d s(DoubleVector value) {
    sw gfa ssJN .ReproduceD stancesObject ve_s ce_d s_set(sw gCPtr, t , DoubleVector.getCPtr(value), value);
  }

  publ c DoubleVector getS ce_d s() {
    long cPtr = sw gfa ssJN .ReproduceD stancesObject ve_s ce_d s_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new DoubleVector(cPtr, false);
  }

  publ c vo d setTarget_d s(SW GTYPE_p_double value) {
    sw gfa ssJN .ReproduceD stancesObject ve_target_d s_set(sw gCPtr, t , SW GTYPE_p_double.getCPtr(value));
  }

  publ c SW GTYPE_p_double getTarget_d s() {
    long cPtr = sw gfa ssJN .ReproduceD stancesObject ve_target_d s_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_double(cPtr, false);
  }

  publ c vo d set  ghts(DoubleVector value) {
    sw gfa ssJN .ReproduceD stancesObject ve_  ghts_set(sw gCPtr, t , DoubleVector.getCPtr(value), value);
  }

  publ c DoubleVector get  ghts() {
    long cPtr = sw gfa ssJN .ReproduceD stancesObject ve_  ghts_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new DoubleVector(cPtr, false);
  }

  publ c double get_s ce_d s( nt  ,  nt j) {
    return sw gfa ssJN .ReproduceD stancesObject ve_get_s ce_d s(sw gCPtr, t ,  , j);
  }

  publ c double compute_cost(SW GTYPE_p_ nt perm) {
    return sw gfa ssJN .ReproduceD stancesObject ve_compute_cost(sw gCPtr, t , SW GTYPE_p_ nt.getCPtr(perm));
  }

  publ c double cost_update(SW GTYPE_p_ nt perm,  nt  w,  nt jw) {
    return sw gfa ssJN .ReproduceD stancesObject ve_cost_update(sw gCPtr, t , SW GTYPE_p_ nt.getCPtr(perm),  w, jw);
  }

  publ c ReproduceD stancesObject ve( nt n, SW GTYPE_p_double s ce_d s_ n, SW GTYPE_p_double target_d s_ n, double d s_  ght_factor) {
    t (sw gfa ssJN .new_ReproduceD stancesObject ve(n, SW GTYPE_p_double.getCPtr(s ce_d s_ n), SW GTYPE_p_double.getCPtr(target_d s_ n), d s_  ght_factor), true);
  }

  publ c stat c vo d compute_ an_stdev(SW GTYPE_p_double tab, long n2, SW GTYPE_p_double  an_out, SW GTYPE_p_double stddev_out) {
    sw gfa ssJN .ReproduceD stancesObject ve_compute_ an_stdev(SW GTYPE_p_double.getCPtr(tab), n2, SW GTYPE_p_double.getCPtr( an_out), SW GTYPE_p_double.getCPtr(stddev_out));
  }

  publ c vo d set_aff ne_target_d s(SW GTYPE_p_double s ce_d s_ n) {
    sw gfa ssJN .ReproduceD stancesObject ve_set_aff ne_target_d s(sw gCPtr, t , SW GTYPE_p_double.getCPtr(s ce_d s_ n));
  }

}
