/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c  nterface sw gfa ssConstants {
  publ c f nal stat c  nt FA SS_VERS ON_MAJOR = sw gfa ssJN .FA SS_VERS ON_MAJOR_get();
  publ c f nal stat c  nt FA SS_VERS ON_M NOR = sw gfa ssJN .FA SS_VERS ON_M NOR_get();
  publ c f nal stat c  nt FA SS_VERS ON_PATCH = sw gfa ssJN .FA SS_VERS ON_PATCH_get();
}
