/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class sw gfa ss  mple nts sw gfa ssConstants {
  publ c stat c vo d b vec_pr nt(SW GTYPE_p_uns gned_char b, long d) {
    sw gfa ssJN .b vec_pr nt(SW GTYPE_p_uns gned_char.getCPtr(b), d);
  }

  publ c stat c vo d fvecs2b vecs(SW GTYPE_p_float x, SW GTYPE_p_uns gned_char b, long d, long n) {
    sw gfa ssJN .fvecs2b vecs(SW GTYPE_p_float.getCPtr(x), SW GTYPE_p_uns gned_char.getCPtr(b), d, n);
  }

  publ c stat c vo d b vecs2fvecs(SW GTYPE_p_uns gned_char b, SW GTYPE_p_float x, long d, long n) {
    sw gfa ssJN .b vecs2fvecs(SW GTYPE_p_uns gned_char.getCPtr(b), SW GTYPE_p_float.getCPtr(x), d, n);
  }

  publ c stat c vo d fvec2b vec(SW GTYPE_p_float x, SW GTYPE_p_uns gned_char b, long d) {
    sw gfa ssJN .fvec2b vec(SW GTYPE_p_float.getCPtr(x), SW GTYPE_p_uns gned_char.getCPtr(b), d);
  }

  publ c stat c vo d b vec_shuffle(long n, long da, long db, SW GTYPE_p_ nt order, SW GTYPE_p_uns gned_char a, SW GTYPE_p_uns gned_char b) {
    sw gfa ssJN .b vec_shuffle(n, da, db, SW GTYPE_p_ nt.getCPtr(order), SW GTYPE_p_uns gned_char.getCPtr(a), SW GTYPE_p_uns gned_char.getCPtr(b));
  }

  publ c stat c vo d setHamm ng_batch_s ze(long value) {
    sw gfa ssJN .hamm ng_batch_s ze_set(value);
  }

  publ c stat c long getHamm ng_batch_s ze() {
    return sw gfa ssJN .hamm ng_batch_s ze_get();
  }

  publ c stat c  nt popcount64(long x) {
    return sw gfa ssJN .popcount64(x);
  }

  publ c stat c vo d hamm ngs(SW GTYPE_p_uns gned_char a, SW GTYPE_p_uns gned_char b, long na, long nb, long nbytespercode, SW GTYPE_p_ nt d s) {
    sw gfa ssJN .hamm ngs(SW GTYPE_p_uns gned_char.getCPtr(a), SW GTYPE_p_uns gned_char.getCPtr(b), na, nb, nbytespercode, SW GTYPE_p_ nt.getCPtr(d s));
  }

  publ c stat c vo d hamm ngs_knn_hc(SW GTYPE_p_fa ss__ apArrayT_fa ss__CMaxT_ nt_ nt64_t_t_t ha, SW GTYPE_p_uns gned_char a, SW GTYPE_p_uns gned_char b, long nb, long ncodes,  nt ordered) {
    sw gfa ssJN .hamm ngs_knn_hc(SW GTYPE_p_fa ss__ apArrayT_fa ss__CMaxT_ nt_ nt64_t_t_t.getCPtr(ha), SW GTYPE_p_uns gned_char.getCPtr(a), SW GTYPE_p_uns gned_char.getCPtr(b), nb, ncodes, ordered);
  }

  publ c stat c vo d hamm ngs_knn(SW GTYPE_p_fa ss__ apArrayT_fa ss__CMaxT_ nt_ nt64_t_t_t ha, SW GTYPE_p_uns gned_char a, SW GTYPE_p_uns gned_char b, long nb, long ncodes,  nt ordered) {
    sw gfa ssJN .hamm ngs_knn(SW GTYPE_p_fa ss__ apArrayT_fa ss__CMaxT_ nt_ nt64_t_t_t.getCPtr(ha), SW GTYPE_p_uns gned_char.getCPtr(a), SW GTYPE_p_uns gned_char.getCPtr(b), nb, ncodes, ordered);
  }

  publ c stat c vo d hamm ngs_knn_mc(SW GTYPE_p_uns gned_char a, SW GTYPE_p_uns gned_char b, long na, long nb, long k, long ncodes, SW GTYPE_p_ nt d stances, LongVector labels) {
    sw gfa ssJN .hamm ngs_knn_mc(SW GTYPE_p_uns gned_char.getCPtr(a), SW GTYPE_p_uns gned_char.getCPtr(b), na, nb, k, ncodes, SW GTYPE_p_ nt.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels);
  }

  publ c stat c vo d hamm ng_range_search(SW GTYPE_p_uns gned_char a, SW GTYPE_p_uns gned_char b, long na, long nb,  nt rad us, long ncodes, RangeSearchResult result) {
    sw gfa ssJN .hamm ng_range_search(SW GTYPE_p_uns gned_char.getCPtr(a), SW GTYPE_p_uns gned_char.getCPtr(b), na, nb, rad us, ncodes, RangeSearchResult.getCPtr(result), result);
  }

  publ c stat c vo d hamm ng_count_thres(SW GTYPE_p_uns gned_char bs1, SW GTYPE_p_uns gned_char bs2, long n1, long n2,  nt ht, long ncodes, SW GTYPE_p_uns gned_long nptr) {
    sw gfa ssJN .hamm ng_count_thres(SW GTYPE_p_uns gned_char.getCPtr(bs1), SW GTYPE_p_uns gned_char.getCPtr(bs2), n1, n2, ht, ncodes, SW GTYPE_p_uns gned_long.getCPtr(nptr));
  }

  publ c stat c long match_hamm ng_thres(SW GTYPE_p_uns gned_char bs1, SW GTYPE_p_uns gned_char bs2, long n1, long n2,  nt ht, long ncodes, LongVector  dx, SW GTYPE_p_ nt d s) {
    return sw gfa ssJN .match_hamm ng_thres(SW GTYPE_p_uns gned_char.getCPtr(bs1), SW GTYPE_p_uns gned_char.getCPtr(bs2), n1, n2, ht, ncodes, SW GTYPE_p_long_long.getCPtr( dx.data()),  dx, SW GTYPE_p_ nt.getCPtr(d s));
  }

  publ c stat c vo d crosshamm ng_count_thres(SW GTYPE_p_uns gned_char dbs, long n,  nt ht, long ncodes, SW GTYPE_p_uns gned_long nptr) {
    sw gfa ssJN .crosshamm ng_count_thres(SW GTYPE_p_uns gned_char.getCPtr(dbs), n, ht, ncodes, SW GTYPE_p_uns gned_long.getCPtr(nptr));
  }

  publ c stat c  nt get_num_gpus() {
    return sw gfa ssJN .get_num_gpus();
  }

  publ c stat c Str ng get_comp le_opt ons() {
    return sw gfa ssJN .get_comp le_opt ons();
  }

  publ c stat c double getm ll secs() {
    return sw gfa ssJN .getm ll secs();
  }

  publ c stat c long get_ m_usage_kb() {
    return sw gfa ssJN .get_ m_usage_kb();
  }

  publ c stat c long get_cycles() {
    return sw gfa ssJN .get_cycles();
  }

  publ c stat c vo d fvec_madd(long n, SW GTYPE_p_float a, float bf, SW GTYPE_p_float b, SW GTYPE_p_float c) {
    sw gfa ssJN .fvec_madd(n, SW GTYPE_p_float.getCPtr(a), bf, SW GTYPE_p_float.getCPtr(b), SW GTYPE_p_float.getCPtr(c));
  }

  publ c stat c  nt fvec_madd_and_argm n(long n, SW GTYPE_p_float a, float bf, SW GTYPE_p_float b, SW GTYPE_p_float c) {
    return sw gfa ssJN .fvec_madd_and_argm n(n, SW GTYPE_p_float.getCPtr(a), bf, SW GTYPE_p_float.getCPtr(b), SW GTYPE_p_float.getCPtr(c));
  }

  publ c stat c vo d reflect on(SW GTYPE_p_float u, SW GTYPE_p_float x, long n, long d, long nu) {
    sw gfa ssJN .reflect on(SW GTYPE_p_float.getCPtr(u), SW GTYPE_p_float.getCPtr(x), n, d, nu);
  }

  publ c stat c vo d matr x_qr( nt m,  nt n, SW GTYPE_p_float a) {
    sw gfa ssJN .matr x_qr(m, n, SW GTYPE_p_float.getCPtr(a));
  }

  publ c stat c vo d rankl st_handle_t es( nt k, LongVector  dx, SW GTYPE_p_float d s) {
    sw gfa ssJN .rankl st_handle_t es(k, SW GTYPE_p_long_long.getCPtr( dx.data()),  dx, SW GTYPE_p_float.getCPtr(d s));
  }

  publ c stat c long rankl st_ ntersect on_s ze(long k1, LongVector v1, long k2, LongVector v2) {
    return sw gfa ssJN .rankl st_ ntersect on_s ze(k1, SW GTYPE_p_long_long.getCPtr(v1.data()), v1, k2, SW GTYPE_p_long_long.getCPtr(v2.data()), v2);
  }

  publ c stat c long  rge_result_table_w h(long n, long k, LongVector  0, SW GTYPE_p_float D0, LongVector  1, SW GTYPE_p_float D1, boolean keep_m n, long translat on) {
    return sw gfa ssJN . rge_result_table_w h__SW G_0(n, k, SW GTYPE_p_long_long.getCPtr( 0.data()),  0, SW GTYPE_p_float.getCPtr(D0), SW GTYPE_p_long_long.getCPtr( 1.data()),  1, SW GTYPE_p_float.getCPtr(D1), keep_m n, translat on);
  }

  publ c stat c long  rge_result_table_w h(long n, long k, LongVector  0, SW GTYPE_p_float D0, LongVector  1, SW GTYPE_p_float D1, boolean keep_m n) {
    return sw gfa ssJN . rge_result_table_w h__SW G_1(n, k, SW GTYPE_p_long_long.getCPtr( 0.data()),  0, SW GTYPE_p_float.getCPtr(D0), SW GTYPE_p_long_long.getCPtr( 1.data()),  1, SW GTYPE_p_float.getCPtr(D1), keep_m n);
  }

  publ c stat c long  rge_result_table_w h(long n, long k, LongVector  0, SW GTYPE_p_float D0, LongVector  1, SW GTYPE_p_float D1) {
    return sw gfa ssJN . rge_result_table_w h__SW G_2(n, k, SW GTYPE_p_long_long.getCPtr( 0.data()),  0, SW GTYPE_p_float.getCPtr(D0), SW GTYPE_p_long_long.getCPtr( 1.data()),  1, SW GTYPE_p_float.getCPtr(D1));
  }

  publ c stat c double  mbalance_factor( nt n,  nt k, LongVector ass gn) {
    return sw gfa ssJN . mbalance_factor__SW G_0(n, k, SW GTYPE_p_long_long.getCPtr(ass gn.data()), ass gn);
  }

  publ c stat c double  mbalance_factor( nt k, SW GTYPE_p_ nt  t) {
    return sw gfa ssJN . mbalance_factor__SW G_1(k, SW GTYPE_p_ nt.getCPtr( t));
  }

  publ c stat c vo d fvec_argsort(long n, SW GTYPE_p_float vals, SW GTYPE_p_uns gned_long perm) {
    sw gfa ssJN .fvec_argsort(n, SW GTYPE_p_float.getCPtr(vals), SW GTYPE_p_uns gned_long.getCPtr(perm));
  }

  publ c stat c vo d fvec_argsort_parallel(long n, SW GTYPE_p_float vals, SW GTYPE_p_uns gned_long perm) {
    sw gfa ssJN .fvec_argsort_parallel(n, SW GTYPE_p_float.getCPtr(vals), SW GTYPE_p_uns gned_long.getCPtr(perm));
  }

  publ c stat c  nt  vec_ t(long n, SW GTYPE_p_ nt v,  nt vmax, SW GTYPE_p_ nt  t) {
    return sw gfa ssJN . vec_ t(n, SW GTYPE_p_ nt.getCPtr(v), vmax, SW GTYPE_p_ nt.getCPtr( t));
  }

  publ c stat c vo d b ncode_ t(long n, long nb s, SW GTYPE_p_uns gned_char codes, SW GTYPE_p_ nt  t) {
    sw gfa ssJN .b ncode_ t(n, nb s, SW GTYPE_p_uns gned_char.getCPtr(codes), SW GTYPE_p_ nt.getCPtr( t));
  }

  publ c stat c long  vec_c cksum(long n, SW GTYPE_p_ nt a) {
    return sw gfa ssJN . vec_c cksum(n, SW GTYPE_p_ nt.getCPtr(a));
  }

  publ c stat c SW GTYPE_p_float fvecs_maybe_subsample(long d, SW GTYPE_p_uns gned_long n, long nmax, SW GTYPE_p_float x, boolean verbose, long seed) {
    long cPtr = sw gfa ssJN .fvecs_maybe_subsample__SW G_0(d, SW GTYPE_p_uns gned_long.getCPtr(n), nmax, SW GTYPE_p_float.getCPtr(x), verbose, seed);
    return (cPtr == 0) ? null : new SW GTYPE_p_float(cPtr, false);
  }

  publ c stat c SW GTYPE_p_float fvecs_maybe_subsample(long d, SW GTYPE_p_uns gned_long n, long nmax, SW GTYPE_p_float x, boolean verbose) {
    long cPtr = sw gfa ssJN .fvecs_maybe_subsample__SW G_1(d, SW GTYPE_p_uns gned_long.getCPtr(n), nmax, SW GTYPE_p_float.getCPtr(x), verbose);
    return (cPtr == 0) ? null : new SW GTYPE_p_float(cPtr, false);
  }

  publ c stat c SW GTYPE_p_float fvecs_maybe_subsample(long d, SW GTYPE_p_uns gned_long n, long nmax, SW GTYPE_p_float x) {
    long cPtr = sw gfa ssJN .fvecs_maybe_subsample__SW G_2(d, SW GTYPE_p_uns gned_long.getCPtr(n), nmax, SW GTYPE_p_float.getCPtr(x));
    return (cPtr == 0) ? null : new SW GTYPE_p_float(cPtr, false);
  }

  publ c stat c vo d b nary_to_real(long d, SW GTYPE_p_uns gned_char x_ n, SW GTYPE_p_float x_out) {
    sw gfa ssJN .b nary_to_real(d, SW GTYPE_p_uns gned_char.getCPtr(x_ n), SW GTYPE_p_float.getCPtr(x_out));
  }

  publ c stat c vo d real_to_b nary(long d, SW GTYPE_p_float x_ n, SW GTYPE_p_uns gned_char x_out) {
    sw gfa ssJN .real_to_b nary(d, SW GTYPE_p_float.getCPtr(x_ n), SW GTYPE_p_uns gned_char.getCPtr(x_out));
  }

  publ c stat c long hash_bytes(SW GTYPE_p_uns gned_char bytes, long n) {
    return sw gfa ssJN .hash_bytes(SW GTYPE_p_uns gned_char.getCPtr(bytes), n);
  }

  publ c stat c boolean c ck_openmp() {
    return sw gfa ssJN .c ck_openmp();
  }

  publ c stat c float k ans_cluster ng(long d, long n, long k, SW GTYPE_p_float x, SW GTYPE_p_float centro ds) {
    return sw gfa ssJN .k ans_cluster ng(d, n, k, SW GTYPE_p_float.getCPtr(x), SW GTYPE_p_float.getCPtr(centro ds));
  }

  publ c stat c vo d set ndexPQ_stats( ndexPQStats value) {
    sw gfa ssJN . ndexPQ_stats_set( ndexPQStats.getCPtr(value), value);
  }

  publ c stat c  ndexPQStats get ndexPQ_stats() {
    long cPtr = sw gfa ssJN . ndexPQ_stats_get();
    return (cPtr == 0) ? null : new  ndexPQStats(cPtr, false);
  }

  publ c stat c vo d set ndex VF_stats( ndex VFStats value) {
    sw gfa ssJN . ndex VF_stats_set( ndex VFStats.getCPtr(value), value);
  }

  publ c stat c  ndex VFStats get ndex VF_stats() {
    long cPtr = sw gfa ssJN . ndex VF_stats_get();
    return (cPtr == 0) ? null : new  ndex VFStats(cPtr, false);
  }

  publ c stat c short[] getHamd s_tab_ham_bytes() {
    return sw gfa ssJN .hamd s_tab_ham_bytes_get();
  }

  publ c stat c  nt general zed_hamm ng_64(long a) {
    return sw gfa ssJN .general zed_hamm ng_64(a);
  }

  publ c stat c vo d general zed_hamm ngs_knn_hc(SW GTYPE_p_fa ss__ apArrayT_fa ss__CMaxT_ nt_ nt64_t_t_t ha, SW GTYPE_p_uns gned_char a, SW GTYPE_p_uns gned_char b, long nb, long code_s ze,  nt ordered) {
    sw gfa ssJN .general zed_hamm ngs_knn_hc__SW G_0(SW GTYPE_p_fa ss__ apArrayT_fa ss__CMaxT_ nt_ nt64_t_t_t.getCPtr(ha), SW GTYPE_p_uns gned_char.getCPtr(a), SW GTYPE_p_uns gned_char.getCPtr(b), nb, code_s ze, ordered);
  }

  publ c stat c vo d general zed_hamm ngs_knn_hc(SW GTYPE_p_fa ss__ apArrayT_fa ss__CMaxT_ nt_ nt64_t_t_t ha, SW GTYPE_p_uns gned_char a, SW GTYPE_p_uns gned_char b, long nb, long code_s ze) {
    sw gfa ssJN .general zed_hamm ngs_knn_hc__SW G_1(SW GTYPE_p_fa ss__ apArrayT_fa ss__CMaxT_ nt_ nt64_t_t_t.getCPtr(ha), SW GTYPE_p_uns gned_char.getCPtr(a), SW GTYPE_p_uns gned_char.getCPtr(b), nb, code_s ze);
  }

  publ c stat c vo d c ck_compat ble_for_ rge( ndex  ndex1,  ndex  ndex2) {
    sw gfa ssJN .c ck_compat ble_for_ rge( ndex.getCPtr( ndex1),  ndex1,  ndex.getCPtr( ndex2),  ndex2);
  }

  publ c stat c  ndex VF extract_ ndex_ vf( ndex  ndex) {
    long cPtr = sw gfa ssJN .extract_ ndex_ vf__SW G_0( ndex.getCPtr( ndex),  ndex);
    return (cPtr == 0) ? null : new  ndex VF(cPtr, false);
  }

  publ c stat c  ndex VF try_extract_ ndex_ vf( ndex  ndex) {
    long cPtr = sw gfa ssJN .try_extract_ ndex_ vf__SW G_0( ndex.getCPtr( ndex),  ndex);
    return (cPtr == 0) ? null : new  ndex VF(cPtr, false);
  }

  publ c stat c vo d  rge_ nto( ndex  ndex0,  ndex  ndex1, boolean sh ft_ ds) {
    sw gfa ssJN . rge_ nto( ndex.getCPtr( ndex0),  ndex0,  ndex.getCPtr( ndex1),  ndex1, sh ft_ ds);
  }

  publ c stat c vo d search_centro d( ndex  ndex, SW GTYPE_p_float x,  nt n, LongVector centro d_ ds) {
    sw gfa ssJN .search_centro d( ndex.getCPtr( ndex),  ndex, SW GTYPE_p_float.getCPtr(x), n, SW GTYPE_p_long_long.getCPtr(centro d_ ds.data()), centro d_ ds);
  }

  publ c stat c vo d search_and_return_centro ds( ndex  ndex, long n, SW GTYPE_p_float x n,  nt k, SW GTYPE_p_float d stances, LongVector labels, LongVector query_centro d_ ds, LongVector result_centro d_ ds) {
    sw gfa ssJN .search_and_return_centro ds( ndex.getCPtr( ndex),  ndex, n, SW GTYPE_p_float.getCPtr(x n), k, SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels, SW GTYPE_p_long_long.getCPtr(query_centro d_ ds.data()), query_centro d_ ds, SW GTYPE_p_long_long.getCPtr(result_centro d_ ds.data()), result_centro d_ ds);
  }

  publ c stat c Array nvertedL sts get_ nvl st_range( ndex  ndex,  nt  0,  nt  1) {
    long cPtr = sw gfa ssJN .get_ nvl st_range( ndex.getCPtr( ndex),  ndex,  0,  1);
    return (cPtr == 0) ? null : new Array nvertedL sts(cPtr, false);
  }

  publ c stat c vo d set_ nvl st_range( ndex  ndex,  nt  0,  nt  1, Array nvertedL sts src) {
    sw gfa ssJN .set_ nvl st_range( ndex.getCPtr( ndex),  ndex,  0,  1, Array nvertedL sts.getCPtr(src), src);
  }

  publ c stat c vo d search_w h_para ters( ndex  ndex, long n, SW GTYPE_p_float x, long k, SW GTYPE_p_float d stances, LongVector labels,  VFSearchPara ters params, SW GTYPE_p_uns gned_long nb_d s, SW GTYPE_p_double ms_per_stage) {
    sw gfa ssJN .search_w h_para ters__SW G_0( ndex.getCPtr( ndex),  ndex, n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels,  VFSearchPara ters.getCPtr(params), params, SW GTYPE_p_uns gned_long.getCPtr(nb_d s), SW GTYPE_p_double.getCPtr(ms_per_stage));
  }

  publ c stat c vo d search_w h_para ters( ndex  ndex, long n, SW GTYPE_p_float x, long k, SW GTYPE_p_float d stances, LongVector labels,  VFSearchPara ters params, SW GTYPE_p_uns gned_long nb_d s) {
    sw gfa ssJN .search_w h_para ters__SW G_1( ndex.getCPtr( ndex),  ndex, n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels,  VFSearchPara ters.getCPtr(params), params, SW GTYPE_p_uns gned_long.getCPtr(nb_d s));
  }

  publ c stat c vo d search_w h_para ters( ndex  ndex, long n, SW GTYPE_p_float x, long k, SW GTYPE_p_float d stances, LongVector labels,  VFSearchPara ters params) {
    sw gfa ssJN .search_w h_para ters__SW G_2( ndex.getCPtr( ndex),  ndex, n, SW GTYPE_p_float.getCPtr(x), k, SW GTYPE_p_float.getCPtr(d stances), SW GTYPE_p_long_long.getCPtr(labels.data()), labels,  VFSearchPara ters.getCPtr(params), params);
  }

  publ c stat c vo d range_search_w h_para ters( ndex  ndex, long n, SW GTYPE_p_float x, float rad us, RangeSearchResult result,  VFSearchPara ters params, SW GTYPE_p_uns gned_long nb_d s, SW GTYPE_p_double ms_per_stage) {
    sw gfa ssJN .range_search_w h_para ters__SW G_0( ndex.getCPtr( ndex),  ndex, n, SW GTYPE_p_float.getCPtr(x), rad us, RangeSearchResult.getCPtr(result), result,  VFSearchPara ters.getCPtr(params), params, SW GTYPE_p_uns gned_long.getCPtr(nb_d s), SW GTYPE_p_double.getCPtr(ms_per_stage));
  }

  publ c stat c vo d range_search_w h_para ters( ndex  ndex, long n, SW GTYPE_p_float x, float rad us, RangeSearchResult result,  VFSearchPara ters params, SW GTYPE_p_uns gned_long nb_d s) {
    sw gfa ssJN .range_search_w h_para ters__SW G_1( ndex.getCPtr( ndex),  ndex, n, SW GTYPE_p_float.getCPtr(x), rad us, RangeSearchResult.getCPtr(result), result,  VFSearchPara ters.getCPtr(params), params, SW GTYPE_p_uns gned_long.getCPtr(nb_d s));
  }

  publ c stat c vo d range_search_w h_para ters( ndex  ndex, long n, SW GTYPE_p_float x, float rad us, RangeSearchResult result,  VFSearchPara ters params) {
    sw gfa ssJN .range_search_w h_para ters__SW G_2( ndex.getCPtr( ndex),  ndex, n, SW GTYPE_p_float.getCPtr(x), rad us, RangeSearchResult.getCPtr(result), result,  VFSearchPara ters.getCPtr(params), params);
  }

  publ c stat c vo d setHnsw_stats(HNSWStats value) {
    sw gfa ssJN .hnsw_stats_set(HNSWStats.getCPtr(value), value);
  }

  publ c stat c HNSWStats getHnsw_stats() {
    long cPtr = sw gfa ssJN .hnsw_stats_get();
    return (cPtr == 0) ? null : new HNSWStats(cPtr, false);
  }

  publ c stat c vo d setPrecomputed_table_max_bytes(long value) {
    sw gfa ssJN .precomputed_table_max_bytes_set(value);
  }

  publ c stat c long getPrecomputed_table_max_bytes() {
    return sw gfa ssJN .precomputed_table_max_bytes_get();
  }

  publ c stat c vo d  n  al ze_ VFPQ_precomputed_table(SW GTYPE_p_ nt use_precomputed_table,  ndex quant zer, ProductQuant zer pq, SW GTYPE_p_Al gnedTableT_float_32_t precomputed_table, boolean verbose) {
    sw gfa ssJN . n  al ze_ VFPQ_precomputed_table(SW GTYPE_p_ nt.getCPtr(use_precomputed_table),  ndex.getCPtr(quant zer), quant zer, ProductQuant zer.getCPtr(pq), pq, SW GTYPE_p_Al gnedTableT_float_32_t.getCPtr(precomputed_table), verbose);
  }

  publ c stat c vo d set ndex VFPQ_stats( ndex VFPQStats value) {
    sw gfa ssJN . ndex VFPQ_stats_set( ndex VFPQStats.getCPtr(value), value);
  }

  publ c stat c  ndex VFPQStats get ndex VFPQ_stats() {
    long cPtr = sw gfa ssJN . ndex VFPQ_stats_get();
    return (cPtr == 0) ? null : new  ndex VFPQStats(cPtr, false);
  }

  publ c stat c  ndex downcast_ ndex( ndex  ndex) {
    long cPtr = sw gfa ssJN .downcast_ ndex( ndex.getCPtr( ndex),  ndex);
    return (cPtr == 0) ? null : new  ndex(cPtr, false);
  }

  publ c stat c VectorTransform downcast_VectorTransform(VectorTransform vt) {
    long cPtr = sw gfa ssJN .downcast_VectorTransform(VectorTransform.getCPtr(vt), vt);
    return (cPtr == 0) ? null : new VectorTransform(cPtr, false);
  }

  publ c stat c  ndexB nary downcast_ ndexB nary( ndexB nary  ndex) {
    long cPtr = sw gfa ssJN .downcast_ ndexB nary( ndexB nary.getCPtr( ndex),  ndex);
    return (cPtr == 0) ? null : new  ndexB nary(cPtr, false);
  }

  publ c stat c  ndex upcast_ ndexShards( ndexShards  ndex) {
    long cPtr = sw gfa ssJN .upcast_ ndexShards( ndexShards.getCPtr( ndex),  ndex);
    return (cPtr == 0) ? null : new  ndex(cPtr, false);
  }

  publ c stat c vo d wr e_ ndex( ndex  dx, Str ng fna ) {
    sw gfa ssJN .wr e_ ndex__SW G_0( ndex.getCPtr( dx),  dx, fna );
  }

  publ c stat c vo d wr e_ ndex( ndex  dx, SW GTYPE_p_F LE f) {
    sw gfa ssJN .wr e_ ndex__SW G_1( ndex.getCPtr( dx),  dx, SW GTYPE_p_F LE.getCPtr(f));
  }

  publ c stat c vo d wr e_ ndex( ndex  dx, SW GTYPE_p_fa ss__ OWr er wr er) {
    sw gfa ssJN .wr e_ ndex__SW G_2( ndex.getCPtr( dx),  dx, SW GTYPE_p_fa ss__ OWr er.getCPtr(wr er));
  }

  publ c stat c vo d wr e_ ndex_b nary( ndexB nary  dx, Str ng fna ) {
    sw gfa ssJN .wr e_ ndex_b nary__SW G_0( ndexB nary.getCPtr( dx),  dx, fna );
  }

  publ c stat c vo d wr e_ ndex_b nary( ndexB nary  dx, SW GTYPE_p_F LE f) {
    sw gfa ssJN .wr e_ ndex_b nary__SW G_1( ndexB nary.getCPtr( dx),  dx, SW GTYPE_p_F LE.getCPtr(f));
  }

  publ c stat c vo d wr e_ ndex_b nary( ndexB nary  dx, SW GTYPE_p_fa ss__ OWr er wr er) {
    sw gfa ssJN .wr e_ ndex_b nary__SW G_2( ndexB nary.getCPtr( dx),  dx, SW GTYPE_p_fa ss__ OWr er.getCPtr(wr er));
  }

  publ c stat c  nt get O_FLAG_READ_ONLY() {
    return sw gfa ssJN . O_FLAG_READ_ONLY_get();
  }

  publ c stat c  nt get O_FLAG_OND SK_SAME_D R() {
    return sw gfa ssJN . O_FLAG_OND SK_SAME_D R_get();
  }

  publ c stat c  nt get O_FLAG_SK P_ VF_DATA() {
    return sw gfa ssJN . O_FLAG_SK P_ VF_DATA_get();
  }

  publ c stat c  nt get O_FLAG_MMAP() {
    return sw gfa ssJN . O_FLAG_MMAP_get();
  }

  publ c stat c  ndex read_ ndex(Str ng fna ,  nt  o_flags) {
    long cPtr = sw gfa ssJN .read_ ndex__SW G_0(fna ,  o_flags);
    return (cPtr == 0) ? null : new  ndex(cPtr, true);
  }

  publ c stat c  ndex read_ ndex(Str ng fna ) {
    long cPtr = sw gfa ssJN .read_ ndex__SW G_1(fna );
    return (cPtr == 0) ? null : new  ndex(cPtr, true);
  }

  publ c stat c  ndex read_ ndex(SW GTYPE_p_F LE f,  nt  o_flags) {
    long cPtr = sw gfa ssJN .read_ ndex__SW G_2(SW GTYPE_p_F LE.getCPtr(f),  o_flags);
    return (cPtr == 0) ? null : new  ndex(cPtr, true);
  }

  publ c stat c  ndex read_ ndex(SW GTYPE_p_F LE f) {
    long cPtr = sw gfa ssJN .read_ ndex__SW G_3(SW GTYPE_p_F LE.getCPtr(f));
    return (cPtr == 0) ? null : new  ndex(cPtr, true);
  }

  publ c stat c  ndex read_ ndex(SW GTYPE_p_fa ss__ OReader reader,  nt  o_flags) {
    long cPtr = sw gfa ssJN .read_ ndex__SW G_4(SW GTYPE_p_fa ss__ OReader.getCPtr(reader),  o_flags);
    return (cPtr == 0) ? null : new  ndex(cPtr, true);
  }

  publ c stat c  ndex read_ ndex(SW GTYPE_p_fa ss__ OReader reader) {
    long cPtr = sw gfa ssJN .read_ ndex__SW G_5(SW GTYPE_p_fa ss__ OReader.getCPtr(reader));
    return (cPtr == 0) ? null : new  ndex(cPtr, true);
  }

  publ c stat c  ndexB nary read_ ndex_b nary(Str ng fna ,  nt  o_flags) {
    long cPtr = sw gfa ssJN .read_ ndex_b nary__SW G_0(fna ,  o_flags);
    return (cPtr == 0) ? null : new  ndexB nary(cPtr, true);
  }

  publ c stat c  ndexB nary read_ ndex_b nary(Str ng fna ) {
    long cPtr = sw gfa ssJN .read_ ndex_b nary__SW G_1(fna );
    return (cPtr == 0) ? null : new  ndexB nary(cPtr, true);
  }

  publ c stat c  ndexB nary read_ ndex_b nary(SW GTYPE_p_F LE f,  nt  o_flags) {
    long cPtr = sw gfa ssJN .read_ ndex_b nary__SW G_2(SW GTYPE_p_F LE.getCPtr(f),  o_flags);
    return (cPtr == 0) ? null : new  ndexB nary(cPtr, true);
  }

  publ c stat c  ndexB nary read_ ndex_b nary(SW GTYPE_p_F LE f) {
    long cPtr = sw gfa ssJN .read_ ndex_b nary__SW G_3(SW GTYPE_p_F LE.getCPtr(f));
    return (cPtr == 0) ? null : new  ndexB nary(cPtr, true);
  }

  publ c stat c  ndexB nary read_ ndex_b nary(SW GTYPE_p_fa ss__ OReader reader,  nt  o_flags) {
    long cPtr = sw gfa ssJN .read_ ndex_b nary__SW G_4(SW GTYPE_p_fa ss__ OReader.getCPtr(reader),  o_flags);
    return (cPtr == 0) ? null : new  ndexB nary(cPtr, true);
  }

  publ c stat c  ndexB nary read_ ndex_b nary(SW GTYPE_p_fa ss__ OReader reader) {
    long cPtr = sw gfa ssJN .read_ ndex_b nary__SW G_5(SW GTYPE_p_fa ss__ OReader.getCPtr(reader));
    return (cPtr == 0) ? null : new  ndexB nary(cPtr, true);
  }

  publ c stat c vo d wr e_VectorTransform(VectorTransform vt, Str ng fna ) {
    sw gfa ssJN .wr e_VectorTransform(VectorTransform.getCPtr(vt), vt, fna );
  }

  publ c stat c VectorTransform read_VectorTransform(Str ng fna ) {
    long cPtr = sw gfa ssJN .read_VectorTransform(fna );
    return (cPtr == 0) ? null : new VectorTransform(cPtr, true);
  }

  publ c stat c ProductQuant zer read_ProductQuant zer(Str ng fna ) {
    long cPtr = sw gfa ssJN .read_ProductQuant zer__SW G_0(fna );
    return (cPtr == 0) ? null : new ProductQuant zer(cPtr, true);
  }

  publ c stat c ProductQuant zer read_ProductQuant zer(SW GTYPE_p_fa ss__ OReader reader) {
    long cPtr = sw gfa ssJN .read_ProductQuant zer__SW G_1(SW GTYPE_p_fa ss__ OReader.getCPtr(reader));
    return (cPtr == 0) ? null : new ProductQuant zer(cPtr, true);
  }

  publ c stat c vo d wr e_ProductQuant zer(ProductQuant zer pq, Str ng fna ) {
    sw gfa ssJN .wr e_ProductQuant zer__SW G_0(ProductQuant zer.getCPtr(pq), pq, fna );
  }

  publ c stat c vo d wr e_ProductQuant zer(ProductQuant zer pq, SW GTYPE_p_fa ss__ OWr er f) {
    sw gfa ssJN .wr e_ProductQuant zer__SW G_1(ProductQuant zer.getCPtr(pq), pq, SW GTYPE_p_fa ss__ OWr er.getCPtr(f));
  }

  publ c stat c vo d wr e_ nvertedL sts( nvertedL sts  ls, SW GTYPE_p_fa ss__ OWr er f) {
    sw gfa ssJN .wr e_ nvertedL sts( nvertedL sts.getCPtr( ls),  ls, SW GTYPE_p_fa ss__ OWr er.getCPtr(f));
  }

  publ c stat c  nvertedL sts read_ nvertedL sts(SW GTYPE_p_fa ss__ OReader reader,  nt  o_flags) {
    long cPtr = sw gfa ssJN .read_ nvertedL sts__SW G_0(SW GTYPE_p_fa ss__ OReader.getCPtr(reader),  o_flags);
    return (cPtr == 0) ? null : new  nvertedL sts(cPtr, false);
  }

  publ c stat c  nvertedL sts read_ nvertedL sts(SW GTYPE_p_fa ss__ OReader reader) {
    long cPtr = sw gfa ssJN .read_ nvertedL sts__SW G_1(SW GTYPE_p_fa ss__ OReader.getCPtr(reader));
    return (cPtr == 0) ? null : new  nvertedL sts(cPtr, false);
  }

  publ c stat c  ndex  ndex_factory( nt d, Str ng descr pt on,  tr cType  tr c) {
    long cPtr = sw gfa ssJN . ndex_factory__SW G_0(d, descr pt on,  tr c.sw gValue());
    return (cPtr == 0) ? null : new  ndex(cPtr, true);
  }

  publ c stat c  ndex  ndex_factory( nt d, Str ng descr pt on) {
    long cPtr = sw gfa ssJN . ndex_factory__SW G_1(d, descr pt on);
    return (cPtr == 0) ? null : new  ndex(cPtr, true);
  }

  publ c stat c vo d set ndex_factory_verbose( nt value) {
    sw gfa ssJN . ndex_factory_verbose_set(value);
  }

  publ c stat c  nt get ndex_factory_verbose() {
    return sw gfa ssJN . ndex_factory_verbose_get();
  }

  publ c stat c  ndexB nary  ndex_b nary_factory( nt d, Str ng descr pt on) {
    long cPtr = sw gfa ssJN . ndex_b nary_factory(d, descr pt on);
    return (cPtr == 0) ? null : new  ndexB nary(cPtr, true);
  }

  publ c stat c vo d s md_ togram_8(SW GTYPE_p_u nt16_t data,  nt n, SW GTYPE_p_u nt16_t m n,  nt sh ft, SW GTYPE_p_ nt  t) {
    sw gfa ssJN .s md_ togram_8(SW GTYPE_p_u nt16_t.getCPtr(data), n, SW GTYPE_p_u nt16_t.getCPtr(m n), sh ft, SW GTYPE_p_ nt.getCPtr( t));
  }

  publ c stat c vo d s md_ togram_16(SW GTYPE_p_u nt16_t data,  nt n, SW GTYPE_p_u nt16_t m n,  nt sh ft, SW GTYPE_p_ nt  t) {
    sw gfa ssJN .s md_ togram_16(SW GTYPE_p_u nt16_t.getCPtr(data), n, SW GTYPE_p_u nt16_t.getCPtr(m n), sh ft, SW GTYPE_p_ nt.getCPtr( t));
  }

  publ c stat c vo d setPart  on_stats(Part  onStats value) {
    sw gfa ssJN .part  on_stats_set(Part  onStats.getCPtr(value), value);
  }

  publ c stat c Part  onStats getPart  on_stats() {
    long cPtr = sw gfa ssJN .part  on_stats_get();
    return (cPtr == 0) ? null : new Part  onStats(cPtr, false);
  }

  publ c stat c float CM n_float_part  on_fuzzy(SW GTYPE_p_float vals, LongVector  ds, long n, long q_m n, long q_max, SW GTYPE_p_uns gned_long q_out) {
    return sw gfa ssJN .CM n_float_part  on_fuzzy(SW GTYPE_p_float.getCPtr(vals), SW GTYPE_p_long_long.getCPtr( ds.data()),  ds, n, q_m n, q_max, SW GTYPE_p_uns gned_long.getCPtr(q_out));
  }

  publ c stat c float CMax_float_part  on_fuzzy(SW GTYPE_p_float vals, LongVector  ds, long n, long q_m n, long q_max, SW GTYPE_p_uns gned_long q_out) {
    return sw gfa ssJN .CMax_float_part  on_fuzzy(SW GTYPE_p_float.getCPtr(vals), SW GTYPE_p_long_long.getCPtr( ds.data()),  ds, n, q_m n, q_max, SW GTYPE_p_uns gned_long.getCPtr(q_out));
  }

  publ c stat c SW GTYPE_p_u nt16_t CMax_u nt16_part  on_fuzzy(SW GTYPE_p_u nt16_t vals, LongVector  ds, long n, long q_m n, long q_max, SW GTYPE_p_uns gned_long q_out) {
    return new SW GTYPE_p_u nt16_t(sw gfa ssJN .CMax_u nt16_part  on_fuzzy__SW G_0(SW GTYPE_p_u nt16_t.getCPtr(vals), SW GTYPE_p_long_long.getCPtr( ds.data()),  ds, n, q_m n, q_max, SW GTYPE_p_uns gned_long.getCPtr(q_out)), true);
  }

  publ c stat c SW GTYPE_p_u nt16_t CM n_u nt16_part  on_fuzzy(SW GTYPE_p_u nt16_t vals, LongVector  ds, long n, long q_m n, long q_max, SW GTYPE_p_uns gned_long q_out) {
    return new SW GTYPE_p_u nt16_t(sw gfa ssJN .CM n_u nt16_part  on_fuzzy__SW G_0(SW GTYPE_p_u nt16_t.getCPtr(vals), SW GTYPE_p_long_long.getCPtr( ds.data()),  ds, n, q_m n, q_max, SW GTYPE_p_uns gned_long.getCPtr(q_out)), true);
  }

  publ c stat c SW GTYPE_p_u nt16_t CMax_u nt16_part  on_fuzzy(SW GTYPE_p_u nt16_t vals, SW GTYPE_p_ nt  ds, long n, long q_m n, long q_max, SW GTYPE_p_uns gned_long q_out) {
    return new SW GTYPE_p_u nt16_t(sw gfa ssJN .CMax_u nt16_part  on_fuzzy__SW G_1(SW GTYPE_p_u nt16_t.getCPtr(vals), SW GTYPE_p_ nt.getCPtr( ds), n, q_m n, q_max, SW GTYPE_p_uns gned_long.getCPtr(q_out)), true);
  }

  publ c stat c SW GTYPE_p_u nt16_t CM n_u nt16_part  on_fuzzy(SW GTYPE_p_u nt16_t vals, SW GTYPE_p_ nt  ds, long n, long q_m n, long q_max, SW GTYPE_p_uns gned_long q_out) {
    return new SW GTYPE_p_u nt16_t(sw gfa ssJN .CM n_u nt16_part  on_fuzzy__SW G_1(SW GTYPE_p_u nt16_t.getCPtr(vals), SW GTYPE_p_ nt.getCPtr( ds), n, q_m n, q_max, SW GTYPE_p_uns gned_long.getCPtr(q_out)), true);
  }

  publ c stat c vo d omp_set_num_threads( nt num_threads) {
    sw gfa ssJN .omp_set_num_threads(num_threads);
  }

  publ c stat c  nt omp_get_max_threads() {
    return sw gfa ssJN .omp_get_max_threads();
  }

  publ c stat c SW GTYPE_p_vo d  mcpy(SW GTYPE_p_vo d dest, SW GTYPE_p_vo d src, long n) {
    long cPtr = sw gfa ssJN . mcpy(SW GTYPE_p_vo d.getCPtr(dest), SW GTYPE_p_vo d.getCPtr(src), n);
    return (cPtr == 0) ? null : new SW GTYPE_p_vo d(cPtr, false);
  }

  publ c stat c SW GTYPE_p_float cast_ nteger_to_float_ptr( nt x) {
    long cPtr = sw gfa ssJN .cast_ nteger_to_float_ptr(x);
    return (cPtr == 0) ? null : new SW GTYPE_p_float(cPtr, false);
  }

  publ c stat c SW GTYPE_p_long cast_ nteger_to_long_ptr( nt x) {
    long cPtr = sw gfa ssJN .cast_ nteger_to_long_ptr(x);
    return (cPtr == 0) ? null : new SW GTYPE_p_long(cPtr, false);
  }

  publ c stat c SW GTYPE_p_ nt cast_ nteger_to_ nt_ptr( nt x) {
    long cPtr = sw gfa ssJN .cast_ nteger_to_ nt_ptr(x);
    return (cPtr == 0) ? null : new SW GTYPE_p_ nt(cPtr, false);
  }

  publ c stat c vo d  gnore_S GTT N() {
    sw gfa ssJN . gnore_S GTT N();
  }

}
