/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class SW GTYPE_p_fa ss__Al gnedTableT ghtAllocT_uns gned_char_32_t {
  pr vate trans ent long sw gCPtr;

  protected SW GTYPE_p_fa ss__Al gnedTableT ghtAllocT_uns gned_char_32_t(long cPtr, @SuppressWarn ngs("unused") boolean futureUse) {
    sw gCPtr = cPtr;
  }

  protected SW GTYPE_p_fa ss__Al gnedTableT ghtAllocT_uns gned_char_32_t() {
    sw gCPtr = 0;
  }

  protected stat c long getCPtr(SW GTYPE_p_fa ss__Al gnedTableT ghtAllocT_uns gned_char_32_t obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }
}

