/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class U nt64Vector {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected U nt64Vector(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(U nt64Vector obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_U nt64Vector(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c U nt64Vector() {
    t (sw gfa ssJN .new_U nt64Vector(), true);
  }

  publ c vo d push_back(long arg0) {
    sw gfa ssJN .U nt64Vector_push_back(sw gCPtr, t , arg0);
  }

  publ c vo d clear() {
    sw gfa ssJN .U nt64Vector_clear(sw gCPtr, t );
  }

  publ c SW GTYPE_p_uns gned_long data() {
    long cPtr = sw gfa ssJN .U nt64Vector_data(sw gCPtr, t );
    return (cPtr == 0) ? null : new SW GTYPE_p_uns gned_long(cPtr, false);
  }

  publ c long s ze() {
    return sw gfa ssJN .U nt64Vector_s ze(sw gCPtr, t );
  }

  publ c long at(long n) {
    return sw gfa ssJN .U nt64Vector_at(sw gCPtr, t , n);
  }

  publ c vo d res ze(long n) {
    sw gfa ssJN .U nt64Vector_res ze(sw gCPtr, t , n);
  }

  publ c vo d reserve(long n) {
    sw gfa ssJN .U nt64Vector_reserve(sw gCPtr, t , n);
  }

  publ c vo d swap(U nt64Vector ot r) {
    sw gfa ssJN .U nt64Vector_swap(sw gCPtr, t , U nt64Vector.getCPtr(ot r), ot r);
  }

}
