/* ----------------------------------------------------------------------------
 * T  f le was automat cally generated by SW G (http://www.sw g.org).
 * Vers on 4.0.2
 *
 * Do not make changes to t  f le unless   know what   are do ng--mod fy
 * t  SW G  nterface f le  nstead.
 * ----------------------------------------------------------------------------- */

package com.tw ter.ann.fa ss;

publ c class V s edTable {
  pr vate trans ent long sw gCPtr;
  protected trans ent boolean sw gC mOwn;

  protected V s edTable(long cPtr, boolean c moryOwn) {
    sw gC mOwn = c moryOwn;
    sw gCPtr = cPtr;
  }

  protected stat c long getCPtr(V s edTable obj) {
    return (obj == null) ? 0 : obj.sw gCPtr;
  }

  @SuppressWarn ngs("deprecat on")
  protected vo d f nal ze() {
    delete();
  }

  publ c synchron zed vo d delete() {
     f (sw gCPtr != 0) {
       f (sw gC mOwn) {
        sw gC mOwn = false;
        sw gfa ssJN .delete_V s edTable(sw gCPtr);
      }
      sw gCPtr = 0;
    }
  }

  publ c vo d setV s ed(ByteVector value) {
    sw gfa ssJN .V s edTable_v s ed_set(sw gCPtr, t , ByteVector.getCPtr(value), value);
  }

  publ c ByteVector getV s ed() {
    long cPtr = sw gfa ssJN .V s edTable_v s ed_get(sw gCPtr, t );
    return (cPtr == 0) ? null : new ByteVector(cPtr, false);
  }

  publ c vo d setV sno( nt value) {
    sw gfa ssJN .V s edTable_v sno_set(sw gCPtr, t , value);
  }

  publ c  nt getV sno() {
    return sw gfa ssJN .V s edTable_v sno_get(sw gCPtr, t );
  }

  publ c V s edTable( nt s ze) {
    t (sw gfa ssJN .new_V s edTable(s ze), true);
  }

  publ c vo d set( nt no) {
    sw gfa ssJN .V s edTable_set(sw gCPtr, t , no);
  }

  publ c boolean get( nt no) {
    return sw gfa ssJN .V s edTable_get(sw gCPtr, t , no);
  }

  publ c vo d advance() {
    sw gfa ssJN .V s edTable_advance(sw gCPtr, t );
  }

}
