enable_recom ndat ons:
  com nt: Proport on of requests w re   return an actual response as part. Decreas ng t  value w ll  ncrease t  port on of empty responses ( n order to d sable t  serv ce) as part of t  graceful degradat on.
  default_ava lab l y: 10000
enable_score_user_cand dates:
  com nt: Proport on of requests w re score user cand dates from t  scoreUserCand dates endpo nt
  default_ava lab l y: 10000
enable_prof le_s debar_product:
  com nt: Proport on of requests w re   return an actual response for prof le s debar product
  default_ava lab l y: 10000
enable_mag c_recs_product:
  com nt: Proport on of requests w re   return an actual response for mag c recs product
  default_ava lab l y: 10000
enable_rux_land ng_page_product:
  com nt: Proport on of requests w re   return an actual response for rux land ng page product
  default_ava lab l y: 10000
enable_rux_pymk_product:
  com nt: Proport on of requests w re   return an actual response for rux pymk product
  default_ava lab l y: 10000
enable_prof le_bonus_follow_product:
  com nt: Proport on of requests w re   return an actual response for prof le bonus follow product
  default_ava lab l y: 10000
enable_elect on_explore_wtf_product:
  com nt: Proport on of requests w re   return an actual response for elect on explore wtf product
  default_ava lab l y: 10000
enable_cluster_follow_product:
  com nt: Proport on of requests w re   return an actual response for cluster follow product
  default_ava lab l y: 10000
enable_ho _t  l ne_product:
  com nt: Proport on of requests w re   return an actual response for htl wtf product
  default_ava lab l y: 10000
enable_htl_bonus_follow_product:
  com nt: Proport on of requests w re   return an actual response for htl bonus follow product
  default_ava lab l y: 10000
enable_explore_tab_product:
  com nt: Proport on of requests w re   return an actual response for explore tab product
  default_ava lab l y: 10000
enable_s debar_product:
  com nt: Proport on of requests w re   return an actual response for s debar product
  default_ava lab l y: 10000
enable_campa gn_form_product:
  com nt: Proport on of requests w re   return an actual response for campa gn form product
  default_ava lab l y: 10000
enable_react ve_follow_product:
  com nt: Proport on of requests w re   return an actual response for react ve follow product
  default_ava lab l y: 10000
enable_nux_pymk_product:
  com nt: Proport on of requests w re   return an actual response for nux pymk product
  default_ava lab l y: 10000
enable_nux_ nterests_product:
  com nt: Proport on of requests w re   return an actual response for nux  nterests product
  default_ava lab l y: 10000
enable_nux_top c_bonus_follow_product:
  com nt: Proport on of requests w re   return an actual response for nux top c-based bonus follow product
  default_ava lab l y: 10000
enable_ nd a_cov d19_curated_accounts_wtf_product:
  com nt: Proport on of requests w re   return an actual response for  nd a cov d19 curated accounts wtf product
  default_ava lab l y: 10000
enable_ab_upload_product:
  com nt: Proport on of requests w re   return an actual response for t  address book upload product
  default_ava lab l y: 10000
enable_people_plus_plus_product:
  com nt: Proport on of requests w re   return an actual response for t  PeoplePlusPlus/Connect Tab product
  default_ava lab l y: 10000
enable_t et_not f cat on_recs_product:
  com nt: Proport on of requests w re   return an actual response for t  T et Not f cat on Recom ndat ons product
  default_ava lab l y: 10000
enable_prof le_dev ce_follow_product:
  com nt: Proport on of requests w re   return an actual response for t  Prof leDev ceFollow product
  default_ava lab l y: 10000
enable_d ffy_module_dark_read ng:
  com nt: Percentage of dark read traff c routed to d ffy thr ft
  default_ava lab l y: 0
enable_recos_backf ll_product:
  com nt: Proport on of requests w re   return an actual response for t  RecosBackf ll product
  default_ava lab l y: 10000
enable_post_nux_follow_task_product:
  com nt: Proport on of requests w re   return an actual response for post NUX follow task product
  default_ava lab l y: 10000
enable_curated_space_hosts_product:
  com nt: Proport on of requests w re   return an actual response for curated space hosts product
  default_ava lab l y: 10000
enable_nux_geo_category_product:
  com nt: Proport on of requests w re   return an actual response for nux geo category product
  default_ava lab l y: 10000
enable_nux_ nterests_category_product:
  com nt: Proport on of requests w re   return an actual response for nux  nterests category product
  default_ava lab l y: 10000
enable_nux_pymk_category_product:
  com nt: Proport on of requests w re   return an actual response for nux pymk category product
  default_ava lab l y: 10000
enable_ho _t  l ne_t et_recs_product:
  com nt: Proport on of requests w re   return an actual response for t  Ho  T  l ne T et Recs product
  default_ava lab l y: 10000
enable_htl_bulk_fr end_follows_product:
  com nt: Proport on of requests w re   return an actual response for t  HTL bulk fr end follows product
  default_ava lab l y: 10000
enable_nux_auto_follow_product:
  com nt: Proport on of requests w re   return an actual response for t  NUX auto follow product
  default_ava lab l y: 10000
enable_search_bonus_follow_product:
  com nt: Proport on of requests w re   return an actual response for search bonus follow product
  default_ava lab l y: 10000
enable_fetch_user_ n_request_bu lder:
  com nt: Proport on of requests w re   fetch user object from g zmoduck  n request bu lder
  default_ava lab l y: 0
enable_product_m xer_mag c_recs_product:
  com nt: Proport on of requests w re   enable t  product m xer mag c recs product
  default_ava lab l y: 10000
enable_ho _t  l ne_reverse_chron_product:
  com nt: Proport on of requests w re   return an actual response for Ho  t  l ne reverse chron product
  default_ava lab l y: 10000
enable_product_m xer_p pel ne_mag c_recs_dark_read:
  com nt: Compare product m xer p pel ne responses to current FRS p pel ne responses for Mag c Recs
  default_ava lab l y: 0
enable_exper  ntal_cach ng:
  com nt: Proport on of requests   use exper  ntal cach ng for data cach ng
  default_ava lab l y: 0
enable_d str buted_cach ng:
  com nt: Proport on of requests   use a d str buted cac  cluster for data cach ng
  default_ava lab l y: 10000
enable_g zmoduck_cach ng:
  com nt: Proport on of requests   use a d str buted cac  cluster for data cach ng  n G zmoduck
  default_ava lab l y: 10000
enable_traff c_dark_read ng:
  com nt: Proport on of requests w re   repl cate t  request for traff c dark read ng
  default_ava lab l y: 0
enable_graph_feature_serv ce_requests:
  com nt: Proport on of requests w re   allow request calls to Graph Feature Serv ce
  default_ava lab l y: 10000
