#":mlwf_l bs",

python37_b nary(
    na  = "eval_model",
    s ce = "eval_model.py",
    dependenc es = [
        ":l bs",
        "3rdparty/python/_closures/fr gate/fr gate-pushserv ce-opens ce/src/ma n/python/models/l ght_rank ng:eval_model",
    ],
)

python37_b nary(
    na  = "tra n_model",
    s ce = "deep_norm.py",
    dependenc es = [
        ":l bs",
        "3rdparty/python/_closures/fr gate/fr gate-pushserv ce-opens ce/src/ma n/python/models/l ght_rank ng:tra n_model",
    ],
)

python37_b nary(
    na  = "tra n_model_local",
    s ce = "deep_norm.py",
    dependenc es = [
        ":l bs",
        "3rdparty/python/_closures/fr gate/fr gate-pushserv ce-opens ce/src/ma n/python/models/l ght_rank ng:tra n_model_local",
        "twml",
    ],
)

python37_b nary(
    na  = "eval_model_local",
    s ce = "eval_model.py",
    dependenc es = [
        ":l bs",
        "3rdparty/python/_closures/fr gate/fr gate-pushserv ce-opens ce/src/ma n/python/models/l ght_rank ng:eval_model_local",
        "twml",
    ],
)

python37_b nary(
    na  = "mlwf_model",
    s ce = "deep_norm.py",
    dependenc es = [
        ":mlwf_l bs",
        "3rdparty/python/_closures/fr gate/fr gate-pushserv ce-opens ce/src/ma n/python/models/l ght_rank ng:mlwf_model",
    ],
)

python3_l brary(
    na  = "l bs",
    s ces = ["**/*.py"],
    tags = ["no- py"],
    dependenc es = [
        "src/python/tw ter/deepb rd/projects/mag c_recs/l bs",
        "src/python/tw ter/deepb rd/ut l/data",
        "twml:twml-nodeps",
    ],
)

python3_l brary(
    na  = "mlwf_l bs",
    s ces = ["**/*.py"],
    tags = ["no- py"],
    dependenc es = [
        "src/python/tw ter/deepb rd/projects/mag c_recs/l bs",
        "twml",
    ],
)
