java_l brary(
    s ces = ["*.java"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/code/f ndbugs:jsr305",
        "dec der/src/ma n/scala",
        "src/java/com/tw ter/search/common/dec der",
        "src/java/com/tw ter/search/common/relevance:ent  es_and_f lters",
        "ut l/ut l-core:scala",
    ],
)
