scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "ann/src/ma n/scala/com/tw ter/ann/fa ss",
        "ann/src/ma n/scala/com/tw ter/ann/hnsw",
        "tw ter-server- nternal/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)
