scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        " rm / rm -core/src/ma n/scala/com/tw ter/ rm /pred cate/soc algraph",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/scala/com/tw ter/tw stly/common",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
        "src/thr ft/com/tw ter/soc algraph:thr ft-scala",
        "user-s gnal-serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
        "ut l/ut l-core:ut l-core-ut l",
        "ut l/ut l-core/src/ma n/java/com/tw ter/ut l",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)
