scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "src/java/com/tw ter/ml/ap :ap -base",
        "src/scala/com/tw ter/ml/ap /ut l:datarecord",
        "src/thr ft/com/tw ter/dal/personal_data:personal_data-java",
        "src/thr ft/com/tw ter/ml/ap :data-java",
        "src/thr ft/com/tw ter/ml/ap :data-scala",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "src/thr ft/com/tw ter/dal/personal_data:personal_data-java",
        "src/thr ft/com/tw ter/ml/ap :data-java",
        "src/thr ft/com/tw ter/ml/ap :data-scala",
    ],
)
