scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/algeb rd:core",
        "beam- nternal/src/ma n/scala/com/tw ter/beam/ o/dal",
        "beam- nternal/src/ma n/scala/com/tw ter/sc o_ nternal/job",
        "beam- nternal/src/ma n/scala/com/tw ter/sc o_ nternal/runner/dataflow",
        "flockdb-tools/datasets/flock/src/ma n/thr ft:thr ft-scala",
        "src/scala/com/tw ter/pluck/s ce/comb ned_user_scrooge_s ce",
        "src/thr ft/com/tw ter/g zmoduck:user-thr ft-scala",
        "src/thr ft/com/tw ter/ nteract on_graph: nteract on_graph-scala",
        "src/thr ft/com/tw ter/soc algraph:thr ft-scala",
        "src/thr ft/com/tw ter/twadoop/user/gen:gen-scala",
        "src/thr ft/com/tw ter/user_sess on_store:thr ft-scala",
        "users ce/snapshot/src/ma n/scala/com/tw ter/users ce/snapshot/flat:users ce_flat-scala",
    ],
)

scala_l brary(
    na  = "feature_groups",
    s ces = ["FeatureGroups.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "src/thr ft/com/tw ter/ nteract on_graph: nteract on_graph-scala",
    ],
)
