scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        " d aserv ces/commons/src/ma n/thr ft:thr ft-scala",
        "t etyp e/servo/ut l",
        "snowflake: d",
        "src/thr ft/com/tw ter/g zmoduck:thr ft-scala",
        "src/thr ft/com/tw ter/g zmoduck:user-thr ft-scala",
        "t etyp e/common/src/thr ft/com/tw ter/t etyp e: d a-ent y-scala",
        "t etyp e/common/src/thr ft/com/tw ter/t etyp e:t et-scala",
        "t etyp e/server/src/ma n/thr ft:comp led-scala",
        "t etyp e/common/src/scala/com/tw ter/t etyp e/ut l",
        "ut l/ut l-slf4j-ap ",
    ],
)
