# Java l brary for t et features and ut l  es.
java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/com/google/ nject:gu ce",
        "3rdparty/jvm/com/tw ter/elephantb rd:core",
        "3rdparty/jvm/org/apac /hadoop:hadoop-cl ent-default",
        "3rdparty/jvm/org/apac /thr ft:l bthr ft",
        "src/java/com/tw ter/common/base",
        "src/java/com/tw ter/common/text/token",
        "src/java/com/tw ter/search/common/encod ng/features",
        "src/java/com/tw ter/search/common/features",
        "src/java/com/tw ter/search/common/ tr cs",
        "src/java/com/tw ter/search/common/sc ma/base",
        "src/java/com/tw ter/search/common/sc ma/earlyb rd",
        "src/java/com/tw ter/search/common/ut l/lang",
        "src/thr ft/com/tw ter/search/common:constants-java",
        "src/thr ft/com/tw ter/search/common:features-java",
        "src/thr ft/com/tw ter/search/common:sc ma-java",
    ],
)
