enableLogFavBasedApeEnt y20M145KUpdatedEmbedd ngCac dStore:
  com nt: "Enable to use t  non-empty store for logFavBasedApeEnt y20M145KUpdatedEmbedd ngCac dStore (from 0% to 100%). 0  ans use EMPTY readable store for all requests."
  default_ava lab l y: 0

enableLogFavBasedApeEnt y20M145K2020Embedd ngCac dStore:
  com nt: "Enable to use t  non-empty store for logFavBasedApeEnt y20M145K2020Embedd ngCac dStore (from 0% to 100%). 0  ans use EMPTY readable store for all requests."
  default_ava lab l y: 0

representat on-scorer_forward_dark_traff c:
  com nt: "Def nes t  percentage of traff c to forward to d ffy-proxy. Set to 0 to d sable dark traff c forward ng"
  default_ava lab l y: 0

"representat on-scorer_load_s d_non_prod_callers":
  com nt: "D scard traff c from all non-prod callers"
  default_ava lab l y: 0

enable_log_fav_based_t et_embedd ng_20m145k2020_t  outs:
  com nt: " f enabled, set a t  out on calls to t  logFavBased20M145K2020T etEmbedd ngStore"
  default_ava lab l y: 0

log_fav_based_t et_embedd ng_20m145k2020_t  out_value_m ll s:
  com nt: "T  value of t  dec der def nes t  t  out ( n m ll seconds) to use on calls to t  logFavBased20M145K2020T etEmbedd ngStore,  .e. 1.50%  s 150ms. Only appl ed  f enable_log_fav_based_t et_embedd ng_20m145k2020_t  outs  s true"
  default_ava lab l y: 2000

enable_log_fav_based_t et_embedd ng_20m145kUpdated_t  outs:
  com nt: " f enabled, set a t  out on calls to t  logFavBased20M145KUpdatedT etEmbedd ngStore"
  default_ava lab l y: 0

log_fav_based_t et_embedd ng_20m145kUpdated_t  out_value_m ll s:
  com nt: "T  value of t  dec der def nes t  t  out ( n m ll seconds) to use on calls to t  logFavBased20M145KUpdatedT etEmbedd ngStore,  .e. 1.50%  s 150ms. Only appl ed  f enable_log_fav_based_t et_embedd ng_20m145kUpdated_t  outs  s true"
  default_ava lab l y: 2000

enable_cluster_t et_ ndex_store_t  outs:
  com nt: " f enabled, set a t  out on calls to t  ClusterT et ndexStore"
  default_ava lab l y: 0

cluster_t et_ ndex_store_t  out_value_m ll s:
  com nt: "T  value of t  dec der def nes t  t  out ( n m ll seconds) to use on calls to t  ClusterT et ndexStore,  .e. 1.50%  s 150ms. Only appl ed  f enable_cluster_t et_ ndex_store_t  outs  s true"
  default_ava lab l y: 2000

representat on_scorer_fetch_s gnal_share:
  com nt: " f enabled, fetc s share s gnals from USS"
  default_ava lab l y: 0

representat on_scorer_fetch_s gnal_reply:
  com nt: " f enabled, fetc s reply s gnals from USS"
  default_ava lab l y: 0

representat on_scorer_fetch_s gnal_or g nal_t et:
  com nt: " f enabled, fetc s or g nal t et s gnals from USS"
  default_ava lab l y: 0

representat on_scorer_fetch_s gnal_v deo_playback:
  com nt: " f enabled, fetc s v deo playback s gnals from USS"
  default_ava lab l y: 0

representat on_scorer_fetch_s gnal_block:
  com nt: " f enabled, fetc s account block s gnals from USS"
  default_ava lab l y: 0

representat on_scorer_fetch_s gnal_mute:
  com nt: " f enabled, fetc s account mute s gnals from USS"
  default_ava lab l y: 0

representat on_scorer_fetch_s gnal_report:
  com nt: " f enabled, fetc s t et report s gnals from USS"
  default_ava lab l y: 0

representat on_scorer_fetch_s gnal_dont_l ke:
  com nt: " f enabled, fetc s t et don't l ke s gnals from USS"
  default_ava lab l y: 0

representat on_scorer_fetch_s gnal_see_fe r:
  com nt: " f enabled, fetc s t et see fe r s gnals from USS"
  default_ava lab l y: 0

# To create a new dec der, add  re w h t  sa  format and caller's deta ls : "representat on-scorer_load_s d_by_caller_ d_twtr:{{role}}:{{na }}:{{env ron nt}}:{{cluster}}"
# All t  dec ders below are generated by t  scr pt - ./strato/b n/fed dec ders ./ --serv ce-role=representat on-scorer --serv ce-na =representat on-scorer
#  f   need to run t  scr pt and paste t  output, add only t  prod dec ders  re. Non-prod ones are be ng taken care of by representat on-scorer_load_s d_non_prod_callers

"representat on-scorer_load_s d_by_caller_ d_all":
  com nt: "Reject all traff c from caller  d: all"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:fr gate:fr gate-pushserv ce-canary:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:fr gate:fr gate-pushserv ce-canary:prod:atla"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:fr gate:fr gate-pushserv ce-canary:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:fr gate:fr gate-pushserv ce-canary:prod:pdxa"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:fr gate:fr gate-pushserv ce-send:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:fr gate:fr gate-pushserv ce-send:prod:atla"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:fr gate:fr gate-pushserv ce:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:fr gate:fr gate-pushserv ce:prod:atla"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:fr gate:fr gate-pushserv ce:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:fr gate:fr gate-pushserv ce:prod:pdxa"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:fr gate:fr gate-pushserv ce:stag ng:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:fr gate:fr gate-pushserv ce:stag ng:atla"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:fr gate:fr gate-pushserv ce:stag ng:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:fr gate:fr gate-pushserv ce:stag ng:pdxa"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:ho -scorer:ho -scorer:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:ho -scorer:ho -scorer:prod:atla"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:ho -scorer:ho -scorer:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:ho -scorer:ho -scorer:prod:pdxa"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:stratostore:stratoap :prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:stratostore:stratoap :prod:atla"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:stratostore:stratoserver:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:stratostore:stratoserver:prod:atla"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:stratostore:stratoserver:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:stratostore:stratoserver:prod:pdxa"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:t  l nescorer:t  l nescorer:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:t  l nescorer:t  l nescorer:prod:atla"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:t  l nescorer:t  l nescorer:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:t  l nescorer:t  l nescorer:prod:pdxa"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:top c-soc al-proof:top c-soc al-proof:prod:atla":
  com nt: "Reject all traff c from caller  d: twtr:svc:top c-soc al-proof:top c-soc al-proof:prod:atla"
  default_ava lab l y: 0

"representat on-scorer_load_s d_by_caller_ d_twtr:svc:top c-soc al-proof:top c-soc al-proof:prod:pdxa":
  com nt: "Reject all traff c from caller  d: twtr:svc:top c-soc al-proof:top c-soc al-proof:prod:pdxa"
  default_ava lab l y: 0

"enable_s m_clusters_embedd ng_store_t  outs":
  com nt: " f enabled, set a t  out on calls to t  S mClustersEmbedd ngStore"
  default_ava lab l y: 10000

s m_clusters_embedd ng_store_t  out_value_m ll s:
  com nt: "T  value of t  dec der def nes t  t  out ( n m ll seconds) to use on calls to t  S mClustersEmbedd ngStore,  .e. 1.50%  s 150ms. Only appl ed  f enable_s m_clusters_embedd ng_store_t  outs  s true"
  default_ava lab l y: 2000
