create_thr ft_l brar es(
    base_na  = "thr ft",
    s ces = [
        "com/tw ter/representat on_manager/serv ce.thr ft",
    ],
    platform = "java8",
    tags = [
        "bazel-compat ble",
    ],
    dependency_roots = [
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft",
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
)
