scala_l brary(
    na  = "s mclusters_ ndex_generat on",
    s ces = [
        "**/*.scala",
    ],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "src/scala/com/tw ter/s mclusters_v2/hdfs_s ces:ads_fav_based_s mclusters_cluster_to_t et_ ndex-scala",
        "src/scala/com/tw ter/s mclusters_v2/hdfs_s ces:ads_fav_cl ck_based_s mclusters_cluster_to_t et_ ndex-scala",
        "src/scala/com/tw ter/s mclusters_v2/hdfs_s ces:fav_based_evergreen_content_s mclusters_cluster_to_t et_ ndex-scala",
        "src/scala/com/tw ter/s mclusters_v2/hdfs_s ces:fav_based_s mclusters_cluster_to_t et_ ndex-scala",
        "src/scala/com/tw ter/s mclusters_v2/hdfs_s ces:fav_based_v deo_s mclusters_cluster_to_t et_ ndex-scala",
        "src/scala/com/tw ter/s mclusters_v2/hdfs_s ces:push_open_based_s mclusters_cluster_to_t et_ ndex-scala",
        "src/scala/com/tw ter/s mclusters_v2/hdfs_s ces:reply_based_s mclusters_cluster_to_t et_ ndex-scala",
        "src/scala/com/tw ter/s mclusters_v2/hdfs_s ces:ret et_based_s mclusters_cluster_to_t et_ ndex-scala",
        "src/scala/com/tw ter/s mclusters_v2/hdfs_s ces:v deo_v ew_based_s mclusters_cluster_to_t et_ ndex-scala",
        "src/scala/com/tw ter/s mclusters_v2/sc o/bq_generat on/common",
        "src/scala/com/tw ter/s mclusters_v2/sc o/bq_generat on/sql",
        "src/scala/com/tw ter/s mclusters_v2/sc o/bq_generat on/t ets_ann:bq_generat on",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
    ],
)

jvm_b nary(
    na  = "fav-based-cluster-to-t et- ndex-generat on-adhoc-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.FavBasedClusterToT et ndexGenerat onAdhocJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "fav-based-cluster-to-t et- ndex-generat on-batch-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.FavBasedClusterToT et ndexGenerat onBatchJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "v deo-v ew-based-cluster-to-t et- ndex-generat on-adhoc-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.V deoV ewBasedClusterToT et ndexGenerat onAdhocJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "v deo-v ew-based-cluster-to-t et- ndex-generat on-batch-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.V deoV ewBasedClusterToT et ndexGenerat onBatchJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "ret et-based-cluster-to-t et- ndex-generat on-adhoc-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.Ret etBasedClusterToT et ndexGenerat onAdhocJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "ret et-based-cluster-to-t et- ndex-generat on-batch-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.Ret etBasedClusterToT et ndexGenerat onBatchJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "reply-based-cluster-to-t et- ndex-generat on-adhoc-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.ReplyBasedClusterToT et ndexGenerat onAdhocJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "reply-based-cluster-to-t et- ndex-generat on-batch-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.ReplyBasedClusterToT et ndexGenerat onBatchJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "push-open-based-cluster-to-t et- ndex-generat on-adhoc-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.PushOpenBasedClusterToT et ndexGenerat onAdhocJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "push-open-based-cluster-to-t et- ndex-generat on-batch-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.PushOpenBasedClusterToT et ndexGenerat onBatchJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "ads-fav-based-cluster-to-t et- ndex-generat on-adhoc-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.AdsFavBasedClusterToT et ndexGenerat onAdhocJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "ads-fav-based-cluster-to-t et- ndex-generat on-batch-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.AdsFavBasedClusterToT et ndexGenerat onBatchJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "ads-fav-cl ck-based-cluster-to-t et- ndex-generat on-adhoc-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.AdsFavCl ckBasedClusterToT et ndexGenerat onAdhocJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "ads-fav-cl ck-based-cluster-to-t et- ndex-generat on-batch-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.AdsFavCl ckBasedClusterToT et ndexGenerat onBatchJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "fav-based-evergreen-content-cluster-to-t et- ndex-generat on-adhoc-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.FavBasedEvergreenContentClusterToT et ndexGenerat onAdhocJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "fav-based-evergreen-content-cluster-to-t et- ndex-generat on-batch-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.FavBasedEvergreenContentClusterToT et ndexGenerat onBatchJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "fav-based-v deo-cluster-to-t et- ndex-generat on-adhoc-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.FavBasedV deoClusterToT et ndexGenerat onAdhocJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)

jvm_b nary(
    na  = "fav-based-v deo-cluster-to-t et- ndex-generat on-batch-job",
    ma n = "com.tw ter.s mclusters_v2.sc o.bq_generat on.s mclusters_ ndex_generat on.FavBasedV deoClusterToT et ndexGenerat onBatchJob",
    dependenc es = [
        ":s mclusters_ ndex_generat on",
    ],
)
