scala_l brary(
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/storehaus:core",
        "fr gate/fr gate-common:base",
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/base",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/scala/com/tw ter/s mclusters_v2/score",
        "src/scala/com/tw ter/s mclusters_v2/summ ngb rd/stores",
        "src/scala/com/tw ter/s mclusters_v2/t et_s m lar y",
        "src/thr ft/com/tw ter/recos/user_t et_ent y_graph:user_t et_ent y_graph-scala",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
        "src/thr ft/com/tw ter/wtf/ nterest: nterest-thr ft-scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)
