create_thr ft_l brar es(
    base_na  = "thr ft",
    s ces = ["*.thr ft"],
    platform = "java8",
    tags = [
        "bazel-compat ble",
    ],
    dependency_roots = [
        "content-recom nder/thr ft/src/ma n/thr ft",
        "content-recom nder/thr ft/src/ma n/thr ft:content-recom nder-common",
        " nterests-serv ce/thr ft/src/ma n/thr ft",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft",
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    prov des_java_na  = "tsp-thr ft-java",
    prov des_scala_na  = "tsp-thr ft-scala",
)
