scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/conf gap /reg stry",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng/request",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/m xer",
        "st ch/st ch-core",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/conf gap /reg stry",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng/request",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/m xer",
        "st ch/st ch-core",
    ],
)
