scala_l brary(
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/com/tw ter/storehaus:core",
        "fr gate/fr gate-common:base",
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/base",
        "s mclusters-ann/thr ft/src/ma n/thr ft:thr ft-scala",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/scala/com/tw ter/s mclusters_v2/summ ngb rd/stores",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)
