scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/cand date_s ce",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "st ch/st ch-core",
        "strato/src/ma n/scala/com/tw ter/strato/catalog",
        "strato/src/ma n/scala/com/tw ter/strato/cl ent",
        "strato/src/ma n/scala/com/tw ter/strato/response",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/cand date_s ce",
        "st ch/st ch-core",
        "strato/src/ma n/scala/com/tw ter/strato/catalog",
        "strato/src/ma n/scala/com/tw ter/strato/cl ent",
    ],
)
