# Java l brary for docvalues and common str de f eld encod ng ut l  es.
java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    prov des = art fact(
        org = "com.tw ter.search.common",
        na  = "encod ng-docvalues",
        repo = art factory,
    ),
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/org/apac /lucene:lucene-analyzers-common",
        "3rdparty/jvm/org/apac /lucene:lucene-core",
        "3rdparty/jvm/org/apac /lucene:lucene-facet",
        "3rdparty/jvm/org/apac /thr ft:l bthr ft",
        "src/java/com/tw ter/search/common/sc ma/base",
        "src/thr ft/com/tw ter/search/common:sc ma-java",
    ],
)
