java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/apac /lucene:lucene-analyzers-common",
        "3rdparty/jvm/org/apac /lucene:lucene-analyzers-smartcn",
        "3rdparty/jvm/org/apac /lucene:lucene-facet",
        "3rdparty/jvm/org/apac /lucene:lucene-quer es",
        "src/java/com/tw ter/search/common/constants",
        "src/java/com/tw ter/search/common/sc ma/base",
        "src/java/com/tw ter/search/common/sc ma/earlyb rd",
        "src/java/com/tw ter/search/core/earlyb rd",
        "src/thr ft/com/tw ter/search:earlyb rd-java",
    ],
)
