scala_l brary(
    s ces = [
        "*.scala",
    ],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "common- nternal/analyt cs/cl ent-analyt cs-data-layer/src/ma n/scala",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "src/scala/com/tw ter/loggedout/analyt cs/common",
        "src/thr ft/com/tw ter/cl entapp/gen:cl entapp-scala",
        "twadoop_conf g/conf gurat on/log_categor es/group/scr bel b:cl ent_event-scala",
        "un f ed_user_act ons/adapter/src/ma n/scala/com/tw ter/un f ed_user_act ons/adapter:base",
        "un f ed_user_act ons/adapter/src/ma n/scala/com/tw ter/un f ed_user_act ons/adapter/common",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
    ],
)
