create_thr ft_l brar es(
    base_na  = "thr ft",
    s ces = ["**/*.thr ft"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependency_roots = [
        "f natra- nternal/thr ft/src/ma n/thr ft",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft",
    ],
    generate_languages = [
        "java",
        "scala",
    ],
    prov des_java_na  = "s mclusters-ann-thr ft-java",
    prov des_scala_na  = "s mclusters-ann-thr ft-scala",
)
