python3_l brary(
    na  = "params_l b",
    s ces = [
        "params.py",
    ],
    tags = [
        "bazel-compat ble",
        "no- py",
    ],
    dependenc es = [
        "3rdparty/python/pydant c:default",
    ],
)

python3_l brary(
    na  = "layers_l b",
    s ces = [
        "layers.py",
    ],
    tags = [
        "bazel-compat ble",
        "no- py",
    ],
    dependenc es = [
    ],
)

python3_l brary(
    na  = "model_l b",
    s ces = [
        "model.py",
    ],
    tags = [
        "bazel-compat ble",
        "no- py",
    ],
    dependenc es = [
        ":layers_l b",
        ":params_l b",
        "3rdparty/python/absl-py:default",
    ],
)
