scala_l brary(
    platform = "java11",
    str ct_deps = False,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/graphjet",
        "f nagle/f nagle-stats",
        "recos- njector/server/src/ma n/scala/com/tw ter/recos njector/cl ents",
        "src/scala/com/tw ter/recos/ut l:recos-ut l",
        "src/thr ft/com/tw ter/t etyp e:t et-scala",
    ],
)
