scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "servo/ut l",
        "st ch/st ch-core",
        "ut l/ut l-core:ut l-core-ut l",
        "ut l/ut l-stats",
    ],
    exports = [
        "servo/ut l",
        "st ch/st ch-core",
        "ut l/ut l-core:ut l-core-ut l",
        "ut l/ut l-stats",
    ],
)
