scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle-core/src/ma n",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "servo/ut l",
        "snowflake: d",
        "st ch/st ch-core",
        "ut l/ut l-core:ut l-core-ut l",
        "ut l/ut l-stats",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "servo/ut l",
        "snowflake: d",
        "st ch/st ch-core",
        "ut l/ut l-core:ut l-core-ut l",
        "ut l/ut l-stats",
    ],
)
