scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "conf gap /conf gap -core",
        "f nagle/f nagle-stats",
        "v s b l y/common/src/ma n/scala/com/tw ter/v s b l y/common:model_thresholds",
    ],
    exports = [
        "v s b l y/common/src/ma n/scala/com/tw ter/v s b l y/common:model_thresholds",
    ],
)
