scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/com/tw ter/b ject on:core",
        "3rdparty/jvm/com/tw ter/storehaus:core",
        "3rdparty/jvm/org/apac /beam:beam-sdks-java- o-google-cloud-platform",
        "ann/src/ma n/thr ft/com/tw ter/ann/common:ann-common-scala",
        "f natra/ nject/ nject-mdc/src/ma n/scala",
        " d aserv ces/commons/src/ma n/scala:futuretracker",
        "src/java/com/tw ter/search/common/f le",
        "src/scala/com/tw ter/ml/ap /embedd ng",
        "st ch/st ch-core",
    ],
    exports = [
        "3rdparty/jvm/com/tw ter/b ject on:core",
    ],
)
