java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/commons- o",
        "3rdparty/jvm/org/json",
        "src/java/com/tw ter/common/ut l:system-mocks",
        "src/java/com/tw ter/search/common/dark",
        "src/java/com/tw ter/search/common/ tr cs",
        "src/java/com/tw ter/search/common/ut l/ o/per od c",
        "src/java/com/tw ter/search/common/ut l/json",
    ],
)
