scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = False,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "appsec/san  zat on-l b/src/ma n/scala",
        "src/thr ft/com/tw ter/expandodo:cards-scala",
        "st ch/st ch-core",
        "v s b l y/l b/src/ma n/res ces/conf g",
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y",
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/bu lder/t ets",
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/bu lder/users",
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/features",
    ],
)
