scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/scorer/common",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featuremap",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featuremap/featurestorev1",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featurestorev1",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "src/thr ft/com/tw ter/ml/ap :embedd ng-scala",
    ],
    exports = [
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/scorer/common",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
    ],
)
