scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f natra/ nject/ nject-app/src/ma n/java/com/tw ter/ nject/annotat ons",
        "f natra/ nject/ nject-core/src/ma n/scala",
    ],
    exports = [
        "f natra/ nject/ nject-app/src/ma n/java/com/tw ter/ nject/annotat ons",
        "f natra/ nject/ nject-core/src/ma n/scala",
    ],
)
