create_thr ft_l brar es(
    base_na  = "s mclusters_v2-thr ft",
    s ces = ["*.thr ft"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependency_roots = [
        "src/thr ft/com/tw ter/algeb rd_ nternal",
    ],
    export_roots = [
        "src/thr ft/com/tw ter/algeb rd_ nternal:algeb rd_ nternal",
    ],
    generate_languages = [
        "go",
        "java",
        "lua",
        "python",
        "ruby",
        "scala",
        "strato",
    ],
    prov des_java_na  = "s mclusters_v2-thr ft-java",
    prov des_scala_na  = "s mclusters_v2-thr ft-scala",
)
