scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/storehaus:core",
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date/ads",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/query/ads",
        "src/thr ft/com/tw ter/ads/adserver:ads_shared_types-scala",
    ],
    exports = [
        "3rdparty/jvm/com/tw ter/storehaus:core",
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date/ads",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/query/ads",
        "src/thr ft/com/tw ter/ads/adserver:ads_shared_types-scala",
    ],
)
