scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle- mcac d/src/ma n/scala",
        "scrooge/scrooge-ser al zer",
        "st ch/st ch-core",
        "ut l/ut l-core",
        "ut l/ut l-logg ng",
        # Cac dValue struct
        "t etyp e/servo/repo/src/ma n/thr ft:thr ft-scala",
        "ut l/ut l-slf4j-ap /src/ma n/scala/com/tw ter/ut l/logg ng",
    ],
)
