scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "conf gap /conf gap -core",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/product",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/product",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/product/reg stry",
        "st ch/st ch-core",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql:ap - d a-graphql-scala",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql:graphql-scala",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql:top cs-graphql-scala",
        "ut l/ut l-core:scala",
    ],
    exports = [
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql:graphql-scala",
    ],
)
