scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f natra/ nject/ nject-thr ft-cl ent",
        "representat on-manager/server/src/ma n/scala/com/tw ter/representat on_manager/columns/top c",
        "representat on-manager/server/src/ma n/scala/com/tw ter/representat on_manager/columns/t et",
        "representat on-manager/server/src/ma n/scala/com/tw ter/representat on_manager/columns/user",
        "strato/src/ma n/scala/com/tw ter/strato/fed",
        "strato/src/ma n/scala/com/tw ter/strato/fed/server",
    ],
)
