res ces(
    s ces = [
        "!*.pyc",
        "!BU LD*",
        "*",
    ],
    tags = ["bazel-compat ble"],
)

# Created for Bazel compat b l y.
#  n Bazel, loose f les must be part of a target to be  ncluded  nto a bundle.
# See also http://go/bazel-compat b l y/bundle_does_not_match_any_f les
f les(
    na  = "f les",
    s ces = [
        "!BU LD",
        "**/*",
    ],
    tags = ["bazel-compat ble"],
)
