t et_event_transfor r_user_t et_ent y_edges:
  com nt: "Enables t  generat on of UserT etEnt y edges  n t et event transfor r"
  default_ava lab l y: 0

enable_em _t et_edge_from_reply:
  com nt: "Dec des w n process ng a Reply edge, w t r to generate a T et edge for   as  ll"
  default_ava lab l y: 0

enable_unfavor e_edge:
  com nt: "Dec des w n process ng a Unfavor eEvent from T  l ne events, w t r to process unfav edges"
  default_ava lab l y: 0
