jvm_b nary(
    na  = "uua-tls-favs-b n",
    basena  = "uua-tls-favs-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.TlsFavsServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:tls-favs",
    ],
)

jvm_app(
    na  = "uua-tls-favs",
    arch ve = "z p",
    b nary = ":uua-tls-favs-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)

jvm_b nary(
    na  = "uua-cl ent-event-b n",
    basena  = "uua-cl ent-event-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.Cl entEventServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:cl ent-event",
    ],
)

jvm_app(
    na  = "uua-cl ent-event",
    arch ve = "z p",
    b nary = ":uua-cl ent-event-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)


jvm_b nary(
    na  = "uua-t etyp e-event-b n",
    basena  = "uua-t etyp e-event-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.T etyp eEventServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:t etyp e-event",
    ],
)

jvm_app(
    na  = "uua-t etyp e-event",
    arch ve = "z p",
    b nary = ":uua-t etyp e-event-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)

jvm_b nary(
    na  = "uua-soc al-graph-b n",
    basena  = "uua-soc al-graph-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.Soc alGraphServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:soc al-graph-event",
    ],
)

jvm_app(
    na  = "uua-soc al-graph",
    arch ve = "z p",
    b nary = ":uua-soc al-graph-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)

jvm_b nary(
    na  = "uua-ema l-not f cat on-event-b n",
    basena  = "uua-ema l-not f cat on-event-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.Ema lNot f cat onEventServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:ema l-not f cat on-event",
    ],
)

jvm_app(
    na  = "uua-ema l-not f cat on-event",
    arch ve = "z p",
    b nary = ":uua-ema l-not f cat on-event-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)

jvm_b nary(
    na  = "uua-user-mod f cat on-b n",
    basena  = "uua-user-mod f cat on-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.UserMod f cat onServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:user-mod f cat on-event",
    ],
)

jvm_app(
    na  = "uua-user-mod f cat on",
    arch ve = "z p",
    b nary = ":uua-user-mod f cat on-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)

jvm_b nary(
    na  = "uua-ads-callback-engage nts-b n",
    basena  = "uua-ads-callback-engage nts-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.AdsCallbackEngage ntsServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:ads-callback-engage nts",
    ],
)

jvm_app(
    na  = "uua-ads-callback-engage nts",
    arch ve = "z p",
    b nary = ":uua-ads-callback-engage nts-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)

jvm_b nary(
    na  = "uua-favor e-arch val-events-b n",
    basena  = "uua-favor e-arch val-events-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.Favor eArch valEventsServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:favor e-arch val-events",
    ],
)

jvm_app(
    na  = "uua-favor e-arch val-events",
    arch ve = "z p",
    b nary = ":uua-favor e-arch val-events-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)

jvm_b nary(
    na  = "uua-ret et-arch val-events-b n",
    basena  = "uua-ret et-arch val-events-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.Ret etArch valEventsServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:ret et-arch val-events",
    ],
)

jvm_app(
    na  = "uua-ret et-arch val-events",
    arch ve = "z p",
    b nary = ":uua-ret et-arch val-events-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)

jvm_b nary(
    na  = "rekey-uua-b n",
    basena  = "rekey-uua-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.RekeyUuaServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:rekey-uua",
    ],
)

jvm_app(
    na  = "rekey-uua",
    arch ve = "z p",
    b nary = ":rekey-uua-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)

jvm_b nary(
    na  = "rekey-uua- es ce-b n",
    basena  = "rekey-uua- es ce-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.RekeyUua es ceServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:rekey-uua- es ce",
    ],
)

jvm_app(
    na  = "rekey-uua- es ce",
    arch ve = "z p",
    b nary = ":rekey-uua- es ce-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)

jvm_b nary(
    na  = "uua-enr ch nt-planner-b n",
    basena  = "uua-enr ch nt-planner-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.Enr ch ntPlannerServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:enr ch nt-planner",
    ],
)

jvm_app(
    na  = "uua-enr ch nt-planner",
    arch ve = "z p",
    b nary = ":uua-enr ch nt-planner-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)

jvm_b nary(
    na  = "uua-enr c r-b n",
    basena  = "uua-enr c r-b n",
    ma n = "com.tw ter.un f ed_user_act ons.serv ce.Enr c rServ ceMa n",
    runt  _platform = "java11",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/ch/qos/logback:logback-class c",
        "loglens/loglens-logback/src/ma n/scala/com/tw ter/loglens/logback",
        "tw ter-server- nternal/src/ma n/scala",
        "tw ter-server/logback-class c/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/res ces",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce:enr c r",
    ],
)

jvm_app(
    na  = "uua-enr c r",
    arch ve = "z p",
    b nary = ":uua-enr c r-b n",
    bundles = [
        bundle(
            f leset = ["**/*"],
            own ng_target = "un f ed_user_act ons/serv ce/src/ma n/res ces:f les",
            rel_path = "un f ed_user_act ons/serv ce/src/ma n/res ces",
        ),
    ],
    tags = ["bazel-compat ble"],
)
