scala_l brary(
    s ces = ["*.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/graphjet",
        "snowflake: d",
        "snowflake/src/ma n/scala/com/tw ter/snowflake/ d",
        "src/scala/com/tw ter/recos/ut l:recos-ut l",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/thr ft/com/tw ter/recos/user_t et_graph:user_t et_graph-scala",
    ],
)
