scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "strato/src/ma n/scala/com/tw ter/strato/fed",
        "strato/src/ma n/scala/com/tw ter/strato/fed/server",
    ],
)
