scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    scalac_plug ns = ["no-roomba"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "ads- nject on/l b/src/ma n/scala/com/tw ter/goldf nch/model",
        "ads- nject on/l b/src/ma n/scala/com/tw ter/goldf nch/model/promoted",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common",
        "src/thr ft/com/tw ter/ads/adserver:adserver_common-scala",
    ],
    exports = [
        "ads- nject on/l b/src/ma n/scala/com/tw ter/goldf nch/model",
        "ads- nject on/l b/src/ma n/scala/com/tw ter/goldf nch/model/promoted",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common",
        "src/thr ft/com/tw ter/ads/adserver:adserver_common-scala",
    ],
)
