scala_l brary(
    s ces = ["**/*.scala"],
    platform = "java8",
    prov des = scala_art fact(
        org = "com.tw ter",
        na  = "servo-request",
        repo = art factory,
    ),
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle-core/src/ma n",
        "t etyp e/servo/ut l",
        "tw ter-conf g/yaml",
        "ut l/ut l-stats/src/ma n/scala",
    ],
    exports = [
        "t etyp e/servo/ut l",
    ],
)
