scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "account-recom ndat ons-m xer/thr ft/src/ma n/thr ft:thr ft-scala",
        "f natra/ nject/ nject-core/src/ma n/scala/com/tw ter/ nject",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/cand date_s ce",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "src/thr ft/com/tw ter/ads/adserver:adserver_common-scala",
        "st ch/st ch-core",
    ],
    exports = [
        "account-recom ndat ons-m xer/thr ft/src/ma n/thr ft:thr ft-scala",
        "f natra/ nject/ nject-core/src/ma n/scala/com/tw ter/ nject",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/cand date_s ce",
        "st ch/st ch-core",
    ],
)
