scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "conf gap /conf gap -core/src/ma n/scala/com/tw ter/t  l nes/conf gap ",
        "f nagle/f nagle-core/src/ma n",
        "follow-recom ndat ons-serv ce/common/src/ma n/scala/com/tw ter/follow_recom ndat ons/common/models",
        " rm / rm -core/src/ma n/scala/com/tw ter/ rm /model",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/cand date_s ce",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/recom ndat on",
        "st ch/st ch-core",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/recom ndat on",
    ],
)
