scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/b ject on:core",
        "featuresw c s/featuresw c s-core/src/ma n/scala",
        "scrooge/scrooge-ser al zer/src/ma n/scala",
        "t etyp e/servo/repo",
        "t etyp e/servo/ut l",
        "t etyp e/common/src/thr ft/com/tw ter/t etyp e:serv ce-scala",
        "t etyp e/common/src/thr ft/com/tw ter/t etyp e:t et-scala",
        "st ch/st ch-core",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e",
        "t etyp e/server/src/ma n/thr ft:comp led-scala",
    ],
)
