scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    scalac_plug ns = ["no-roomba"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "onboard ng/serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/cand date_s ce/flex ble_ nject on_p pel ne",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/cand date",
    ],
    exports = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "onboard ng/serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/cand date_s ce/flex ble_ nject on_p pel ne",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/cand date",
    ],
)
