scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle/f nagle-core/src/ma n",
        "f nagle/f nagle-http/src/ma n/scala",
        "f nagle/f nagle-thr ftmux/src/ma n/scala",
        "f natra- nternal/mtls-http/src/ma n/scala",
        "f natra- nternal/mtls-thr ftmux/src/ma n/scala",
        "ut l/ut l-core",
    ],
    exports = [
        "f nagle/f nagle-core/src/ma n",
        "f nagle/f nagle-http/src/ma n/scala",
        "f nagle/f nagle-thr ftmux/src/ma n/scala",
        "f natra- nternal/mtls-http/src/ma n/scala",
        "f natra- nternal/mtls-thr ftmux/src/ma n/scala",
        "ut l/ut l-core",
    ],
)
