scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "addressbook/thr ft/src/thr ft/com/tw ter/addressbook:thr ft-scala",
        "addressbook/thr ft/src/thr ft/com/tw ter/addressbook/datatypes:thr ft-scala",
    ],
)
