scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/component-l brary/src/ma n/thr ft/com/tw ter/product_m xer/component_l brary:thr ft-scala",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/marshaller",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng/response/sl ce",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql:ap - d a-graphql-scala",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql:graphql-scala",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql:top cs-graphql-scala",
    ],
)
