scala_l brary(
    s ces = [
        "*.scala",
    ],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = [
        "bazel-compat ble",
        "bazel-only",
    ],
    dependenc es = [
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "src/thr ft/com/tw ter/ads/b ll ng/spendserver:spendserver_thr ft-scala",
        "src/thr ft/com/tw ter/ads/eventstream:eventstream-scala",
        "un f ed_user_act ons/adapter/src/ma n/scala/com/tw ter/un f ed_user_act ons/adapter:base",
        "un f ed_user_act ons/adapter/src/ma n/scala/com/tw ter/un f ed_user_act ons/adapter/common",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
    ],
)
