scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/premarshaller/urp/bu lder",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/premarshaller/urt/bu lder",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/premarshaller",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/selector",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng/response/urp",
    ],
    exports = [
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/premarshaller/urp/bu lder",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/premarshaller",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/selector",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng/response/urp",
    ],
)
