scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/apac /thr ft:l bthr ft",
        " d aserv ces/commons/src/ma n/thr ft:thr ft-scala",
        "scrooge/scrooge-core",
        "src/thr ft/com/tw ter/esc rb rd: d a-annotat on-structs-scala",
        "src/thr ft/com/tw ter/spam/rtf:safety-label-scala",
        "t etyp e/common/src/thr ft/com/tw ter/t etyp e:t et-scala",
    ],
)
