scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/ nject:gu ce",
        "3rdparty/jvm/javax/ nject:javax. nject",
        "f natra/ nject/ nject-core/src/ma n/scala",
        "product-m xer/core/src/ma n/java/com/tw ter/product_m xer/core/product/gu ce/scope",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng/request",
    ],
    exports = [
        "product-m xer/core/src/ma n/java/com/tw ter/product_m xer/core/product/gu ce/scope",
    ],
)
