scala_l brary(
    na  = "hcac ",
    s ces = ["*.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "ut l/ut l-cac -guava/src/ma n/scala",
        "ut l/ut l-cac /src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)
