scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = [
        "bazel-compat ble",
    ],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "abdec der/src/ma n/scala",
        "content-recom nder/thr ft/src/ma n/thr ft:thr ft-scala",
        " rm / rm -core/src/ma n/scala/com/tw ter/ rm /store/common",
        " rm / rm -core/src/ma n/scala/com/tw ter/ rm /store/g zmoduck",
        "src/scala/com/tw ter/top c_recos/stores",
        "src/thr ft/com/tw ter/g zmoduck:thr ft-scala",
        "src/thr ft/com/tw ter/g zmoduck:user-thr ft-scala",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
        "st ch/st ch-storehaus",
        "top c-soc al-proof/server/src/ma n/scala/com/tw ter/tsp/common",
        "top c-soc al-proof/server/src/ma n/scala/com/tw ter/tsp/handlers",
        "top c-soc al-proof/server/src/ma n/scala/com/tw ter/tsp/modules",
        "top c-soc al-proof/server/src/ma n/scala/com/tw ter/tsp/stores",
        "top c-soc al-proof/server/src/ma n/thr ft:thr ft-scala",
    ],
)
