scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "t  l neranker/common/src/ma n/scala/com/tw ter/t  l neranker/model",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/core",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/recap/model",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/model/types",
    ],
)
