scala_l brary(
    s ces = ["*.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/storehaus:core",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/thr ft/com/tw ter/soc algraph:thr ft-scala",
    ],
)
