scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common/presentat on",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "st ch/st ch-core",
    ],
    exports = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common/presentat on",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "st ch/st ch-core",
    ],
)
