scala_l brary(
    na  = " nsert_append_results",
    s ces = [" nsertAppendResults.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/common",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/selector",
    ],
    exports = [
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/common",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/selector",
    ],
)

scala_l brary(
    s ces = [
        "! nsertAppendResults.scala",
        "*.scala",
    ],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    scalac_plug ns = ["no-roomba"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        ": nsert_append_results",
        "3rdparty/jvm/com/google/ nject:gu ce",
        "f natra/ nject/ nject-slf4j/src/ma n/scala/com/tw ter/ nject",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date/ads",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/query/ads",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/selector/sorter",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/conf gap ",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/selector",
    ],
    exports = [
        ": nsert_append_results",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/selector/sorter",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/selector",
    ],
)
