scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/datarecord",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featuremap",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featurestorev1",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featurestorev1/featurevalue",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "src/java/com/tw ter/ml/ap :ap -base",
        "src/scala/com/tw ter/ml/ap /ut l:datarecord",
        "ut l/ut l-core",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featuremap",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "ut l/ut l-core",
    ],
)
