python3_l brary(
    na  = "l bs_py3",
    s ces = ["*.py"],
    tags = ["no- py"],
    dependenc es = [
        "src/python/tw ter/deepb rd/ o",
        "src/python/tw ter/deepb rd/projects/t  l nes/conf gs:all_conf gs",
        "twml:twml-nodeps",
    ],
)

python37_b nary(
    na  = "model_earlyb rd",
    s ce = "tra n.py",
    tags = ["no- py"],
    dependenc es = [
        ":l bs_py3",
        "3rdparty/python/_closures/src/python/tw ter/deepb rd/projects/t  l nes/scr pts/models/earlyb rd:model_earlyb rd",
        "src/python/tw ter/deepb rd/projects/t  l nes/scr pts/models/earlyb rd/lolly:l bs_py3",
        "src/python/tw ter/deepb rd/projects/t  l nes/scr pts/models/earlyb rd/tf_model:l bs_py3",
        "twml",
    ],
)
