scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f natra/ nject/ nject-core/src/ma n/scala/com/tw ter/ nject",
        "onboard ng/serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/cand date_s ce",
        "st ch/st ch-core",
    ],
    exports = [
        "onboard ng/serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/cand date_s ce",
    ],
)
