scala_l brary(
    s ces = ["Dec derGates.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "dec der",
        "f nagle/f nagle-toggle/src/ma n/scala/com/tw ter/f nagle/server",
        "t etyp e/servo/dec der",
        "t etyp e/servo/ut l/src/ma n/scala",
        "ut l/ut l-core:scala",
    ],
)
