scala_l brary(
    s ces = ["*.scala"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "dec der/src/ma n/scala",
        "src/scala/com/tw ter/recos/ut l:recos-ut l",
    ],
)
