create_thr ft_l brar es(
    base_na  = "thr ft",
    s ces = [
        "com/tw ter/representat onscorer/serv ce.thr ft",
    ],
    platform = "java8",
    tags = [
        "bazel-compat ble",
    ],
    dependency_roots = [
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft",
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    prov des_java_na  = "representat onscorer-serv ce-thr ft-java",
    prov des_scala_na  = "representat onscorer-serv ce-thr ft-scala",
)
