scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/marshaller/response/rtf/safety_level",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng/response/rtf/safety_level",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng/response/urt/contextual_ref",
        "src/thr ft/com/tw ter/spam/rtf:safety-level-scala",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql/contextual_refs:graphql-refs-scala",
    ],
    exports = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/marshaller/response/rtf/safety_level",
        "src/thr ft/com/tw ter/spam/rtf:safety-level-scala",
        "strato/conf g/src/thr ft/com/tw ter/strato/graphql/contextual_refs:graphql-refs-scala",
    ],
)
