scala_l brary(
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        ":t et_s m lar y_test_datarecords_120m n-java",
        ":t et_s m lar y_test_datarecords_30m n-java",
        ":t et_s m lar y_tra n_datarecords_120m n-java",
        ":t et_s m lar y_tra n_datarecords_30m n-java",
        ":t et_s m lar y_unhydrated_pa rs_120m n-scala",
        ":t et_s m lar y_unhydrated_pa rs_30m n-scala",
        "3rdparty/jvm/com/tw ter/storehaus:algebra",
        "3rdparty/jvm/com/tw ter/storehaus:core",
        "dataproducts/ ns ghts/common/common",
        "snowflake: d",
        "src/java/com/tw ter/ml/ap /constant",
        "src/scala/com/tw ter/ads/dataserv ce_account/snapshot/jobs:db_snapshots_promoted_t ets-scala",
        "src/scala/com/tw ter/ml/ap :ap -base",
        "src/scala/com/tw ter/ml/featurestore/catalog/features/recom ndat ons:aggregate",
        "src/scala/com/tw ter/ml/featurestore/l b/embedd ng",
        "src/scala/com/tw ter/scald ng_ nternal/dalv2",
        "src/scala/com/tw ter/scald ng_ nternal/dalv2/dataset",
        "src/scala/com/tw ter/scald ng_ nternal/job",
        "src/scala/com/tw ter/scald ng_ nternal/job/analyt cs_batch",
        "src/scala/com/tw ter/scald ng_ nternal/s ce",
        "src/scala/com/tw ter/scald ng_ nternal/s ce/lzo_scrooge",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/scala/com/tw ter/s mclusters_v2/scald ng",
        "src/scala/com/tw ter/s mclusters_v2/t et_s m lar y",
        "src/scala/com/tw ter/wtf/scald ng/jobs/cl ent_event_process ng:user_ nteract on-scala",
        "twadoop_conf g/conf gurat on/log_categor es/group/t  l ne:t  l ne_serv ce_favor es-scala",
        "t ets ce/common:unhydrated_flat-scala",
    ],
)

hadoop_b nary(
    na  = "tra n ng_data_collect on-adhoc",
    ma n = "com.tw ter.s mclusters_v2.scald ng.t et_s m lar y.Tra n ngDataCollect onAdhocApp",
    platform = "java8",
    runt  _platform = "java8",
    tags = [
        "bazel-compat ble",
        "bazel-compat ble:m grated",
        "bazel-only",
    ],
    dependenc es = [
        ":t et_s m lar y",
    ],
)

hadoop_b nary(
    na  = "tra n ng_data_collect on_30m n",
    ma n = "com.tw ter.s mclusters_v2.scald ng.t et_s m lar y.Tra n ngDataCollect on30M nSc duledApp",
    platform = "java8",
    runt  _platform = "java8",
    tags = [
        "bazel-compat ble",
        "bazel-compat ble:m grated",
        "bazel-only",
    ],
    dependenc es = [
        ":t et_s m lar y",
    ],
)

hadoop_b nary(
    na  = "tra n ng_data_collect on_120m n",
    ma n = "com.tw ter.s mclusters_v2.scald ng.t et_s m lar y.Tra n ngDataCollect on120M nSc duledApp",
    platform = "java8",
    runt  _platform = "java8",
    tags = [
        "bazel-compat ble",
        "bazel-compat ble:m grated",
        "bazel-only",
    ],
    dependenc es = [
        ":t et_s m lar y",
    ],
)

hadoop_b nary(
    na  = "unhydrated_pa r_collect on-adhoc",
    ma n = "com.tw ter.s mclusters_v2.scald ng.t et_s m lar y.UnhydratedPa rsCollect onAdhocApp",
    platform = "java8",
    runt  _platform = "java8",
    tags = [
        "bazel-compat ble",
        "bazel-compat ble:m grated",
        "bazel-only",
    ],
    dependenc es = [
        ":t et_s m lar y",
    ],
)

hadoop_b nary(
    na  = "unhydrated_pa r_collect on_30m n",
    ma n = "com.tw ter.s mclusters_v2.scald ng.t et_s m lar y.UnhydratedPa rsCollect on30M nSc duledApp",
    platform = "java8",
    runt  _platform = "java8",
    tags = [
        "bazel-compat ble",
        "bazel-compat ble:m grated",
        "bazel-only",
    ],
    dependenc es = [
        ":t et_s m lar y",
    ],
)

hadoop_b nary(
    na  = "unhydrated_pa r_collect on_120m n",
    ma n = "com.tw ter.s mclusters_v2.scald ng.t et_s m lar y.UnhydratedPa rsCollect on120M nSc duledApp",
    platform = "java8",
    runt  _platform = "java8",
    tags = [
        "bazel-compat ble",
        "bazel-compat ble:m grated",
        "bazel-only",
    ],
    dependenc es = [
        ":t et_s m lar y",
    ],
)

hadoop_b nary(
    na  = "model_eval-adhoc",
    ma n = "com.tw ter.s mclusters_v2.scald ng.t et_s m lar y.ModelEvalAdhocApp",
    platform = "java8",
    runt  _platform = "java8",
    tags = [
        "bazel-compat ble",
        "bazel-compat ble:m grated",
        "bazel-only",
    ],
    dependenc es = [
        ":t et_s m lar y",
    ],
)

hadoop_b nary(
    na  = "dataset_topk_analys s-adhoc",
    ma n = "com.tw ter.s mclusters_v2.scald ng.t et_s m lar y.DatasetTopKAnalys sAdhocApp",
    platform = "java8",
    runt  _platform = "java8",
    tags = [
        "bazel-compat ble",
        "bazel-compat ble:m grated",
        "bazel-only",
    ],
    dependenc es = [
        ":t et_s m lar y",
    ],
)

hadoop_b nary(
    na  = "dataset_topk_analys s_dump-adhoc",
    ma n = "com.tw ter.s mclusters_v2.scald ng.t et_s m lar y.DatasetTopKAnalys sDumpApp",
    platform = "java8",
    runt  _platform = "java8",
    tags = [
        "bazel-compat ble",
        "bazel-compat ble:m grated",
        "bazel-only",
    ],
    dependenc es = [
        ":t et_s m lar y",
    ],
)

create_datarecord_datasets(
    base_na  = "t et_s m lar y_tra n_datarecords_30m n",
    platform = "java8",
    role = "cassowary",
    seg nt_type = "part  oned",
    tags = ["bazel-compat ble"],
)

create_datarecord_datasets(
    base_na  = "t et_s m lar y_test_datarecords_30m n",
    platform = "java8",
    role = "cassowary",
    seg nt_type = "part  oned",
    tags = ["bazel-compat ble"],
)

create_datarecord_datasets(
    base_na  = "t et_s m lar y_tra n_datarecords_120m n",
    platform = "java8",
    role = "cassowary",
    seg nt_type = "part  oned",
    tags = ["bazel-compat ble"],
)

create_datarecord_datasets(
    base_na  = "t et_s m lar y_test_datarecords_120m n",
    platform = "java8",
    role = "cassowary",
    seg nt_type = "part  oned",
    tags = ["bazel-compat ble"],
)

create_datasets(
    base_na  = "t et_s m lar y_unhydrated_pa rs_30m n",
    descr pt on = "30m n coocurrence tra n ng pa rs before feature hydrat on",
    java_sc ma = "com.tw ter.s mclusters_v2.thr ftjava.LabelledT etPa rs",
    platform = "java8",
    role = "cassowary",
    scala_sc ma = "com.tw ter.s mclusters_v2.thr ftscala.LabelledT etPa rs",
    seg nt_type = "part  oned",
    tags = ["bazel-compat ble"],
    java_dependenc es = [
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-java",
    ],
    scala_dependenc es = [
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
    ],
)

create_datasets(
    base_na  = "t et_s m lar y_unhydrated_pa rs_120m n",
    descr pt on = "120m n coocurrence tra n ng pa rs before feature hydrat on",
    java_sc ma = "com.tw ter.s mclusters_v2.thr ftjava.LabelledT etPa rs",
    platform = "java8",
    role = "cassowary",
    scala_sc ma = "com.tw ter.s mclusters_v2.thr ftscala.LabelledT etPa rs",
    seg nt_type = "part  oned",
    tags = ["bazel-compat ble"],
    java_dependenc es = [
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-java",
    ],
    scala_dependenc es = [
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
    ],
)
