scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/cand date_s ce/strato",
        "strato/conf g/columns/ nterests: nterests-strato-cl ent",
        "strato/src/ma n/scala/com/tw ter/strato/cl ent",
    ],
)
