scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle- nternal/mtls/src/ma n/scala/com/tw ter/f nagle/mtls/aut nt cat on",
        "f nagle- nternal/mtls/src/ma n/scala/com/tw ter/f nagle/mtls/transport",
        "f nagle/f nagle-thr ft/src/ma n/scala",
        "t etyp e/servo/ut l/src/ma n/scala:except on",
        "strato/src/ma n/scala/com/tw ter/strato/access",
        "strato/src/ma n/scala/com/tw ter/strato/data",
    ],
)
