scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "3rdparty/src/jvm/com/tw ter/storehaus:core",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator",
        "src/thr ft/com/tw ter/t  l nes/ mpress on_store:thr ft-scala",
        "st ch/st ch-core",
    ],
    exports = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "3rdparty/src/jvm/com/tw ter/storehaus:core",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator",
        "src/thr ft/com/tw ter/t  l nes/ mpress on_store:thr ft-scala",
        "st ch/st ch-core",
    ],
)
