scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/datarecord",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featuremap",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featurestorev1",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featurestorev1/featurevalue",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "src/scala/com/tw ter/ml/featurestore/l b/onl ne",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featuremap",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featurestorev1",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featurestorev1/featurevalue",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "src/scala/com/tw ter/ml/featurestore/l b/onl ne",
    ],
)
