scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "content-recom nder/server/src/ma n/scala/com/tw ter/contentrecom nder:representat on-manager-deps",
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/ut l",
        " rm / rm -core/src/ma n/scala/com/tw ter/ rm /store/common",
        "representat on-manager/server/src/ma n/scala/com/tw ter/representat on_manager/common",
        "src/scala/com/tw ter/s mclusters_v2/stores",
        "src/scala/com/tw ter/s mclusters_v2/summ ngb rd/stores",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
        "storage/cl ents/manhattan/cl ent/src/ma n/scala",
        "t etyp e/src/scala/com/tw ter/t etyp e/ut l",
    ],
)
