scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "content-recom nder/thr ft/src/ma n/thr ft:thr ft-scala",
        "f natra/ nject/ nject-core/src/ma n/scala",
        "representat on-scorer/server/src/ma n/scala/com/tw ter/representat onscorer/common",
        "representat on-scorer/server/src/ma n/scala/com/tw ter/representat onscorer/modules",
        "representat on-scorer/server/src/ma n/scala/com/tw ter/representat onscorer/scorestore",
        "representat on-scorer/server/src/ma n/scala/com/tw ter/representat onscorer/tw stlyfeatures",
        "representat on-scorer/server/src/ma n/thr ft:thr ft-scala",
        "strato/src/ma n/scala/com/tw ter/strato/fed",
        "strato/src/ma n/scala/com/tw ter/strato/fed/server",
    ],
)
