scala_l brary(
    s ces = ["*.scala"],
    platform = "java8",
    prov des = scala_art fact(
        org = "com.tw ter",
        na  = "servo-json",
        repo = art factory,
    ),
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "//:scala-reflect",
        "3rdparty/jvm/com/fasterxml/jackson/core:jackson-core",
        "3rdparty/jvm/com/fasterxml/jackson/core:jackson-datab nd",
        "3rdparty/jvm/com/googlecode/java-d ff-ut ls:d ffut ls",
        "3rdparty/jvm/org/apac /thr ft:l bthr ft",
        "scrooge/scrooge-core",
        "scrooge/scrooge-ser al zer",
        "ut l/ut l-codec/src/ma n/scala",
    ],
)
