scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    prov des = scala_art fact(
        org = "com.tw ter",
        na  = "t etyp e-t ettext",
        repo = art factory,
    ),
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/ bm/ cu: cu4j",
        "tw ter-text/l b/java/src/ma n/java/com/tw ter/tw tertext",
    ],
)
