scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = [
        "bazel-compat ble",
    ],
    dependenc es = [
        "st ch/st ch-storehaus",
        "strato/src/ma n/scala/com/tw ter/strato/fed",
        "top c-soc al-proof/server/src/ma n/scala/com/tw ter/tsp/serv ce",
        "top c-soc al-proof/server/src/ma n/thr ft:thr ft-scala",
    ],
)
