scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/query/ads",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/common",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/gate",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/qual y_factor",
        "src/scala/com/tw ter/ml/featurestore/l b",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/common",
    ],
)
