scala_l brary(
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/algeb rd:core",
        "3rdparty/jvm/com/tw ter/algeb rd:ut l",
        "servo/dec der",
        "src/scala/com/tw ter/storehaus_ nternal/manhattan",
        "src/thr ft/com/tw ter/ml/ap : nterpretable-model-java",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
    ],
)
