RECOSGRAPH_SOURCES = ["user_t et_ent y_graph.thr ft"]

create_thr ft_l brar es(
    base_na  = "user_t et_ent y_graph",
    s ces = RECOSGRAPH_SOURCES,
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependency_roots = [
        "src/thr ft/com/tw ter/recos:recos-common",
        "src/thr ft/com/tw ter/recos/features:t et",
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    prov des_java_na  = "user_t et_ent y_graph-java",
    prov des_scala_na  = "user_t et_ent y_graph-scala",
)
