scala_l brary(
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "src/scala/com/tw ter/ml/ap :ap -base",
        "src/scala/com/tw ter/ml/featurestore/catalog/features/recom ndat ons:aggregate",
        "src/scala/com/tw ter/ml/featurestore/l b/embedd ng",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/scala/com/tw ter/s mclusters_v2/common/ml",
    ],
)
