create_thr ft_l brar es(
    base_na  = "graph_feature_serv ce_thr ft",
    s ces = ["*.thr ft"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    generate_languages = [
        "java",
        # ruby  s added due to ruby dependees  n t  l nes
        "ruby",
        "scala",
        "strato",
    ],
    prov des_java_na  = "graph_feature_serv ce_thr ft_java",
    prov des_scala_na  = "graph_feature_serv ce_thr ft_scala",
)
