scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "conf gap /conf gap -core",
        "conf gap /conf gap -core/src/ma n/scala/com/tw ter/t  l nes/conf gap ",
        "servo/dec der",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/para ters/ent y_t ets",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/para ters/ n_network_t ets",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/para ters/mon or ng",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/para ters/recap",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/para ters/recap_author",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/para ters/recap_hydrat on",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/para ters/revchron",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/para ters/uteg_l ked_by_t ets",
    ],
)
