java_l brary(
    s ces = ["*.java"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/search/ ngester:legacy",
    ],
)
