scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f natra- nternal/mtls-thr ftmux/src/ma n/scala",
        "f natra/ nject/ nject-thr ft-cl ent",
        "follow-recom ndat ons-serv ce/common/src/ma n/scala/com/tw ter/follow_recom ndat ons/common/cl ents/common",
        "follow-recom ndat ons-serv ce/common/src/ma n/scala/com/tw ter/follow_recom ndat ons/common/models",
        "graph-feature-serv ce/src/ma n/thr ft/com/tw ter/graph_feature_serv ce:graph_feature_serv ce_thr ft-scala",
        "st ch/st ch-core",
    ],
)
