target(
    na  = " ngester-l b",
    dependenc es = [
        "src/java/com/tw ter/search/common/converter/earlyb rd",
        "src/java/com/tw ter/search/ ngester/model",
        "src/java/com/tw ter/search/ ngester/p pel ne/app",
        "src/java/com/tw ter/search/ ngester/p pel ne/tw ter",
        "src/java/com/tw ter/search/ ngester/p pel ne/tw ter/engage nts",
        "src/java/com/tw ter/search/ ngester/p pel ne/tw ter/f lters",
        "src/java/com/tw ter/search/ ngester/p pel ne/tw ter/kafka",
        "src/java/com/tw ter/search/ ngester/p pel ne/tw ter/thr ftparse",
        "src/java/com/tw ter/search/ ngester/p pel ne/tw ter/userupdates",
        "src/java/com/tw ter/search/ ngester/p pel ne/ut l",
        "src/java/com/tw ter/search/ ngester/ut l/jnd ",
    ],
)

jvm_b nary(
    na  = " ngester-b nary",
    basena  = " ngester",
    ma n = "com.tw ter.search. ngester.p pel ne.app. ngesterP pel neAppl cat on\\$Ma n",
    platform = "java8",
    tags = [
        "bazel-compat ble",
    ],
    dependenc es = [
        ": ngester-l b",
        "src/java/com/tw ter/search/common/logg ng:search-log4j",
    ],
)
