scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/mapdb",
        "ann/src/ma n/java/com/tw ter/ann/fa ss",
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "ann/src/ma n/scala/com/tw ter/ann/ser al zat on",
        "ann/src/ma n/thr ft/com/tw ter/ann/common:ann-common-scala",
        " d aserv ces/commons/src/ma n/scala:futuretracker",
        "src/java/com/tw ter/common_ nternal/hadoop",
        "src/java/com/tw ter/search/common/f le",
        "src/scala/com/tw ter/ml/ap /embedd ng",
    ],
    exports = [
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "src/java/com/tw ter/common_ nternal/hadoop",
        "src/java/com/tw ter/search/common/f le",
        "src/scala/com/tw ter/ml/ap /embedd ng",
    ],
)
