scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng/response/urp",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "str ngcenter/cl ent",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng/response/urp",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "str ngcenter/cl ent",
    ],
)
