scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "t etyp e/servo/ut l",
        "t etyp e/common/src/thr ft/com/tw ter/t etyp e: d a-ent y-scala",
        "t etyp e/common/src/thr ft/com/tw ter/t etyp e:t et-scala",
        "tco-ut l",
        "t etyp e/common/src/scala/com/tw ter/t etyp e/t ettext",
        "t etyp e/common/src/scala/com/tw ter/t etyp e/ut l",
        "tw ter-text/l b/java/src/ma n/java/com/tw ter/tw tertext",
    ],
)
