scala_l brary(
    s ces = ["*.scala"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/algeb rd:core",
        "3rdparty/jvm/com/tw ter/algeb rd:ut l",
        "3rdparty/jvm/com/tw ter/storehaus:algebra",
        "3rdparty/jvm/com/tw ter/storehaus:core",
        "3rdparty/src/jvm/com/tw ter/scald ng:commons",
        "3rdparty/src/jvm/com/tw ter/scald ng:core",
        "3rdparty/src/jvm/com/tw ter/summ ngb rd:batch",
        "3rdparty/src/jvm/com/tw ter/summ ngb rd:core",
        "src/java/com/tw ter/ml/ap :ap -base",
        "src/thr ft/com/tw ter/ml/ap :data-java",
        "src/thr ft/com/tw ter/ml/ap : nterpretable-model-java",
        "t  l nes/data_process ng/ml_ut l/aggregat on_fra work:common_types",
    ],
)
