scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "st ch/st ch-storehaus",
        "strato/src/ma n/scala/com/tw ter/strato/fed",
        "strato/src/ma n/scala/com/tw ter/strato/fed/server",
        "user-s gnal-serv ce/server/src/ma n/scala/com/tw ter/users gnalserv ce/conf g",
        "user-s gnal-serv ce/server/src/ma n/scala/com/tw ter/users gnalserv ce/handler",
        "user-s gnal-serv ce/server/src/ma n/scala/com/tw ter/users gnalserv ce/module",
        "user-s gnal-serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
    ],
)
