scala_l brary(
    s ces = [
        "*.scala",
    ],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "snowflake/src/ma n/scala/com/tw ter/snowflake/ d",
        "ut l/ut l-core:ut l-core-ut l",
    ],
)
