scala_l brary(
    na  = "user_sess on_ nj",
    s ces = ["UserSess on nject on.scala"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/b ject on:scrooge",
        "src/scala/com/tw ter/scald ng_ nternal/mult format/format",
        "src/thr ft/com/tw ter/user_sess on_store:thr ft-scala",
    ],
)

scala_l brary(
    na  = "edge_l st_ nject on",
    s ces = ["EdgeL st nject on.scala"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/b ject on:scrooge",
        "src/scala/com/tw ter/scald ng_ nternal/mult format/format",
        "src/thr ft/com/tw ter/ nteract on_graph: nteract on_graph-scala",
    ],
)
