package com.tw ter.v s b l y.rules

 mport com.tw ter.v s b l y.features.AuthorScreenNa 
 mport com.tw ter.v s b l y.features.Feature
 mport com.tw ter.v s b l y.features.FeatureMap
 mport com.tw ter.v s b l y.features.RawQuery
 mport com.tw ter.v s b l y.models.SafetyLevel
 mport com.tw ter.v s b l y.models.SafetyLevel._

object RuleBase {

  val DeprecatedFeatures: Seq[Feature[_]] =
    Seq(AuthorScreenNa , RawQuery)

  val RuleMap: Map[SafetyLevel, V s b l yPol cy] = Map(
    Access nternalPromotedContent ->  nternalPromotedContentPol cy,
    AllSubscr bedL sts -> AllSubscr bedL stsPol cy,
    AdsBus nessSett ngs -> AdsBus nessSett ngsPol cy,
    AdsCampa gn -> AdsCampa gnPol cy,
    AdsManager -> AdsManagerPol cy,
    AdsReport ngDashboard -> AdsReport ngDashboardPol cy,
    Appeals -> AppealsPol cy,
    Art cleT etT  l ne -> Art cleT etT  l nePol cy,
    BaseQ g -> BaseQ gPol cy,
    B rdwatchNoteAuthor -> B rdwatchNoteAuthorPol cy,
    B rdwatchNoteT etsT  l ne -> B rdwatchNoteT etsT  l nePol cy,
    B rdwatchNeedsY  lpNot f cat ons -> B rdwatchNeedsY  lpNot f cat onsPol cy,
    BlockMuteUsersT  l ne -> BlockMuteUsersT  l nePol cy,
    BrandSafety -> BrandSafetyPol cy,
    CardPollVot ng -> CardPollVot ngPol cy,
    CardsServ ce -> CardsServ cePol cy,
    Commun  es -> Commun  esPol cy,
    ContentControlTool nstall -> ContentControlTool nstallPol cy,
    Conversat onFocalPrehydrat on -> Conversat onFocalPrehydrat onPol cy,
    Conversat onFocalT et -> Conversat onFocalT etPol cy,
    Conversat on njectedT et -> Conversat on njectedT etPol cy,
    Conversat onReply -> Conversat onReplyPol cy,
    CuratedTrendsRepresentat veT et -> CuratedTrendsRepresentat veT etPol cy,
    Curat onPol cyV olat ons -> Curat onPol cyV olat onsPol cy,
    Follow ngAndFollo rsUserL st -> Follow ngAndFollo rsUserL stPol cy,
    DeprecatedSafetyLevel -> F lterNonePol cy,
    DevPlatformGetL stT ets -> DevPlatformGetL stT etsPol cy,
    DesFollow ngAndFollo rsUserL st -> Follow ngAndFollo rsUserL stPol cy,
    DesHo T  l ne -> DESHo T  l nePol cy,
    DesQuoteT etT  l ne -> DesQuoteT etT  l nePol cy,
    DesRealt   -> DESRealt  Pol cy,
    DesRealt  SpamEnr ch nt -> DESRealt  SpamEnr ch ntPol cy,
    DesRealt  T etF lter -> DESRealt  SpamEnr ch ntPol cy,
    DesRet et ngUsers -> DESRet et ngUsersPol cy,
    DesT etDeta l -> DesT etDeta lPol cy,
    DesT etL k ngUsers -> DEST etL k ngUsersPol cy,
    DesUserBookmarks -> DESUserBookmarksPol cy,
    DesUserL kedT ets -> DESUserL kedT etsPol cy,
    DesUser nt ons -> DESUser nt onsPol cy,
    DesUserT ets -> DESUserT etsPol cy,
    DevPlatformCompl anceStream -> DevPlatformCompl anceStreamPol cy,
    D rect ssages -> D rect ssagesPol cy,
    D rect ssagesConversat onL st -> D rect ssagesConversat onL stPol cy,
    D rect ssagesConversat onT  l ne -> D rect ssagesConversat onT  l nePol cy,
    D rect ssages nbox -> D rect ssages nboxPol cy,
    D rect ssagesMutedUsers -> D rect ssagesMutedUsersPol cy,
    D rect ssagesP nned -> D rect ssagesP nnedPol cy,
    D rect ssagesSearch -> D rect ssagesSearchPol cy,
    Ed  toryT  l ne -> Ed  toryT  l nePol cy,
    ElevatedQuoteT etT  l ne -> ElevatedQuoteT etT  l nePol cy,
    EmbeddedT et -> EmbeddedT etsPol cy,
    EmbedsPubl c nterestNot ce -> EmbedsPubl c nterestNot cePol cy,
    EmbedT etMarkup -> EmbedT etMarkupPol cy,
    Wr ePathL m edAct onsEnforce nt -> Wr ePathL m edAct onsEnforce ntPol cy,
    F lterAll -> F lterAllPol cy,
    F lterAllPlaceholder -> F lterAllPol cy,
    F lterNone -> F lterNonePol cy,
    F lterDefault -> F lterDefaultPol cy,
    Follo dTop csT  l ne -> Follo dTop csT  l nePol cy,
    Follo rConnect ons -> Follo rConnect onsPol cy,
    ForDevelop ntOnly -> ForDevelop ntOnlyPol cy,
    Fr endsFollow ngL st -> Fr endsFollow ngL stPol cy,
    GraphqlDefault -> GraphqlDefaultPol cy,
    GryphonDecksAndColumns -> GryphonDecksAndColumnsShar ngPol cy,
    Human zat onNudge -> Human zat onNudgePol cy,
    K c nS nkDevelop nt -> K c nS nkDevelop ntPol cy,
    L st ader -> L st aderPol cy,
    L st mbersh ps -> L st mbersh psPol cy,
    L stOwnersh ps -> L stOwnersh psPol cy,
    L stRecom ndat ons -> L stRecom ndat onsPol cy,
    L stSearch -> L stSearchPol cy,
    L stSubscr pt ons -> L stSubscr pt onsPol cy,
    L veP pel neEngage ntCounts -> L veP pel neEngage ntCountsPol cy,
    L veV deoT  l ne -> L veV deoT  l nePol cy,
    Mag cRecs -> Mag cRecsPol cy,
    Mag cRecsAggress ve -> Mag cRecsAggress vePol cy,
    Mag cRecsAggress veV2 -> Mag cRecsAggress veV2Pol cy,
    Mag cRecsV2 -> Mag cRecsV2Pol cy,
    M n mal -> M n malPol cy,
    ModeratedT etsT  l ne -> ModeratedT etsT  l nePol cy,
    Mo nts -> Mo ntsPol cy,
    NearbyT  l ne -> NearbyT  l nePol cy,
    NewUserExper ence -> NewUserExper encePol cy,
    Not f cat ons b s -> Not f cat ons b sPol cy,
    Not f cat onsPlatform -> Not f cat onsPlatformPol cy,
    Not f cat onsPlatformPush -> Not f cat onsPlatformPushPol cy,
    Not f cat onsQ g -> Not f cat onsQ gPol cy,
    Not f cat onsRead -> Not f cat onsReadPol cy,
    Not f cat onsT  l neDev ceFollow -> Not f cat onsT  l neDev ceFollowPol cy,
    Not f cat onsWr e -> Not f cat onsWr ePol cy,
    Not f cat onsWr erV2 -> Not f cat onsWr erV2Pol cy,
    Not f cat onsWr erT etHydrator -> Not f cat onsWr erT etHydratorPol cy,
    Prof leM xer d a -> Prof leM xer d aPol cy,
    Prof leM xerFavor es -> Prof leM xerFavor esPol cy,
    Qu ckPromoteT etEl g b l y -> Qu ckPromoteT etEl g b l yPol cy,
    QuoteT etT  l ne -> QuoteT etT  l nePol cy,
    QuotedT etRules -> QuotedT etRulesPol cy,
    Recom ndat ons -> Recom ndat onsPol cy,
    RecosV deo -> RecosV deoPol cy,
    RecosWr ePath -> RecosWr ePathPol cy,
    Repl esGroup ng -> Repl esGroup ngPol cy,
    ReportCenter -> ReportCenterPol cy,
    Return ngUserExper ence -> Return ngUserExper encePol cy,
    Return ngUserExper enceFocalT et -> Return ngUserExper enceFocalT etPol cy,
    Revenue -> RevenuePol cy,
    R oAct onedT etT  l ne -> R oAct onedT etT  l nePol cy,
    SearchHydrat on -> SearchHydrat onPol cy,
    SearchM xerSrpM n mal -> SearchM xerSrpM n malPol cy,
    SearchM xerSrpStr ct -> SearchM xerSrpStr ctPol cy,
    SearchLatest -> SearchLatestPol cy,
    SearchPeopleSrp -> SearchPeopleSrpPol cy,
    SearchPeopleTypea ad -> SearchPeopleTypea adPol cy,
    SearchPhoto -> SearchPhotoPol cy,
    SearchTrendTakeoverPromotedT et -> SearchTrendTakeoverPromotedT etPol cy,
    SearchTop -> SearchTopPol cy,
    SearchTopQ g -> SearchTopQ gPol cy,
    SearchV deo -> SearchV deoPol cy,
    SearchBlenderUserRules -> SearchBlenderUserRulesPol cy,
    SearchLatestUserRules -> SearchLatestUserRulesPol cy,
    Shopp ngManagerSpyMode -> Shopp ngManagerSpyModePol cy,
    S gnalsReact ons -> S gnalsReact onsPol cy,
    S gnalsT etReact ngUsers -> S gnalsT etReact ngUsersPol cy,
    Soc alProof -> Soc alProofPol cy,
    Soft ntervent onP vot -> Soft ntervent onP votPol cy,
    SpaceFleetl ne -> SpaceFleetl nePol cy,
    SpaceHo T  l neUprank ng -> SpaceHo T  l neUprank ngPol cy,
    SpaceJo nScreen -> SpaceJo nScreenPol cy,
    SpaceNot f cat ons -> SpaceNot f cat onsPol cy,
    Spaces -> SpacesPol cy,
    SpacesPart c pants -> SpacesPart c pantsPol cy,
    SpacesSellerAppl cat onStatus -> SpacesSellerAppl cat onStatusPol cy,
    SpacesShar ng -> SpacesShar ngPol cy,
    SpaceT etAvatarHo T  l ne -> SpaceT etAvatarHo T  l nePol cy,
    St ckersT  l ne -> St ckersT  l nePol cy,
    StratoExtL m edEngage nts -> StratoExtL m edEngage ntsPol cy,
    StreamServ ces -> StreamServ cesPol cy,
    SuperFollo rConnect ons -> SuperFollo rConnect onsPol cy,
    SuperL ke -> SuperL kePol cy,
    Test -> TestPol cy,
    T  l neContentControls -> T  l neContentControlsPol cy,
    T  l neConversat ons -> T  l neConversat onsPol cy,
    T  l neConversat onsDownrank ng -> T  l neConversat onsDownrank ngPol cy,
    T  l neConversat onsDownrank ngM n mal -> T  l neConversat onsDownrank ngM n malPol cy,
    T  l neFollow ngAct v y -> T  l neFollow ngAct v yPol cy,
    T  l neHo  -> T  l neHo Pol cy,
    T  l neHo Commun  es -> T  l neHo Commun  esPol cy,
    T  l neHo Hydrat on -> T  l neHo Hydrat onPol cy,
    T  l neHo PromotedHydrat on -> T  l neHo PromotedHydrat onPol cy,
    T  l neHo Recom ndat ons -> T  l neHo Recom ndat onsPol cy,
    T  l neHo Top cFollowRecom ndat ons -> T  l neHo Top cFollowRecom ndat onsPol cy,
    T  l neScorer -> T  l neScorerPol cy,
    Top csLand ngPageTop cRecom ndat ons -> Top csLand ngPageTop cRecom ndat onsPol cy,
    ExploreRecom ndat ons -> ExploreRecom ndat onsPol cy,
    T  l ne nject on -> T  l ne nject onPol cy,
    T  l ne nt ons -> T  l ne nt onsPol cy,
    T  l neModeratedT etsHydrat on -> T  l neModeratedT etsHydrat onPol cy,
    T  l neHo Latest -> T  l neHo LatestPol cy,
    T  l neL kedBy -> T  l neL kedByPol cy,
    T  l neRet etedBy -> T  l neRet etedByPol cy,
    T  l neSuperL kedBy -> T  l neSuperL kedByPol cy,
    T  l neBookmark -> T  l neBookmarkPol cy,
    T  l ne d a -> T  l ne d aPol cy,
    T  l neReact veBlend ng -> T  l neReact veBlend ngPol cy,
    T  l neFavor es -> T  l neFavor esPol cy,
    T  l neFavor esSelfV ew -> T  l neFavor esSelfV ewPol cy,
    T  l neL sts -> T  l neL stsPol cy,
    T  l neProf le -> T  l neProf lePol cy,
    T  l neProf leAll -> T  l neProf leAllPol cy,
    T  l neProf leSpaces -> T  l neProf leSpacesPol cy,
    T  l neProf leSuperFollows -> T  l neProf leSuperFollowsPol cy,
    T  l neFocalT et -> T  l neFocalT etPol cy,
    Tombston ng -> Tombston ngPol cy,
    Top cRecom ndat ons -> Top cRecom ndat onsPol cy,
    TrendsRepresentat veT et -> TrendsRepresentat veT etPol cy,
    TrustedFr endsUserL st -> TrustedFr endsUserL stPol cy,
    Tw terDelegateUserL st -> Tw terDelegateUserL stPol cy,
    T etDeta l -> T etDeta lPol cy,
    T etDeta lNonToo -> T etDeta lNonTooPol cy,
    T etDeta lW h nject onsHydrat on -> T etDeta lW h nject onsHydrat onPol cy,
    T etEngagers -> T etEngagersPol cy,
    T etReplyNudge -> T etReplyNudgePol cy,
    T etScopedT  l ne -> T etScopedT  l nePol cy,
    T etWr esAp  -> T etWr esAp Pol cy,
    Tw terArt cleCompose -> Tw terArt cleComposePol cy,
    Tw terArt cleProf leTab -> Tw terArt cleProf leTabPol cy,
    Tw terArt cleRead -> Tw terArt cleReadPol cy,
    UserM lestoneRecom ndat on -> UserM lestoneRecom ndat onPol cy,
    UserProf le ader -> UserProf le aderPol cy,
    UserScopedT  l ne -> UserScopedT  l nePol cy,
    UserSearchSrp -> UserSearchSrpPol cy,
    UserSearchTypea ad -> UserSearchTypea adPol cy,
    UserSelfV ewOnly -> UserSelfV ewOnlyPol cy,
    UserSett ngs -> UserSett ngsPol cy,
    V deoAds -> V deoAdsPol cy,
    Z pb rdConsu rArch ves -> Z pb rdConsu rArch vesPol cy,
    T etAward -> T etAwardPol cy,
  )

  def removeUnusedFeaturesFromFeatureMap(
    featureMap: FeatureMap,
    rules: Seq[Rule],
  ): FeatureMap = {
    val features nSafetyLevel: Set[Feature[_]] =
      RuleBase.getFeaturesForRules(rules)
    val f lteredMap = featureMap.map.f lterKeys(features nSafetyLevel.conta ns(_))

    new FeatureMap(f lteredMap, featureMap.constantMap)
  }

  def getFeaturesForRules(rules: Seq[Rule]): Set[Feature[_]] = {
    rules.flatMap { r: Rule =>
      r.featureDependenc es ++ r.opt onalFeatureDependenc es
    }.toSet
  }

  def hasT etRules(safetyLevel: SafetyLevel): Boolean = RuleMap(safetyLevel).t etRules.nonEmpty
  def hasUserRules(safetyLevel: SafetyLevel): Boolean = RuleMap(safetyLevel).userRules.nonEmpty
  def hasCardRules(safetyLevel: SafetyLevel): Boolean = RuleMap(safetyLevel).cardRules.nonEmpty
  def hasDmRules(safetyLevel: SafetyLevel): Boolean = RuleMap(safetyLevel).dmRules.nonEmpty
  def hasDmConversat onRules(safetyLevel: SafetyLevel): Boolean = RuleMap(
    safetyLevel).dmConversat onRules.nonEmpty
  def hasDmEventRules(safetyLevel: SafetyLevel): Boolean = RuleMap(
    safetyLevel).dmEventRules.nonEmpty
}
