scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = [
        "bazel-compat ble",
    ],
    dependenc es = [
        "3rdparty/jvm/org/lz4:lz4-java",
        "content-recom nder/thr ft/src/ma n/thr ft:thr ft-scala",
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/store",
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/store/ alth",
        "st ch/st ch-storehaus",
        "top c-soc al-proof/server/src/ma n/thr ft:thr ft-scala",
    ],
)
