java_l brary(
    s ces = ["*.java"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/com/google/ nject:gu ce",
        "3rdparty/jvm/com/tw ter/b ject on:core",
        "3rdparty/jvm/commons-lang",
        "3rdparty/jvm/org/apac /thr ft",
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "ann/src/ma n/thr ft/com/tw ter/ann/common:ann-common-java",
        " d aserv ces/commons/src/ma n/scala:futuretracker",
        "scrooge/scrooge-core",
        "src/java/com/tw ter/search/common/f le",
    ],
)
