scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/ut l",
        " rm / rm -core/src/ma n/scala/com/tw ter/ rm /store/common",
        "relevance-platform/src/ma n/scala/com/tw ter/relevance_platform/common/ nject on",
        "representat on-manager/cl ent/src/ma n/scala/com/tw ter/representat on_manager",
        "representat on-manager/cl ent/src/ma n/scala/com/tw ter/representat on_manager/conf g",
        "representat on-scorer/server/src/ma n/scala/com/tw ter/representat onscorer/common",
        "src/scala/com/tw ter/s mclusters_v2/score",
        "src/scala/com/tw ter/top c_recos/common",
        "src/scala/com/tw ter/top c_recos/stores",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
        "src/thr ft/com/tw ter/top c_recos:top c_recos-thr ft-scala",
        "st ch/st ch-storehaus",
    ],
)
