create_thr ft_l brar es(
    base_na  = "thr ft",
    s ces = ["**/*.thr ft"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    prov des_java_na  = "servo-repo-thr ft-java",
    prov des_scala_na  = "servo-repo-thr ft-scala",
)
