scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator/featurestorev1",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "st ch/st ch-core",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/feature_hydrator/featurestorev1",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "st ch/st ch-core",
    ],
)
