scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "dspb dder/thr ft/src/ma n/thr ft/com/tw ter/dspb dder/commons:thr ft-scala",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "src/thr ft/com/tw ter/ads/adserver:adserver_rpc-scala",
    ],
    exports = [
        "dspb dder/thr ft/src/ma n/thr ft/com/tw ter/dspb dder/commons:thr ft-scala",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne",
        "src/thr ft/com/tw ter/ads/adserver:adserver_rpc-scala",
    ],
)
