scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/fasterxml/jackson:jackson-module-scala",
        "3rdparty/jvm/com/fasterxml/jackson/core:jackson-annotat ons",
        "conf gap /conf gap -core/src/ma n/scala/com/tw ter/t  l nes/conf gap ",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common/ dent f er",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/p pel ne_fa lure",
        "ut l/ut l-core:ut l-core-ut l",
    ],
    exports = [
        "3rdparty/jvm/com/fasterxml/jackson:jackson-module-scala",
        "3rdparty/jvm/com/fasterxml/jackson/core:jackson-annotat ons",
        "conf gap /conf gap -core/src/ma n/scala/com/tw ter/t  l nes/conf gap ",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/marshall ng",
        "ut l/ut l-core:ut l-core-ut l",
    ],
)
