scala_l brary(
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f natra/ nject/ nject-core/src/ma n/scala",
        "follow-recom ndat ons-serv ce/common/src/ma n/scala/com/tw ter/follow_recom ndat ons/common/base",
        "follow-recom ndat ons-serv ce/common/src/ma n/scala/com/tw ter/follow_recom ndat ons/common/models",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/marshaller",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/funct onal_component/marshaller/request",
        "st ch/st ch-core",
        "ut l/ut l-slf4j-ap /src/ma n/scala",
    ],
)
