python3_l brary(
    na  = "l bs_py3",
    s ces = ["*.py"],
    dependenc es = [
        "src/python/tw ter/deepb rd/ o",
        "twml:twml-nodeps",
    ],
)

python37_b nary(
    na  = "score",
    s ce = "score.py",
    dependenc es = [
        ":l bs_py3",
        "3rdparty/python/_closures/src/python/tw ter/deepb rd/projects/t  l nes/scr pts/models/earlyb rd/lolly:score",
        "twml",
    ],
)
