scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "conf gap /conf gap -core/src/ma n/scala/com/tw ter/t  l nes/conf gap ",
        "src/thr ft/com/tw ter/recos/user_t et_ent y_graph:user_t et_ent y_graph-scala",
        "src/thr ft/com/tw ter/search:earlyb rd-scala",
        "src/thr ft/com/tw ter/search/common:constants-scala",
        "src/thr ft/com/tw ter/search/common:features-scala",
        "t  l neranker/common:model",
        "t  l neranker/server/src/ma n/scala/com/tw ter/t  l neranker/recap/model",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/cl ents/g zmoduck",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/model/t et",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/ut l",
        "t  l nes/src/ma n/scala/com/tw ter/t  l nes/v s b l y/model",
        "ut l/ut l-core:ut l-core-ut l",
    ],
    exports = [
        "src/thr ft/com/tw ter/recos/user_t et_ent y_graph:user_t et_ent y_graph-scala",
    ],
)
