# S mClusters embedd ng store enable / d sable dec der values

# ---------- Dark Traff c Proxy ----------
dark_traff c_f lter:
  com nt: Proport on of t  requests that are forwarded as dark traff c to t  proxy
  default_ava lab l y: 0

# T et embedd ngs
enable_LogFavBasedT et_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_LogFavLongestL2Embedd ngT et_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

# Ent y embedd ngs
enable_FavTfgTop c_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000


enable_LogFavBasedKgoApeTop c_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

# KnownFor embedd ngs
enable_FavBasedProducer_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_FollowBasedProducer_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_RelaxedAggregatableLogFavBasedProducer_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

#  nterested n embedd ngs
enable_LogFavBasedUser nterested nFromAPE_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_FollowBasedUser nterested nFromAPE_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_FavBasedUser nterested n_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_FollowBasedUser nterested n_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_LogFavBasedUser nterested n_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_F lteredUser nterested n_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_Unf lteredUser nterested n_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_LogFavBasedUser nterestedMaxpool ngAddressBookFrom  APE_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_LogFavBasedUser nterestedAverageAddressBookFrom  APE_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_LogFavBasedUser nterestedBooktypeMaxpool ngAddressBookFrom  APE_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_LogFavBasedUser nterestedLargestD mMaxpool ngAddressBookFrom  APE_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_LogFavBasedUser nterestedLouva nMaxpool ngAddressBookFrom  APE_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_LogFavBasedUser nterestedConnectedMaxpool ngAddressBookFrom  APE_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000

enable_UserNext nterested n_Model20m145k2020:
  com nt: "Enable t  read traff c to (embedd ngType, modelVers on) from 0% to 100%. 0  ans return EMPTY for all requests."
  default_ava lab l y: 10000
