java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/ nject:gu ce",
        "3rdparty/jvm/commons- o",
        "3rdparty/jvm/org/yaml:snakeyaml",
        "f nagle/f nagle-core/src/ma n",
        "src/java/com/tw ter/common/ut l:system-mocks",
        "src/java/com/tw ter/search/common/ut l/ o/per od c",
    ],
)
