scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "abdec der/src/ma n/scala",
        "dec der",
        "featuresw c s/featuresw c s-core/src/ma n/scala",
        "featuresw c s/featuresw c s-core/src/ma n/scala/com/tw ter/featuresw c s/v2/bu lder",
        "st ch/st ch-core",
        "tw ter-conf g/yaml",
        "ut l- nternal/scr be",
        "ut l/ut l-logg ng/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala",
    ],
)
