scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    scalac_plug ns = ["no-roomba"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/selector/sorter",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featuremap/featurestorev1",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featurestorev1",
    ],
    exports = [
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/selector/sorter",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featuremap/featurestorev1",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featurestorev1",
    ],
)
