scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/squareup/okhttp:okhttp3",
        "f nagle/f nagle-mux/src/ma n/scala",
        "src/thr ft/com/tw ter/g zmoduck:user-thr ft-scala",
        "src/thr ft/com/tw ter/search/common:constants-scala",
        "src/thr ft/com/tw ter/t etyp e:t et-scala",
        "st ch/st ch-core",
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/models",
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/ut l",
    ],
)
