java_l brary(
    s ces = ["*.java"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/google/guava",
        "src/java/com/tw ter/search/common/part  on ng/base",
        "src/java/com/tw ter/search/common/sc ma/base",
        "src/java/com/tw ter/search/common/sc ma/earlyb rd",
        "src/java/com/tw ter/search/queryparser/query:core-query-nodes",
        "src/java/com/tw ter/search/queryparser/query/search:search-query-nodes",
    ],
)
