scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    scalac_plug ns = ["no-roomba"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/cand date_s ce/ads",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/decorator/urt",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date/ads",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/query/ads",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/cand date",
    ],
    exports = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/cand date_s ce/ads",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/cand date/ads",
        "product-m xer/component-l brary/src/ma n/scala/com/tw ter/product_m xer/component_l brary/model/query/ads",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/p pel ne/cand date",
    ],
)
