scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        " d aserv ces/commons/src/ma n/thr ft:thr ft-scala",
        "scrooge/scrooge-core/src/ma n/scala",
        "t etyp e/servo/ut l/src/ma n/scala",
        "t etyp e/common/src/thr ft/com/tw ter/t etyp e: d a-ent y-scala",
        "t etyp e/common/src/thr ft/com/tw ter/t etyp e:t et-scala",
        "tco-ut l",
        "t etyp e/common/src/scala/com/tw ter/t etyp e/ut l",
        "ut l/ut l-logg ng/src/ma n/scala/com/tw ter/logg ng",
    ],
)
