scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "ann/src/ma n/scala/com/tw ter/ann/ser al zat on",
        "ann/src/ma n/thr ft/com/tw ter/ann/ser al zat on:ser al zat on-scala",
        "src/java/com/tw ter/search/common/f le",
    ],
)
