scala_l brary(
    na  = "tls-favs",
    s ces = ["TlsFavsServ ce.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/apac /kafka:kafka-cl ents",
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "kafka/l bs/src/ma n/scala/com/tw ter/kafka/cl ent/processor",
        "src/thr ft/com/tw ter/t  l neserv ce/server/ nternal:thr ft-scala",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:tls-favs",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "cl ent-event",
    s ces = ["Cl entEventServ ce.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/apac /kafka:kafka-cl ents",
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "kafka/l bs/src/ma n/scala/com/tw ter/kafka/cl ent/processor",
        "twadoop_conf g/conf gurat on/log_categor es/group/scr bel b:cl ent_event-scala",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:cl ent-event",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "t etyp e-event",
    s ces = ["T etyp eEventServ ce.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/apac /kafka:kafka-cl ents",
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "kafka/l bs/src/ma n/scala/com/tw ter/kafka/cl ent/processor",
        "twadoop_conf g/conf gurat on/log_categor es/group/scr bel b:cl ent_event-scala",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:t etyp e-event",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "soc al-graph-event",
    s ces = ["Soc alGraphServ ce.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/apac /kafka:kafka-cl ents",
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "kafka/l bs/src/ma n/scala/com/tw ter/kafka/cl ent/processor",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:soc al-graph-event",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "ema l-not f cat on-event",
    s ces = ["Ema lNot f cat onEventServ ce.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/apac /kafka:kafka-cl ents",
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "kafka/l bs/src/ma n/scala/com/tw ter/kafka/cl ent/processor",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:ema l-not f cat on-event",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "user-mod f cat on-event",
    s ces = ["UserMod f cat onServ ce.scala"],
    tags = [
        "bazel-compat ble",
        "bazel-only",
    ],
    dependenc es = [
        "3rdparty/jvm/org/apac /kafka:kafka-cl ents",
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "kafka/l bs/src/ma n/scala/com/tw ter/kafka/cl ent/processor",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:user-mod f cat on-event",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "ads-callback-engage nts",
    s ces = ["AdsCallbackEngage ntsServ ce.scala"],
    tags = [
        "bazel-compat ble",
        "bazel-only",
    ],
    dependenc es = [
        "3rdparty/jvm/org/apac /kafka:kafka-cl ents",
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "kafka/l bs/src/ma n/scala/com/tw ter/kafka/cl ent/processor",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:ads-callback-engage nts",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "favor e-arch val-events",
    s ces = ["Favor eArch valEventsServ ce.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/apac /kafka:kafka-cl ents",
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "kafka/l bs/src/ma n/scala/com/tw ter/kafka/cl ent/processor",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:favor e-arch val-events",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "ret et-arch val-events",
    s ces = ["Ret etArch valEventsServ ce.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/apac /kafka:kafka-cl ents",
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "kafka/l bs/src/ma n/scala/com/tw ter/kafka/cl ent/processor",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:ret et-arch val-events",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "rekey-uua",
    s ces = ["RekeyUuaServ ce.scala"],
    tags = [
        "bazel-compat ble",
        "bazel-only",
    ],
    dependenc es = [
        "3rdparty/jvm/org/apac /kafka:kafka-cl ents",
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "kafka/l bs/src/ma n/scala/com/tw ter/kafka/cl ent/processor",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:rekey-uua",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "rekey-uua- es ce",
    s ces = ["RekeyUua es ceServ ce.scala"],
    tags = [
        "bazel-compat ble",
        "bazel-only",
    ],
    dependenc es = [
        "3rdparty/jvm/org/apac /kafka:kafka-cl ents",
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "kafka/l bs/src/ma n/scala/com/tw ter/kafka/cl ent/processor",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:rekey-uua- es ce",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)

scala_l brary(
    na  = "enr ch nt-planner",
    s ces = ["Enr ch ntPlannerServ ce.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "dec der/src/ma n/scala",
        "f natra- nternal/dec der/src/ma n/scala",
        "f natra- nternal/kafka-streams/kafka-streams/src/ma n/scala",
        "f natra- nternal/kafka/src/ma n/scala/com/tw ter/f natra/kafka/producers",
        "f natra- nternal/mtls-thr ftmux/src/ma n/scala",
        "f natra- nternal/mtls/src/ma n/scala",
        "kafka/f nagle-kafka/f natra-kafka-streams/kafka-streams-stat c-part  on ng/src/ma n/scala",
        "kafka/f nagle-kafka/f natra-kafka-streams/kafka-streams/src/ma n/scala",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "un f ed_user_act ons/enr c r/src/ma n/scala/com/tw ter/un f ed_user_act ons/enr c r/dr ver",
        "un f ed_user_act ons/enr c r/src/ma n/scala/com/tw ter/un f ed_user_act ons/enr c r/hydrator:noop",
        "un f ed_user_act ons/enr c r/src/ma n/scala/com/tw ter/un f ed_user_act ons/enr c r/part  oner:default",
        "un f ed_user_act ons/enr c r/src/ma n/thr ft/com/tw ter/un f ed_user_act ons/enr c r/ nternal: nternal-scala",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
    ],
)

scala_l brary(
    na  = "enr c r",
    s ces = ["Enr c rServ ce.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f natra- nternal/kafka-streams/kafka-streams/src/ma n/scala",
        "f natra- nternal/mtls/src/ma n/scala",
        "f natra/ nject/ nject-server/src/ma n/scala/com/tw ter/ nject/server",
        "graphql/thr ft/src/ma n/thr ft/com/tw ter/graphql:graphql-scala",
        "kafka/f nagle-kafka/f natra-kafka-streams/kafka-streams-stat c-part  on ng/src/ma n/scala",
        "kafka/f nagle-kafka/f natra-kafka-streams/kafka-streams/src/ma n/scala",
        "kafka/f nagle-kafka/f natra-kafka/src/ma n/scala",
        "tw ter-server/server/src/ma n/scala",
        "un f ed_user_act ons/enr c r/src/ma n/scala/com/tw ter/un f ed_user_act ons/enr c r/dr ver",
        "un f ed_user_act ons/enr c r/src/ma n/scala/com/tw ter/un f ed_user_act ons/enr c r/graphql",
        "un f ed_user_act ons/enr c r/src/ma n/scala/com/tw ter/un f ed_user_act ons/enr c r/hydrator:default",
        "un f ed_user_act ons/enr c r/src/ma n/scala/com/tw ter/un f ed_user_act ons/enr c r/part  oner:default",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:cac ",
        "un f ed_user_act ons/serv ce/src/ma n/scala/com/tw ter/un f ed_user_act ons/serv ce/module:graphql-cl ent",
        "un f ed_user_act ons/thr ft/src/ma n/thr ft/com/tw ter/un f ed_user_act ons:un f ed_user_act ons-scala",
        "ut l/ut l-app/src/ma n/scala",
        "ut l/ut l-stats/src/ma n/scala/com/tw ter/f nagle/stats",
    ],
)
