scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle- nternal/mtls/src/ma n/scala/com/tw ter/f nagle/mtls/aut nt cat on",
        "f nagle/f nagle-stats",
        "f natra/ nject/ nject-core/src/ma n/scala",
        "fr gate/fr gate-common/src/ma n/scala/com/tw ter/fr gate/common/ut l",
        " nterests-serv ce/thr ft/src/ma n/thr ft:thr ft-scala",
        "representat on-manager/server/src/ma n/scala/com/tw ter/representat on_manager/common",
        "servo/ut l",
        "src/scala/com/tw ter/storehaus_ nternal/manhattan",
        "src/scala/com/tw ter/storehaus_ nternal/ mcac ",
        "src/scala/com/tw ter/storehaus_ nternal/ut l",
        "strato/src/ma n/scala/com/tw ter/strato/cl ent",
    ],
)
