scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/b ject on:core",
        "3rdparty/jvm/com/tw ter/b ject on:scrooge",
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "src/scala/com/tw ter/ml/ap /embedd ng",
        "storage/cl ents/manhattan",
    ],
)
