scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/javax/ nject:javax. nject",
        "dec der/src/ma n/scala",
        "f nagle/f nagle-base-http/src/ma n",
        "f nagle/f nagle-core/src/ma n",
        "f nagle/f nagle-http/src/ma n/scala",
        "servo/dec der",
        "src/scala/com/tw ter/s mclusters_v2/common",
    ],
)
