scala_l brary(
    na  = "default",
    s ces = [
        "AbstractHydrator.scala",
        "DefaultHydrator.scala",
    ],
    tags = ["bazel-compat ble"],
    dependenc es = [
        ":base",
        "featuresw c s/dynmap/src/ma n/scala/com/tw ter/dynmap:dynmap-core",
        "un f ed_user_act ons/enr c r/src/ma n/scala/com/tw ter/un f ed_user_act ons/enr c r",
        "un f ed_user_act ons/enr c r/src/ma n/scala/com/tw ter/un f ed_user_act ons/enr c r/graphql",
        "un f ed_user_act ons/enr c r/src/ma n/scala/com/tw ter/un f ed_user_act ons/enr c r/hcac ",
        "un f ed_user_act ons/enr c r/src/ma n/thr ft/com/tw ter/un f ed_user_act ons/enr c r/ nternal: nternal-scala",
    ],
)

scala_l brary(
    na  = "noop",
    s ces = ["NoopHydrator.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        ":base",
        "un f ed_user_act ons/enr c r/src/ma n/scala/com/tw ter/un f ed_user_act ons/enr c r",
        "un f ed_user_act ons/enr c r/src/ma n/thr ft/com/tw ter/un f ed_user_act ons/enr c r/ nternal: nternal-scala",
    ],
)

scala_l brary(
    na  = "base",
    s ces = ["Hydrator.scala"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "un f ed_user_act ons/enr c r/src/ma n/thr ft/com/tw ter/un f ed_user_act ons/enr c r/ nternal: nternal-scala",
    ],
)
