scala_l brary(
    s ces = ["**/*.scala"],
    platform = "java8",
    prov des = scala_art fact(
        org = "com.tw ter",
        na  = "servo-dec der",
        repo = art factory,
    ),
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "dec der",
        "f nagle/f nagle-core/src/ma n",
        "t etyp e/servo/ut l",
        "tw ter-server- nternal",
        "tw ter-server/server/src/ma n/scala",
    ],
)
