scala_l brary(
    platform = "java11",
    str ct_deps = False,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/org/apac /thr ft:l bthr ft",
        "f natra- nternal/ ssag ng/kafka/src/ma n/scala",
        "servo/repo/src/ma n/scala",
        "src/thr ft/com/tw ter/recos:recos- njector-scala",
        "src/thr ft/com/tw ter/recos:recos- nternal-scala",
    ],
)
