scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle- nternal/mtls/src/ma n/scala/com/tw ter/f nagle/mtls/aut nt cat on",
        "f nagle/f nagle-stats",
        "f natra/ nject/ nject-core/src/ma n/scala",
        "representat on-manager/cl ent/src/ma n/scala/com/tw ter/representat on_manager",
        "representat on-manager/cl ent/src/ma n/scala/com/tw ter/representat on_manager/conf g",
        "representat on-manager/server/src/ma n/scala/com/tw ter/representat on_manager/m grat on",
        "representat on-scorer/server/src/ma n/scala/com/tw ter/representat onscorer/common",
        "servo/ut l",
        "src/scala/com/tw ter/s mclusters_v2/stores",
        "src/scala/com/tw ter/storehaus_ nternal/ mcac ",
        "src/scala/com/tw ter/storehaus_ nternal/ut l",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
    ],
)
