scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f natra/thr ft/src/ma n/scala/com/tw ter/f natra/thr ft",
        "f natra/thr ft/src/ma n/scala/com/tw ter/f natra/thr ft:controller",
        "f natra/thr ft/src/ma n/scala/com/tw ter/f natra/thr ft/except ons",
        "f natra/thr ft/src/ma n/scala/com/tw ter/f natra/thr ft/f lters",
        "f natra/thr ft/src/ma n/scala/com/tw ter/f natra/thr ft/modules",
        "f natra/thr ft/src/ma n/scala/com/tw ter/f natra/thr ft/response",
        "f natra/thr ft/src/ma n/scala/com/tw ter/f natra/thr ft/rout ng",
    ],
)
