scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/b ject on:core",
        "ann/src/ma n/scala/com/tw ter/ann/common",
        "ann/src/ma n/thr ft/com/tw ter/ann/ser al zat on:ser al zat on-scala",
        " d aserv ces/commons",
        "scrooge/scrooge-core",
        "src/scala/com/tw ter/scald ng_ nternal/mult format/format",
    ],
)
