scala_l brary(
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependenc es = [
        "3rdparty/jvm/com/tw ter/storehaus:core",
        " rm / rm -core/src/ma n/scala/com/tw ter/ rm /store/common",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/scala/com/tw ter/storehaus_ nternal/manhattan",
        "src/scala/com/tw ter/storehaus_ nternal/ut l",
        "src/scala/com/tw ter/wtf/scald ng/jobs/ nject on",
        "src/thr ft/com/tw ter/recos/ent  es:ent  es-thr ft-scala",
        "storage/cl ents/manhattan/cl ent/src/ma n/scala",
    ],
)
