target(
    dependenc es = [
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y",
    ],
)

target(
    na  = "conversat ons",
    dependenc es = [
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/ nterfaces/common/t ets",
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/ nterfaces/conversat ons",
    ],
)

target(
    na  = "t ets",
    dependenc es = [
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/generators",
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/ nterfaces/common/t ets",
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/ nterfaces/t ets",
    ],
)

target(
    na  = "users",
    dependenc es = [
        "v s b l y/l b/src/ma n/scala/com/tw ter/v s b l y/ nterfaces/users",
    ],
)
