create_thr ft_l brar es(
    org = "com.tw ter",
    base_na  = "un f ed_user_act ons",
    s ces = ["*.thr ft"],
    tags = ["bazel-compat ble"],
    dependency_roots = [
        "src/thr ft/com/tw ter/cl entapp/gen:cl entapp",
        "src/thr ft/com/tw ter/g zmoduck:thr ft",
        "src/thr ft/com/tw ter/g zmoduck:user-thr ft",
        "src/thr ft/com/tw ter/search/common:constants",
        "src/thr ft/com/tw ter/soc algraph:thr ft",
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    prov des_java_na  = "un f ed_user_act ons-thr ft-java",
    prov des_scala_na  = "un f ed_user_act ons-thr ft-scala",
)
