target(
    tags = ["bazel-compat ble"],
    dependenc es = [
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/backends",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/conf g",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/core",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/handler",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/hydrator",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/ d a",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/repos ory",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/serverut l",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/serv ce",
        "t etyp e/server/src/ma n/scala/com/tw ter/t etyp e/store",
    ],
)