create_thr ft_l brar es(
    base_na  = "ann-common",
    s ces = ["*.thr ft"],
    platform = "java8",
    tags = ["bazel-compat ble"],
    dependency_roots = [
        " d aserv ces/commons/src/ma n/thr ft",
        "src/thr ft/com/tw ter/ml/ap :embedd ng",
    ],
    generate_languages = [
        "java",
        "python",
        "scala",
        "strato",
    ],
    prov des_java_na  = "ann-common-thr ft-java",
    prov des_scala_na  = "ann-common-thr ft-scala",
)
