scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "conf gap /conf gap -core",
        "content-recom nder/thr ft/src/ma n/thr ft:thr ft-scala",
        "cr-m xer/thr ft/src/ma n/thr ft:thr ft-scala",
        "product-m xer/core/src/ma n/thr ft/com/tw ter/product_m xer/core:thr ft-scala",
        "src/scala/com/tw ter/s mclusters_v2/common",
        "src/thr ft/com/tw ter/core_workflows/user_model:user_model-scala",
        "src/thr ft/com/tw ter/recos:recos-common-scala",
        "src/thr ft/com/tw ter/s mclusters_v2:s mclusters_v2-thr ft-scala",
    ],
)
