scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    platform = "java8",
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featuremap",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common/ dent f er",
        "st ch/st ch-core",
        "ut l/ut l-jackson/src/ma n/scala/com/tw ter/ut l/jackson",
    ],
    exports = [
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/feature/featuremap",
        "product-m xer/core/src/ma n/scala/com/tw ter/product_m xer/core/model/common/ dent f er",
        "st ch/st ch-core",
    ],
)
