python3_l brary(
    na  = "l bs",
    s ces = ["*.py"],
    tags = [
        "bazel-compat ble",
        "no- py",
    ],
    dependenc es = [
        "cortex/recsys/src/python/tw ter/cortex/recsys/ut ls",
        "mag cpony/common/f le_access/src/python/tw ter/mag cpony/common/f le_access",
        "src/python/tw ter/cortex/ml/embedd ngs/deepb rd",
        "src/python/tw ter/cortex/ml/embedd ngs/deepb rd/grouped_ tr cs",
        "src/python/tw ter/deepb rd/ut l/data",
        "twml:twml-nodeps",
    ],
)
