scala_l brary(
    comp ler_opt on_sets = ["fatal_warn ngs"],
    tags = [
        "bazel-compat ble",
    ],
    dependenc es = [
        "f natra/ nject/ nject-thr ft-cl ent",
        "strato/src/ma n/scala/com/tw ter/strato/fed",
        "strato/src/ma n/scala/com/tw ter/strato/fed/server",
        "top c-soc al-proof/server/src/ma n/scala/com/tw ter/tsp/columns",
    ],
)
