scala_l brary(
    s ces = ["*.scala"],
    comp ler_opt on_sets = ["fatal_warn ngs"],
    str ct_deps = True,
    tags = ["bazel-compat ble"],
    dependenc es = [
        "f nagle- nternal/mtls/src/ma n/scala/com/tw ter/f nagle/mtls/aut nt cat on",
        "f nagle- nternal/mtls/src/ma n/scala/com/tw ter/f nagle/mtls/author zat on",
        "f nagle/f nagle-core/src/ma n",
        "f nagle/f nagle-thr ftmux/src/ma n/scala",
        "src/scala/com/tw ter/storehaus_ nternal/manhattan/conf g",
        "src/thr ft/com/tw ter/manhattan:v1-scala",
        "storage/cl ents/manhattan",
        "ut l/ut l-core",
    ],
    exports = [
        "f nagle- nternal/mtls/src/ma n/scala/com/tw ter/f nagle/mtls/aut nt cat on",
        "f nagle- nternal/mtls/src/ma n/scala/com/tw ter/f nagle/mtls/author zat on",
        "f nagle/f nagle-core/src/ma n",
        "src/scala/com/tw ter/storehaus_ nternal/manhattan/conf g",
        "storage/cl ents/manhattan",
        "ut l/ut l-core",
    ],
)
