package com.tw ter.follow_recom ndat ons.products.common

 mport com.tw ter.follow_recom ndat ons.assembler.models.La t
 mport com.tw ter.follow_recom ndat ons.common.base.BaseRecom ndat onFlow
 mport com.tw ter.follow_recom ndat ons.common.base.Transform
 mport com.tw ter.follow_recom ndat ons.common.models.D splayLocat on
 mport com.tw ter.follow_recom ndat ons.common.models.Recom ndat on
 mport com.tw ter.follow_recom ndat ons.models.Recom ndat onRequest
 mport com.tw ter.product_m xer.core.model.marshall ng.request.{Product => ProductM xerProduct}
 mport com.tw ter.st ch.St ch
 mport com.tw ter.t  l nes.conf gap .Params

tra  Product {

  /** Each product also requ res a human-readable na .
   *   can change t  at any t  
   */
  def na : Str ng

  /**
   * Every product needs a mach ne-fr endly  dent f er for  nternal use.
   *   should use t  sa  na  as t  product package na .
   * Except das s are better than underscore
   *
   * Avo d chang ng t  once  's  n product on.
   */
  def  dent f er: Str ng

  def d splayLocat on: D splayLocat on

  def selectWorkflows(
    request: ProductRequest
  ): St ch[Seq[BaseRecom ndat onFlow[ProductRequest, _ <: Recom ndat on]]]

  /**
   * Blender  s respons ble for blend ng toget r t  cand dates generated by d fferent flows used
   *  n a product. For example,  f a product uses two flows,    s blender's respons b l y to
   *  nterleave t  r generated cand dates toget r and make a un f ed sequence of cand dates.
   */
  def blender: Transform[ProductRequest, Recom ndat on]

  /**
   *    s resultsTransfor r job to do any f nal transformat ons needed on t  f nal l st of
   * cand dates generated by a product. For example,  f a f nal qual y c ck on cand dates needed,
   * resultsTransfor r w ll handle  .
   */
  def resultsTransfor r(request: ProductRequest): St ch[Transform[ProductRequest, Recom ndat on]]

  def enabled(request: ProductRequest): St ch[Boolean]

  def la t: Opt on[La t] = None

  def productM xerProduct: Opt on[ProductM xerProduct] = None
}

case class ProductRequest(recom ndat onRequest: Recom ndat onRequest, params: Params)
